### ISSUE TITLE
Last N and Dominant speaker messages on data channel

### ISSUE THREAD

**Issue by xdumaine** [jitsi/jitsi-videobridge#105]
I’m trying to get last n and dominant speaker events hooked up in my app. I have the data channel established, and I’m getting endpointsEnteringLastN messages on the datachannel firing as participants join the conference, but I never get any messages for dominant speaker, and lastNEndpoints never change based on who’s actually speaking. Am I missing something? Do I need to send messages on the data channel to the bridge? I thought it would be checking RTP header extensions to determine the active/dominant speakers. The documentation on this is non existent :(

**Comment by lyubomir** [comment]
Which library is generating the RTP on the client? Does it implement RFC 6464?

**Comment by xdumaine** [comment]
I'm using Chrom[e|ium] 46+

**Comment by lyubomir** [comment]
It's the first time I'm hearing of this issue. If you're able to provide a minimal example that would allow me to reproduce the issue on my machine, I should be able to squeeze a debug session it in my schedule.

**Comment by xdumaine** [comment]
I'm not sure how I'd create a minimal example. I've got a jingle.js supporting app going through an XMPP server translating (focus controller) to jitsi.

**Comment by lyubomir** [comment]
Can you provide a dump of unencrypted RTP traffic from the client to Videobridge and a Java heap dump of Videobridge then?

**Comment by xdumaine** [comment]
I was able to solve my problem. I was adding the RTP header extensions to the client offers, but not to the channels created on the videobridge. More documentation would help.

**Comment by lyubomir** [comment]
@xdumaine, that's good news! Thank you for the update. Please feel free to contribute documentation on the subject.

**Comment by xdumaine** [comment]
@lyubomir I definitely will. Thanks again for your time!
