### ISSUE TITLE
Optionally emit audio levels over Last-N data channel

### ISSUE THREAD

**Issue by xdumaine** [jitsi/jitsi-videobridge#108]
I'm curious about the idea of emitting audio levels periodically over the data channel (it doesn't have to be the last-n data channel, but could be, or another one like audio-levels). The use case is for conferences that want to display an audio bar or visual speaking indicator for users with or without video. Since the video bridge already has the audio levels for last-n, and already has a data channel for endpoint signaling, this seems natural and easy. I'm willing to work on implementing this. Does anyone have any thoughts or ideas on the subject?

**Comment by xdumaine** [comment]
```json
{ 
    audioLevels: [
        {
            endpoint: 'alice@example.com',
            audioLevel: 123
        },
        {
            endpoint: 'bob@example.com',
            audioLevel: 123
        }
    ]
```

**Comment by damencho** [comment]
This is already possible in the client, check it out on meet.jit.si and does not require additional signaling cause the audio levels are already present in the RTP packets and can be handled by the clients.
