### ISSUE TITLE
adaptiveLastN and adaptiveSimulcast not deserialized?

### ISSUE THREAD

**Issue by markreg** [jitsi/jitsi-videobridge#110]
Are `adaptiveLastN` and `adaptiveSimulcast` not supported? They aren't deserialized in:

https://github.com/jitsi/jitsi-videobridge/blob/0b56824d0434f22a132171caa8831999391dbe75/src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java#L130

**Comment by bgrozev** [comment]
It is currently experimental and only supported through the XMPP interface.
