### ISSUE TITLE
Add *jitsi-videobridge2* to dependencies of Debian package *jitsi-meet*

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-videobridge#1139]
Trying to install *jitsi-videobridge2* from the unstable archive, APT wants to remove *jitsi-meet*, as it depends on *jitsi-videobridge*. Therefore, *jitsi-videobridge2* should be added to the dependency list.

**Comment by damencho** [comment]
I'm currently working on that. Please use the community forum before opening new issues.
