### ISSUE TITLE
Pause streaming from unforwarded endpoints?

### ISSUE THREAD

**Issue by markreg** [jitsi/jitsi-videobridge#114]
If `endpoint A` is not within the `lastN` of any other connected `endpoints B-Z`, is it possible for JVB to send a message over datachannel to `endpoint A` to pause transmission of its stream(s) until it becomes the dominant speaker?

Possibly only video streams since audio-levels from the audio streams from `endpoint A` would still be required to determine dominant speaker.

This would save incoming bandwidth to JVB and outgoing from `endpoint A`. Although, would the latency of restarting transmission and renegotiating be problematic?

**Comment by bgrozev** [comment]
It does: https://github.com/jitsi/jitsi-videobridge/blob/master/src/main/java/org/jitsi/videobridge/VideoChannel.java#L576
I am not sure about the way current clients handle it, though. We also ran some tests (section 5.4 (here)[https://jitsi.org/publications/nossdav2015lastn.pdf]).

**Comment by markreg** [comment]
I may have missed that datachannel event. So, as I understand it, there's are events for changes in: old/new endpoints, new dominant speaker, and lastn inclusion, correct?

**Comment by bgrozev** [comment]
Yes, there are events from the bridge to a client for:
*changes to the set of streams forwarded to the client
*changes of the dominant speaker
*changes to whether or not the client's video stream is forwarded to another endpoint/client

**Comment by niallmurphy-ie** [comment]
Hi,

On a recent build, users whose video stream isn't being watched by anyone else still upload the full amount of data. So it's a black screen but over 1mbps upload.

Is this an error on my part?

Thanks

**Comment by bbaldino** [comment]
Unfortunately we had a regression and this feature broke sometime in the last few months.  It hasn't been fixed because we decided to defer fixing it until we merge in the new bridge code, which we expect to be doing soon(ish).

**Comment by niallmurphy-ie** [comment]
Thanks for replying. It's a pretty major difference to bandwidth so work on it is much appreciated.
