### ISSUE TITLE
plzz help me  i am create jisti meet jitsi meet load balancing aws but i dont show first videobridge components /etc/prosody/conf.d# nano suprobhat.supu.best.cfg.lua this terminal

### ISSUE THREAD

**Issue by suprobhat** [jitsi/jitsi-videobridge#1143]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by bbaldino** [comment]
Please read what the bug template says.  Try the community.

**Comment by suprobhat** [comment]
plzz help me any one
