### ISSUE TITLE
Potential VP9 support for use with Chrome M49?

### ISSUE THREAD

**Issue by markreg** [jitsi/jitsi-videobridge#115]

**Comment by fippo** [comment]
the bridge itself is codec-agnostic. VP9 just works (with some bugs) if the focus negotiates things.

**Comment by markreg** [comment]
Does the recording functionality work as well?

**Comment by bgrozev** [comment]
No, the current recording solution is VP8-only.

**Comment by gpolitis** [comment]
We also need to be able to detect key frames for simulcast to work properly but that should be fairly easy to implement.
