### ISSUE TITLE
NullPointerException in IceTransport

### ISSUE THREAD

**Issue by ghost** [jitsi/jitsi-videobridge#1162]
## Description
Since update to version 2020-04-03 only conferences with two persons work, starting with third person there is no video and no audio except the own.

## Current behavior
not working, log shows:
java.lang.NullPointerException
	at org.ice4j.ice.Agent.<init>(Agent.java:400)
	at org.jitsi.videobridge.ice.IceTransport.createIceAgent(IceTransport.java:252)
	at org.jitsi.videobridge.ice.IceTransport.<init>(IceTransport.java:157)
	at org.jitsi.videobridge.DtlsTransport.<init>(DtlsTransport.java:128)
	at org.jitsi.videobridge.Endpoint.<init>(Endpoint.java:269)
	at org.jitsi.videobridge.Endpoint.<init>(Endpoint.java:285)
	at org.jitsi.videobridge.Conference.createLocalEndpoint(Conference.java:692)
...

## Expected Behavior
No NullPointerException but working with more than 2 persons.

## Steps to reproduce
Fresh install on debian 10 plus "secure domain" as in https://github.com/jitsi/jicofo 

# Environment details
clean debian 10 with apt-get jitsi-meet and secure domain setup.

**Comment by bgrozev** [comment]
Thanks for the report. Can you please post full logs, or grep for `MappingCandidateHarvester` in the logs?

**Comment by jitsiissues** [comment]
I'm very sorry - after hours of re-installing with videobridge2 I killed the machine and went back to jitsi-meet-Packages with videobridge (instead of videobridge2).

**Comment by bgrozev** [comment]
I can reproduce the problem if I intentionally use wrong syntax in the config file. I opened jitsi/ice4j#193 to fix it, but it will not fix the underlying config problem (the harvesters will not be initialized, and you will see a single exception in the logs at startup).

I was not able to repro it on a clean debian 10 installation. If you see it again, please post again and include the content of `/etc/jitsi/videobridge/sip-communicator.properties` (or at least grep for `ice4j`) and the startup log file.

**Comment by jitsiissues** [comment]
Thank you very much for testing, reporting and opening a ticket at the right target. I must admit that "clean install" was "clean install + secure domain setup" (added note in post above).

Indeed the sip-communicator.properties after installation in /etc/jitsi/jicofo/sip-communicator.properties (your path had "videobridge"?) was
  org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth.MY-JITSI.COM
which I changed to
  org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth.MY-JITSI.COM
  org.jitsi.jicofo.auth.URL=XMPP:MY-JITSI.COM
to have secure domain setup. With videobridge1, the file was empty after installation.

**Comment by jitsiissues** [comment]
This is my jitsi-install log after debian 10 install:

- import jitsi key
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
  create /etc/apt/sources.list.d/jitsi-stable.list, insert text:
    deb https://download.jitsi.org stable/
  refresh packages
    apt-get update
  start installation
    apt-get install jitsi-meet
- create certificate, copy to
    copy key to /etc/jitsi/meet/MY-JITSI.key
    copy cert with chain to /etc/jitsi/meet/MY-JITSI.crt
- change /etc/prosody/conf.avail/MY-JITSI
    authentication = "internal_plain"
  now user can be added via
    prosodyctl adduser USER@MY-JITSI
  see /var/lib/prosody/MY-JITSI/accounts
- change /etc/nginx/nginx.conf to have
    server_tokens off;
- secure domain setup change following files
    /etc/prosody/conf.avail/MY-JITSI.cfg.lua
      [VirtualHost "MY-JITSI"
        authentication = "internal_plain"
      [add at bottom
      VirtualHost "guest.MY-JITSI"
        authentication = "anonymous"
        c2s_require_encryption = false
    /etc/jitsi/meet/MY-JITSI-config.js
      [domain: 'MY-JITSI'
      anonymousdomain: 'guest.MY-JITSI',
      [activate
      requireDisplayName: true,
    /etc/jitsi/jicofo/sip-communicator.properties
      [with videobridge1: empty, with videobridge2 existing line
      org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth.jitsi.hs-kempten.de
      [add line
      org.jitsi.jicofo.auth.URL=XMPP:jitsi.hs-kempten.de

**Comment by jitsiissues** [comment]
This is my jitsi-install log after debian 10 install:

    import jitsi key
    wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
    create /etc/apt/sources.list.d/jitsi-stable.list, insert text:
    deb https://download.jitsi.org stable/
    refresh packages
    apt-get update
    start installation
    apt-get install jitsi-meet
    create certificate and
    copy key to /etc/jitsi/meet/MY-JITSI.key
    copy cert with chain to /etc/jitsi/meet/MY-JITSI.crt
    change /etc/prosody/conf.avail/MY-JITSI
    authentication = "internal_plain"
    now user can be added via
    prosodyctl adduser USER@MY-JITSI
    see /var/lib/prosody/MY-JITSI/accounts
    change /etc/nginx/nginx.conf to have
    server_tokens off;
    secure domain setup change following files
    -- /etc/prosody/conf.avail/MY-JITSI.cfg.lua
    [VirtualHost "MY-JITSI"
    authentication = "internal_plain"
    [add at bottom
    VirtualHost "guest.MY-JITSI"
    authentication = "anonymous"
    c2s_require_encryption = false
    -- /etc/jitsi/meet/MY-JITSI-config.js
    [domain: 'MY-JITSI'
    anonymousdomain: 'guest.MY-JITSI',
    [activate
    requireDisplayName: true,
    -- /etc/jitsi/jicofo/sip-communicator.properties
    [with videobridge1: empty, with videobridge2 existing line
    org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@internal.auth.MY-JITSI
    [add line
    org.jitsi.jicofo.auth.URL=XMPP:MY-JITSI

**Comment by bgrozev** [comment]
Please re-open and include the contents of `/etc/jitsi/videobridge/sip-communicator.properties` if this happens again
