### ISSUE TITLE
Support for endpoints which uses different payload types for same codec.

### ISSUE THREAD

**Issue by mstyura** [jitsi/jitsi-videobridge#1163]
Hi,
I'd like to discuss the support of heterogenous WebRTC-endpoints in JVB 2.0.

Please note, I'll describe the scenario in a context of my use-case: I use JVB with my own signaling on top of it (not using jicofo/jitsi meet).

The flow of joining the conference in my case is the following:

1. Client create peer connection. Adds send-only `RTCRtpTransceiver` for outbound audio and video. 
2. Client create offer and send it to custom signaling to join the conference.
 Typical offer would look like this ()
```
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=mid:0
a=sendrecv
a=msid:c3ce0974-437c-4792-95e7-7bac8fcadb36 34517d54-6f21-4527-a017-12eac50a96ef
a=ssrc:2285997888 cname:bfGDkSeJ5uT0ADKP
m=video 9 UDP/TLS/RTP/SAVPF 96 97
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=mid:1
a=sendrecv
a=msid:c3ce0974-437c-4792-95e7-7bac8fcadb36 7730f97d-31a1-4937-9233-06312c3f002f
a=ssrc-group:FID 2546541619 25938643
a=ssrc:2546541619 cname:bfGDkSeJ5uT0ADKP
a=ssrc:25938643 cname:bfGDkSeJ5uT0ADKP
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
a=mid:2
```

3. In response to join request client receives answer:
```
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=recvonly
a=mid:0
m=video 9 UDP/TLS/RTP/SAVPF 96
a=recvonly
a=mid:1
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
a=mid:2
```
4. At this point RTCPeerConnection on client establishes connection with JVB 2.0. Data Channel is then used to notify when additional clients joins the conference, the updated conference description (offer from JVB side having new clients description) is sent over data chanel. This offer from signaling server causes creation of additional receive-only `RTCRtpTransceiver` per each of media track of remote endpoint.

In my case client could be mobile client on Android or iOS or Chromium browser or Firefox.
So there are a variety of clients, having slightly different WebRTC configuration. 
Clients are not restricted on set of codecs and payload types used in join offer sent to signaling server.
Signaling server does some filtering of payload types like disabling everything which is not supported (actually not tested yet).
Basically for audio only OPUS codec is allowed and for video only VP8 with RTX.
But there is still no restriction on payload type used for a specific codec.

E.g. different clients could join the conference on JVB having OPUS mapped on different payload types: for example, typical payload type of OPUS in Firefox is 109 and typical payload type for OPUS in Chromium(or WebRTC for iOS and Android) is 111.
The same could be said about video coded payload types - different clients could join conference with different payload types chosen for VP8 and RTX. 
Chromium and WebRTC iOS and Android have all different payload type for VP8 and RTX.

Such heterogeneity of clients (endpoints) within same conference is perfectly expressed with Unified Plan SDPs.
A typical offer (non important lines were omitted) which client A receives when client B joins the conference having different payload type for codec look like this:
```
a=group:BUNDLE 0 1 2 65 64
m=audio 9 UDP/TLS/RTP/SAVPF 111
a=recvonly
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=mid:0
m=video 9 UDP/TLS/RTP/SAVPF 96
a=recvonly
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=bundle-only
a=mid:1
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
a=sctp-port:5000
a=mid:2
m=video 9 UDP/TLS/RTP/SAVPF 120
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:120 VP8/90000
a=fmtp:120 max-fs=12288;max-fr=60
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=ssrc:3681144746 cname:789889ce7ecb33ab
a=ssrc:3681144746 msid:{279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0} {061afa1b-3089-40b1-80da-98b7a14daea5}
a=msid:{279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0} {279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0}
a=mid:65
m=audio 9 UDP/TLS/RTP/SAVPF 109
a=sendonly
a=rtpmap:109 opus/48000/2
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=ssrc:779926115 cname:789889ce7ecb33ab
a=ssrc:779926115 msid:{279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0} {1affa383-8206-4f35-84c9-be7a0ff5aa58}
a=msid:{279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0} {279eda2e-b564-4dd3-8f84-3e2ba8d6d6d0}
a=mid:64
``` 

Please note, that different `m=audio` and `m=video` lines have different payload types.

The behavior I observe on JVB 1 and JVB 2 is completely different here.
JVB 1 does "re-payloading", e.g.  it changes payload type from sender opus 111, to receiver opus 109 and vise versa. The same is done for VP8.
As far as I understand that was necessary at time JVB 1 is written, because of lack of Unified Plan and restrictions implied by Plan B: having single `m=audio` and `m=video` for all inbound media.
Hence on Plan B all the remote tracks has to use same payload types for codes, because there is no way to express other.

JVB 2 behavior in case different payloads is different, it just forward the packet with original payload type. 
So, if Chrome sends OPUS with pt=111, Firefox will receive packet form Chrome with pt=111, and FF sending Opus with PT=109 and Chrome will receive OPUS with pt=109 from FF.
This works today with current JVB 2.0 with carefully generated Unified Plan sdp where each endpoint has dedicated `m=` line for media having it's own set of codes and payload types assignment.
I like the approach the JVB 2 uses! Both because of simplicity and power when combined with Unified Plan SPDs.

But currently there is probably a bug (or just not yet implemented or I misconfigured JVB in my signaling server) support of VP8 video on different payload types on different endpoints.
When I create a conference with Firefox and Chrome, which uses different payload types for VP8 - Chrome uses pt=96, FF uses pt=120 I see that JVB 2.0 just drop packets from both of the clients.
The packet dropped with the following lines logged:
```
2020-04-02 21:32:48,965| ERROR|            Global CPU pool-5| o.j.v.c.AdaptiveTrackProjection     ::log                          @ 111| No payload type object signalled for payload type 96 yet, cannot create track projection context
2020-04-02 21:32:48,968| DEBUG|            Global CPU pool-8| o.j.v.c.AdaptiveTrackProjection     ::log                          @ 122|  adaptive track projection  creating context for payload type 96
```

When I just modify bitrate controller to accept all of the packets (to avoid intentional drop of packets) video starts working between Chrome and Firefox, even so payload type of VP8 is different on both endpoints, but this is resolved by carefully generated Unified Plan SDP by signaling server.

So my questions are:
1. Was the scenario of mismatched payload types is considered supported by JVB 2.0, or it just happen because it was supposed that all clients use same payload type assignments for a codec and that's why there is no "re-payloading"?
2. Or I just misconfigured JVB 2.0 and that's why it is dropping video packets?
3. Would you mind if I'll work on adding support of different payload types for same codec between different endpoints if this scenario was not considered before?

Thanks a lot in advance!

**Comment by mstyura** [comment]
I've done some debugging and found out that `AdaptiveTrackProjection` used `payloadTypes` of destination endpoint, not the endpoint originating RTP packet. 
So when two endpoints have exactly same payload types assignment everything works fine, but when they have different payload types assignment the packet from source endpoint is rejected, because payload type is searched in the destination endpoint payload types.

**Comment by bbaldino** [comment]
We didn't to intend to break support for this in JVB 2--to be honest I think we (or at least I) had lost track of the fact that JVB 1 supported this :)

That being said, we have discussed it a couple times and never felt the need to support it since it doesn't occur in our use case.  That being said, I don't think we'd be against fixing it (assuming the implementation doesn't involve too many compromises in the code or efficiency)...so, PR welcome (and I made a comment on the one you opened).

**Comment by mstyura** [comment]
> We didn't to intend to break support for this in JVB 2--to be honest I think we (or at least I) had lost track of the fact that JVB 1 supported this :)

If you've meant re-payloading from JVB 1, so I don't regret it was removed, because I believe it only complicate things, while have no real sense for modern peers with Unified Plan support.

> That being said, I don't think we'd be against fixing it (assuming the implementation doesn't involve too many compromises in the code or efficiency)...so, PR welcome (and I made a comment on the one you opened).

I also hope that supporting scenario I've raised won't require big changes: so far PR I've provided at least make VP8 video work on different payloads. It also seems safe for your scenario to introduce the changes I've proposed in PR - as long as in you scenarios all payload types the same between endpoints there is no big different from which endpoint to obtain payload types map :)

**Comment by bbaldino** [comment]
> If you've meant re-payloading from JVB 1, so I don't regret it was removed, because I believe it only complicate things, while have no real sense for modern peers with Unified Plan support.

If this is the case, I don't follow why you'd want this change?

**Comment by mstyura** [comment]
@bbaldino because I have peers which uses different payload types for the same codec, but this does not work well with current JVB without [a change I've requested](https://github.com/jitsi/jitsi-videobridge/pull/1164) - payload type looked in the wrong map. But totally work fine with proposed small changes. This works with unified plan SDPs applied into peer connection (multiple m= lines each having own codec definitions).

**Comment by bbaldino** [comment]
But I thought you said you were glad repayloading was removed, because it complicates things.  But to solve the case you describe, that require repayloading, no? Maybe I'm misunderstanding you.
