### ISSUE TITLE
'Address discovery through STUN failed' every ten seconds. Which port should be open?

### ISSUE THREAD

**Issue by Gregoire-M** [jitsi/jitsi-videobridge#1165]
## Description

`jvb.log` is looping on the same error: 

```
2020-04-03 18:50:30.703 SEVERE: [17] Health.doRun#300: Health check failed in 0ms:
java.lang.Exception: Address discovery through STUN failed
	at org.jitsi.videobridge.health.Health.doCheck(Health.java:138)
	at org.jitsi.videobridge.health.Health.doRun(Health.java:266)
	at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
```

I suspect that iptables blocks a request but I can't find which port I'm supposed to open.

My firewall policy is to drop everything except the ports I whitelist. Here is an overview of my config:

```
iptables -t filter -F
iptables -t filter -X
iptables -t filter -P INPUT DROP
iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT DROP

iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT # http
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT # https
iptables -t filter -A INPUT -p udp --dport 3478 -j ACCEPT # STUN (for jitsi)
iptables -t filter -A INPUT -p udp --dport 10000 -j ACCEPT # jitsi
iptables -t filter -A OUTPUT -p udp --dport 10000 -j ACCEPT # jitsi
iptables -t filter -A OUTPUT -p udp --dport 19302 -j ACCEPT # STUN (for jitsi)
```

## Current behavior
Tons of log in `/var/log/jitsi/jvb.log`. One per 10 seconds.

## Expected Behavior
No more 'severe' log.

## Possible Solution
List the ports that need to be open.

## Steps to reproduce
Fresh install of `jitsi-meet` deb package, iptables with above configuration.

## Environment details
Ubuntu 18.04.4 LTS server.
jitsi-meet/stable,now 2.0.4384-1 all
jitsi/stable 2.10.5550-1 amd64
jitsi-videobridge/stable 1126-1 amd64

**Comment by rubenk** [comment]
No clue on the actual port, but perhaps you could add a log rule to iptables to log your dropped traffic?

**Comment by damencho** [comment]
It is outgoing udp 443.
https://github.com/jitsi/jitsi-videobridge/blob/master/debian/postinst#L102
Similar to iptables -t filter -A OUTPUT -p udp --dport 19302 -j ACCEPT # STUN (for jitsi)
But it is now 443.

**Comment by damencho** [comment]
Please use the community forum when having questions or problems before opening new issues.

**Comment by Gregoire-M** [comment]
Thank you for your answers. But I still have the same problem after opening outgoing UDP 443.

Nobody could answer me on [community forum](https://community.jitsi.org/t/firewall-i-guess-issues-after-deb-package-install-of-jitsi-meet/28747).

**Comment by damencho** [comment]
Still haven't been able to come to that one I guess, I'm trying to answer everybody but does not always find the time in one day ...

**Comment by bgrozev** [comment]
I don't know why STUN discovery fails, but you can work around it by removing the STUN config in `/etc/jitsi/videobridge/sip-communicator.properties`. If you're behind a NAT you can replace it with preconfigured addresses: https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address

**Comment by Gregoire-M** [comment]
Actually, after opened outgoing UDP 443, and restarting service jitsi-videobridge2 (I wasn’t aware this step was required), it works fine :)
Many thanks for your help!
