### ISSUE TITLE
Add documentation for Pinning endpoint video in Last N

### ISSUE THREAD

**Issue by xdumaine** [jitsi/jitsi-videobridge#117]
I'm using last-n on the videobridge via colibri/focus controller, but I would like the ability for users to "override" the last-n setting for a single video stream. There are two specific use cases for this:

1. **Implicit override:** lastN = 2; Users A and B are speaking; User C is sharing screen. I would like User C's screen stream to always be visible to other users, regardless of the fact that Users A and B are speaking.

2. **Explicit override:** User D wants to view User B's video stream regardless of who is speaking, so User D focuses User B in the user interface, triggering some signal to always forward user B's video stream, overriding the Last N endpoints.

Are either of these possible?

**Comment by bgrozev** [comment]
We have the concept of a "pinned" endpoint (which we plan to extend to a set of "pinned" endpoints in the near future) which does pretty much what your case "2" describes. It is configured with a message like this from a client to the bridge over the data channel:
{colibriClass: "PinnedEndpointChangedEvent", pinnedEndpoint: "endpoint-id"}

This can also be used to implement case "1", although not in the cleanest possible way. It seems that for a conference-wide "pin", signalling from the focus (via colibri) is more appropriate, but we don't have any of that implemented.

**Comment by xdumaine** [comment]
@bgrozev Oh neat, that sounds promising. Is there a difference between a selected endpoint and a pinned endpoint?

**Comment by bgrozev** [comment]
"Pinned" has to do with Last-N: a pinned endpoint's video will not be dropped, even it it isn't the active speaker.

"Selected" has to do with simulcast: video from a selected endpoint will always be forwarded in high quality.

**Comment by xdumaine** [comment]
Perfect, thanks.

**Comment by jitsi-developers** [comment]
What Will happen if we set last n=1 ?

**Comment by bgrozev** [comment]
Now included here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/last-n.md
