### ISSUE TITLE
It doesn't work if there are more than 2 users in the room.(Only P2P)

### ISSUE THREAD

**Issue by LDelOff** [jitsi/jitsi-videobridge#1180]
I install jitsi-meet on my Orangу PI 3.
If 2 users on room, all work (p2p)
If more - not audio and video.
 
All ports are routed to orange pi(and 443, 4443 and 10000).
I try:
- reintall jitsi
- https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
[sip-communicator.properties.txt](https://github.com/jitsi/jitsi-videobridge/files/4456793/sip-communicator.properties.txt)

my log jicofo
[jicofo.log](https://github.com/jitsi/jitsi-videobridge/files/4456806/jicofo.log)

I check https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
But I didn't know what to do.

**Comment by bgrozev** [comment]
See #1177

**Comment by LDelOff** [comment]
Yes,all works correctly.
Thank you very much!!!!!
