### ISSUE TITLE
/colibri/stats stopped reporting total_memory, used_memory and cpu_usage

### ISSUE THREAD

**Issue by lephisto** [jitsi/jitsi-videobridge#1181]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
```/colibri/stats``` stopped reporting total_memory, used_memory and cpu_usage
## Current behavior
```/colibri/stats``` stopped reporting total_memory, used_memory and cpu_usage

## Expected Behavior
```/colibri/stats``` is reporting total_memory, used_memory and cpu_usage

## Steps to reproduce
Use latest Jitsi-Videobridge release and enable Stats API Endpoint

# Environment details
Most recent Docker Compose Stack

**Comment by JonathanLennox** [comment]
This was deliberate - see the Community post at https://community.jitsi.org/t/proposed-videobridge-stats-removal/20431 .

We recommend using `statsd` or some other system-level monitoring service to monitor these statistics.
