### ISSUE TITLE
Turning off IPv6 support

### ISSUE THREAD

**Issue by Tulkas59** [jitsi/jitsi-videobridge#1182]
## Description
I would like to turn off IPv6 support.
- Prosody. Done. I just read the documentation (https://prosody.im/doc/ports).
- Meet. Done. I set `useIPv6 = false` (even if this parameter seems to be deprecated) and configured apache appropriately.
- Jicofo. Done. Setting `-Djava.net.preferIPv4Stack=true` seems to do the trick.
- Videobridge. I set `-Djava.net.preferIPv4Stack=true `and `org.ice4j.ipv6.DISABLED=true` but JVB is still listening on UDP6 port 5000.

All of this was already discussed in the community forum (https://community.jitsi.org/t/how-to-configure-the-whole-jitsi-stack-to-use-ipv4-only/30303/6) but I failed to get an answer. I am now guessing it is actually an issue.

Note that I still do not know the role of this port. I did not open it and all is working fine.

## Current behavior
Setting `org.ice4j.ipv6.DISABLED=true` does not turn off IPv6 completely. JVB is still listening on UDP6 port 5000.

## Expected Behavior
JVB does not listen on any TCP6 or UDP6 port.

## Environment details
Jitsi-meet stable package (auto install) on debian buster.

All the best,

**Comment by bgrozev** [comment]
See this docs: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md#configuration-of-ice4j

Contributions to make this more visible are welcome

**Comment by Tulkas59** [comment]
I already read this doc. My point is that setting org.ice4j.ipv6.DISABLED=true does not completely turn off IPv6.

Did I miss something ? Would you prefer I drop this question in ice4j's repository ?
