### ISSUE TITLE
Use native distro installed jna.jar

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-videobridge#1190]
Debian Buster, arm64, Java 11

In order to get native srtp .so I can build the lib locally (https://github.com/jitsi/jitsi-srtp/pull/6) and replace the jar in the videobridge folder, but now at run time the videobridge fails to find `libjnidispatch.so` for this arch.

On Debian Buster I can install [libjna-java](https://packages.debian.org/buster/libjna-java) which brings `jna(-4.5.2).jar` and has a dep on [libjna-jni](https://packages.debian.org/buster/libjna-jni) which brings `libjnidispatch.system.so` fulfilling all the deps.

The problem is that at compile time videobridge pulls an older, incompatible `jna.jar` _(no arm64 binaries inside)_, from some internet maven repo.

If I also replace `jna.jar` with my local distro provided one the videobridge will load the build native libs fine.

My question, can videobridge at compile time, use the system provided jars _(from `/usr/share/maven-repo/net/java/dev/jna/jna/`)_ instead? Or this is an issue with my setup _(eg. maybe my maven is not setup to look in that folder)_?

**Comment by JonathanLennox** [comment]
I think the correct solution would be to update the jna version referenced from the jitsi-utils pom.

**Comment by licaon-kter** [comment]
Fixed in head
