### ISSUE TITLE
Turning off IPv6 support (2)

### ISSUE THREAD

**Issue by Tulkas59** [jitsi/jitsi-videobridge#1191]
I would like to follow up on Issue #1182.

I already read this doc. My point is that setting `org.ice4j.ipv6.DISABLED=true` does not completely turn off IPv6.

Did I miss something ? Would you prefer I drop this question in ice4j's repository ?

**Comment by Tulkas59** [comment]
Note that I set `org.ice4j.ipv6.DISABLED=true` in `/etc/jitsi/videobridge/sip-communicator.properties`.

**Comment by bgrozev** [comment]
My bad, I didn't see you already set the ice4j property. Let's continue the discussion on the community forum.
