### ISSUE TITLE
Use NAT_HARVESTER_PUBLIC_ADDRESS if STUN server is local

### ISSUE THREAD

**Issue by licaon-kter** [jitsi/jitsi-videobridge#1198]
Debian Buster, arm64

```
INFO: [20] org.ice4j.ice.harvest.StunMappingCandidateHarvester.discover: Discovered public address LAN.IP.HERE:55594/udp from STUN server 127.0.0.1:3478/udp using local address LAN.IP.HERE:0/udp
INFO: [18] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Using org.ice4j.ice.harvest.StunMappingCandidateHarvester, face=/LAN.IP.HERE, mask=/LAN.IP.HERE
INFO: [19] org.ice4j.ice.harvest.AbstractUdpListener.<init>: Initialized AbstractUdpListener with address LAN.IP.HERE:10000/udp. Receive buffer size 10485760 (asked for 10485760)
INFO: [19] org.ice4j.ice.harvest.SinglePortUdpHarvester.<init>: Initialized SinglePortUdpHarvester with address LAN.IP.HERE:10000/udp
```

What I see when a mobile users connects: https://gist.github.com/licaon-kter/356a42a21ac30a34d0a944c0d4e7fe26

The problem is that 10.XXX.XXX.XXX is the TelCo internal IP for a mobile device connecting, you can't reach that address, that's not the real IP.

I guess the refactor is at fault _(I can only build 03b2fc4bdb8d19ebcda31756d0435e5910d21d60 because of https://github.com/jitsi/jitsi-videobridge/issues/1189)_, but 9e1f9a06c08f363beafd6012e94d1e659c86a3c6 works ok:
* videobridge acknowledges (in log) my defined external/internal IPs in `sip-configurator.properties`
* the local STUN/TURN server is used to get the real IP of the mobile device
* video/audio works

After the refactor:
* at start I never see (in the log) my external IP picked up from `sip-configurator.properties`
* but I see `Discovered public address LAN.IP.HERE` which is wrong
* the real IP of the mobile device is never found
* video/audio doesn't work

I've defined:
```
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=XX.XX.XX.XX
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=XX.XX.XX.XX
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet.domain.tld:3478
```

**Comment by licaon-kter** [comment]
@saghul about https://github.com/jitsi/jitsi-meet/commit/3121494d4b149108bd94185e2a4b22b8eafdc794#commitcomment-38137847

JVB doesn't fail here, it finds an IP... but it's its local one not public.

We are now forced to use only external STUN/TURN servers?

**Comment by bgrozev** [comment]
> We are now forced to use only external STUN/TURN servers?

How do you expect to discover a public address without reaching to a remove server?

This is expected behavior and not new.

**Comment by licaon-kter** [comment]
Why is this closed? 

Why do I need to discover what I already know?

**Comment by licaon-kter** [comment]
@bgrozev  Looking at my settings again, it **didn't** behave like this before, maybe then it was broken?

The error stems from the fact that I set _(as all the guides said)_
`org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet.domain.tld:3478`
...which **NOW** it is used by the videobridge and confuses it with the local IP.

Solution? Remove that line as the videobridge doesn't need to find its own address, as
```
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=XX.XX.XX.XX
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=XX.XX.XX.XX
```
...is used as before and everything works again.

Thanks

**Comment by bgrozev** [comment]
> The error stems from the fact that I set _(as all the guides said)_
> `org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet.domain.tld:3478`

This is misconfiguration. Using what is effectively `localhost` as a STUN server is not going to help to discover a useful address.

If any guides we maintain suggest this configuration they need to be fixed, please point us to them. If these are guides by other people, consider reporting it to them.

**Comment by licaon-kter** [comment]
I now see this, I must of confused the point of this settings, guides talk about commenting the default one that uses the official STUN server so I thought it meant I needed to replace it with my own.
