### ISSUE TITLE
`apt-get purge jitsi-videobridge` will remove config files required by `jitsi-videobridge2`

### ISSUE THREAD

**Issue by tpo** [jitsi/jitsi-videobridge#1210]
## Description

The `jitsi-videobridge2` Debian package has replaced the `jitsi-videobridge` Debian package. But when doing a `apt-get purge jitsi-videobridge`
`/var/lib/dpkg/info/jitsi-videobridge2.postrm` will remove config files (and other stuff) required and used by `jitsi-videobridge2`.

`apt-get purge jitsi-videobridge` is a kind of booby trap waiting for everybody that had `jitsi-videobridge` installed that will destroy the jitsi meet installation.

---

## Current behavior
```
$ cat /var/lib/dpkg/info/jitsi-videobridge.postrm
[...]
case "$1" in
    purge)
        # Clear the debconf variable
        db_purge
        [...]
        deluser jvb
        [...]
        rm -f /etc/jitsi/videobridge/config
        [...etc...]
```

---

## Expected Behavior
```
$ cat /var/lib/dpkg/info/jitsi-videobridge.postrm
[...]
case "$1" in
    purge)
        # I'm not sure about this one:
        db_purge
        # but the rest should be protected by:
        if dpkg -s jitsi-videobridge2 | grep ^Status | grep not-installed; then
           # go on deleting stuff *only* if jitsi-videobridge2 is not installed
           # all other package states of jitsi-videobridge2 should prevent
           # removal of config files etc.
```     
---

## Possible Solution
purging `jitis-videobridge` should keep (== not delete) config files and data required by `jitis-videobridge2` - see "Expected Behavior" above

---

## Steps to reproduce

`apt-get install jitis-videobridge; apt-get install jitis-videobridge2; apt-get install jitis-videobridge`

Now `jitis-videobridge2`'s config files (f.ex. `/etc/jitsi/videobridge/config`) and data will be gone.

---

# Environment details
```
# cat /var/log/dpkg.log
[...]
purge jitsi-videobridge:amd64 1126-1
installed jitsi-videobridge2:all 2.1-183-gdbddd169-1
[...]
```
---

**Comment by damencho** [comment]
We no longer support jitsi-videobridge package, it is not being build and so no fixes can go in it. We support upgrading from jvb to jvb2 which should work fine. So there is nothing we can do here.
