### ISSUE TITLE
Is the Jitsi livestream infrastructure as separate open source project?

### ISSUE THREAD

**Issue by xplatsolutions** [jitsi/jitsi-videobridge#1212]
I am looking to incorporate the live streaming infrastructure only similar to what Muvi is offering, https://www.muvi.com/live-server/.

HLS and RTMP Feed
Stream using Cameras (Mobile or Laptop)
Stream multiple channels at once
Embed Live Streaming

I see the out-of-the-box conference app, I want these features only as an infrastructure server, not the software product.

It looks like VideoBridge is the live infrastructure only but still trying to wrap my head around if this offers the input source, encoding, transcoding, HLS output.

The goal is to use the infrastructure and build our product on top of it which we will need to support millions of streams hosted by users and other users joining the host (see meeting platforms e.g. Zoom)

**Comment by bgrozev** [comment]
See [jibri](https://github.com/jitsi/jibri)

**Comment by xplatsolutions** [comment]
I see this is to stream the actual video communication or record. I started getting my head around it. Thanks.
