### ISSUE TITLE
Can I build a limited features Jitsi Meet using VideoBridge?

### ISSUE THREAD

**Issue by xplatsolutions** [jitsi/jitsi-videobridge#1216]
Team, thank you for all your work and contribution regarding this.
I assume using VideoBridge is the server powering the Jitsi Meet front end application, is it correct to assume using VideoBridge I can accomplish the below.

- Create a channel and start streaming your camera.
- Participants join
- Mute audio (kind of optional)
- Off video (kind of optional)
- End call for everyone
- Recording (I know this is part of Jibri)

Is there documentation where I can explore the interface API to interact with the server?

**Comment by bgrozev** [comment]
> I assume using VideoBridge is the server powering the Jitsi Meet front end application
Correct. It is one of the server components.

You can accomplish what you describe, but it will be a lot of work. Jitsi-videobridge is just a video router. You are probably better off re-using something at a higher level, perhaps modyfing the Jitsi Meet client.

**Comment by xplatsolutions** [comment]
I tried to look at the iOS and Android SDKs but only the binaries are available. I will check the Jitsi Meet client but my target platform is mobile-first and then Reactjs.
@bgrozev

**Comment by bgrozev** [comment]
The code for the android and ios apps is all available in the jitsi-meet repository.
