### ISSUE TITLE
Cosmetic: some log messages "a FIR" and other "an FIR"

### ISSUE THREAD

**Issue by bluikko** [jitsi/jitsi-videobridge#1217]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Some log messages use correct article "an" and others the incorrect "a":
```
{"log":"JVB 2020-04-01 09:15:26.832 INFO: [293130] org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender.log() Sending a FIR to ssrc=564129091 remainingRetries=4\n","stream":"stderr","time":"2020-04-01T02:15:26.833039973Z"}
{"log":"JVB 2020-04-01 09:15:26.832 WARNING: [293130] org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender.log() Not sending an FIR because the stream RTP manager is null.\n","stream":"stderr","time":"2020-04-01T02:15:26.833097344Z"}
```

It is really just a small cosmetic issue that I encountered while filtering logs (could not filter correctly with just `ending an FIR`).

I guess I could look for how to make a PR if needed.

## Current behavior
`Sending a FIR` on one log message and `Not sending an FIR` on other message.

## Expected Behavior
Both log messages should use `an FIR`.

## Possible Solution
Change the `a FIR` to `an FIR`.

## Steps to reproduce
Look at the log.

# Environment details
docker-jitsi-meet latest.

**Comment by bbaldino** [comment]
These logs look like they're coming from JVB v1, which we no longer maintain.

**Comment by bluikko** [comment]
I see, I'm on 4101 still and 4384 and 4416 are out.

**Comment by bbaldino** [comment]
Np, let us know if you find anything in the new logs :)

**Comment by bluikko** [comment]
The container creates relatively large amount of logs so I was checking if there's anything of use before setting them to be automatically purged. Nothing of interest really - I guess have to redo this for jvb v2 if the newer docker-jitsi-meet have it. Thanks.
