### ISSUE TITLE
Restricted Network (with Proxy) - ICE failed, add a STUN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by Gurkenmus** [jitsi/jitsi-videobridge#1218]
Turn Server already set up. Issue still exists, user behind Proxy and only allows TCP doesnt get or send video and audio:

See my thread for this:
https://community.jitsi.org/t/restricted-network-with-proxy-ice-failed-add-a-stun-server-and-see-about-webrtc-for-more-details/36017

**Comment by arpsyapathy** [comment]
@Gurkenmus Hi! You resolve your problem? I have same too
