### ISSUE TITLE
Restricted Network (with Proxy) - ICE failed, add a STUN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by Gurkenmus** [jitsi/jitsi-videobridge#1220]
Turn Server already set up. Issue still exists, user behind Proxy and only allows TCP doesnt get or send video and audio:

See my thread for this:
https://community.jitsi.org/t/restricted-network-with-proxy-ice-failed-add-a-stun-server-and-see-about-webrtc-for-more-details/36017

**Pls dont close an issue without answer.**

**Comment by Gurkenmus** [comment]
Finally i got a working Turn Server.

Over google chrome i can connect to meeting now.

with mozilla firefox its still not able to connect.

Some companies (like ours) are not allowed to use google chrome, pls fix the bugs with firefox...

here is the issue:
![image](https://user-images.githubusercontent.com/64144734/80121813-09d41b80-858d-11ea-9cea-630787c62bca.png)

**Comment by bgrozev** [comment]
This is likely not a jitsi-videobridge issue. Please discuss it on the community forum,  and only open github issues in the appropriate project if a specific issue is confirmed.
