### ISSUE TITLE
Integration in mobile app ?

### ISSUE THREAD

**Issue by flashultra** [jitsi/jitsi-videobridge#1225]
Hi,
 I have a mobile game ( Android and iOS) and I'm looking for video chat integration within in . 
 Is it possible to integrate Jitsi in mobile and web in my  game  as external SDK ? 
 Similiar to Agora video chat sdk ( https://assetstore.unity.com/packages/tools/video/agora-video-chat-sdk-for-unity-134502#releases )

**Comment by aviadavi** [comment]
why not?

**Comment by bgrozev** [comment]
See here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile
