### ISSUE TITLE
DISABLE_TCP_HARVESTER default value changed

### ISSUE THREAD

**Issue by superboum** [jitsi/jitsi-videobridge#1227]
## Description
---

TCP harvester stopped working after upgrading Jitsi.
It is caused by `DISABLE_TCP_HARVESTER` default value change. 

## Current behavior
---

TCP harvester does not listen by default anymore (after the upgrade).
DISABLE_TCP_HARVESTER default value is `true` with build `4468`

## Expected Behavior
---

TCP Harvester should continue to listen, as before.
Default value should be `false` as before and accordingly [to the doc](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md#orgjitsivideobridgedisable_tcp_harvester)

## Possible Solution
---

Set back default value of `DISABLE_TCP_HARVESTER` to false.
The bug has probably been introduced by the negation removal in the new configuration [CONFIG.md](https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md).

## Steps to reproduce
---

  1. Download [jitsi-videobridge-linux-x86-1132.zip](https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x86-1132.zip)
  2. Set this configuration in `~/.sip-communicator/sip-communicator.properties`:

```
org.jitsi.videobridge.TCP_HARVESTER_PORT=8080
```

  3. Start jitsi
  4. See that videobridge listens on port 8080 and that port 8080 is announced over webrtc
  5. Download [last sources](https://github.com/jitsi/jitsi-videobridge/archive/stable/jitsi-meet_4468.zip)
  6. Compile with `mvn package` and install
  7. Restart jitsi, this time videobridge listens only on UDP...
  8. Set this configuration in `~/.sip-communicator/sip-communicator.properties` :
```
org.jitsi.videobridge.TCP_HARVESTER_PORT=8080
org.jitsi.videobridge.DISABLE_TCP_HARVESTER=false
```
  9. Restart jitsi, this time jitsi listens again on port 8080, as expected

# Environment details
---

N/A

**Comment by bgrozev** [comment]
Thanks for the detailed report! We intentionally switched the default value, because using TCP directly is no longer reccommended and because the debian packages which the vast majority of people use now include TURN.
