### ISSUE TITLE
Undocumented or untransitioned (nat) options for application.conf

### ISSUE THREAD

**Issue by tiiiecherle** [jitsi/jitsi-videobridge#1229]
Hey,

first of all thanks for the jitsi and jitsi-meet projects and its components.

After a few installation and configuration problems on archlinux (all packages build from source and configured manually) I got the latest stable versions of jitsi-meet, jicofo and jvb2 as muc to work ;)

Now I'm trying to switch to the new configuration scheme and use an application.conf file. Unfortunately I could not find the following options in the [config documentation](https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md).

```
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=$INT_IP_ONLINE
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=$CURRENTPUBLICIP
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$INT_IP_ONLINE
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$CURRENTPUBLICIP
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
```

I tried to use local-address and public-address in the udp section with no success.

My current version of the application.conf file looks like this:

```
# https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md
# https://github.com/jitsi/jitsi-videobridge/blob/master/doc/muc.md

videobridge {
	stats {
		# Enable broadcasting stats/presence in a MUC
	  	enabled = true
	  	transports = [
	    	{ type = "muc" }
	  	]
	}
	
	apis {
		xmpp-client {
	    	   configs {
	      		# Connect to the first XMPP server
	      		shard {
		        	hostname= "localhost"
		        	domain = "$JITSIFQDN"
		        	username = "jvb"
		        	password = "$JVB_USER_PASSWORD"
		        	muc_jids = "JvbBrewery@internal.$JITSIFQDN"
		        	# The muc_nickname must be unique across all jitsi-videobridge instances
		        	muc_nickname = "jvb2"
		        	disable_certificate_verification = true
	      		}
	    	   }
	  	}
	}
	
	ice {
		tcp {
			enabled = true
			port = "4443"
			mapped-port = "4443"
		}
		udp {
			port = "10000"
			local-address = $INT_IP_ONLINE
			public-address = $CURRENTPUBLICIP
		}
	}
}

```

If the options are already ported please give me the correct names and sections and add them to the documentation. If not it would be nice to see them ported asap to make it possible to use the new config file behind nat.

Additionally it would be nice to have a short feedback if the rest of the file looks plausible.

Is it somehow relevant to use quotes around values that do not contain spaces (ports, ip addresses, host, domain, username)?

Thanks in advance and keep up the great work.

**Comment by bbaldino** [comment]
Hey @tiiiecherle, first of all, thanks for trying out migrating to the new config!  So the reason you didn't find those values in the config is that they're actually ice4j config values, and ice4j still uses the legacy config scheme.  I'm sorry that we weren't able to make that experience more consistent, but had we been forced to migrate all components to the new config I don't think we ever would have been able to tackle it :/ It is something I hope we're able to accomplish in the future, though.  (Btw, I think the `org.jitsi.videobridge` prefixed versions of those keys are deprecated, but I think we have some code that is translating them to the ice4j versions if they are set).  `reference.conf` should list all supported config values, as far as I know.

At a quick glance the config looks fine.

As far as quoting values, I'd refer to the [HOCON spec](https://github.com/lightbend/config/blob/master/HOCON.md), which is the format the file uses.

**Comment by tiiiecherle** [comment]
Hey @bbaldino,

thanks for the fast response. It would be good for me and other users that possibly try this to add something about the status (and the missing parameters) to the [documentation](https://github.com/jitsi/jitsi-videobridge/blob/master/CONFIG.md).

It would be nice if this issue could be updated when the respective config options are available in the new config scheme.

Thanks a lot.

**Comment by bgrozev** [comment]
> Btw, I think the `org.jitsi.videobridge` prefixed versions of those keys are deprecated, but I think we have some code that is translating them to the ice4j versions if they are set

We [removed all support](https://github.com/jitsi/jitsi-videobridge/pull/1030/commits/7e232f851f1384a98d738474f6bc4c26676ec8ce) for the `org.jitsi.videobridge` properties being passed to `ice4j`

**Comment by tiiiecherle** [comment]
O.k., thanks, I removed 

```
org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=$INT_IP_ONLINE
org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=$CURRENTPUBLICIP
```
from my config.

**Comment by SchoolGuy** [comment]
Is this issue still up to date or are all options now documented?

**Comment by damencho** [comment]
I think all options are now transitioned. Will close it as too generic and if anything comes with a particular option it deserves a new issue.
