### ISSUE TITLE
Don't expose password in process listing

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [jitsi/jitsi-videobridge#1237]
## Description
The service will use the authentication password as a command line option (`--secret=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Current behavior
The service will use the authentication password as a command line option (`--user_password=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Possible Solution
I haven't touched Java for years, but if I'm recalling correctly the command line arguments  are not immutable in Java (they aren't in C/Go/Rust).

Unlike "classic" UNIX systems the process arguments on Linux are not read only. Changing the relevant argument to some obfuscated value (after processing them) will be reflected in the process output of the operating system.

This can be used to prevent access to the password/shared secrets to anyone running `ps`.

**Comment by obfusk** [comment]
See also jitsi/jicofo#504.

**Comment by obfusk** [comment]
This has been fixed by #1266.
