### ISSUE TITLE
Jigasi media error with latest videobridge builds

### ISSUE THREAD

**Issue by driesken** [jitsi/jitsi-videobridge#124]
I was struggeling the last few days with the following error in jigasi:

jigasi.sh[22134]: 2016-01-21 10:47:41.735 INFO: [109] org.jitsi.jigasi.GatewaySession.handleCallState().628 SIP call format used: rtpmap:0 PCMU/8000
jigasi.sh[22134]: 2016-01-21 10:47:41.735 INFO: [109] org.jitsi.jigasi.GatewaySession.peerStateChanged().692 15263950d86@callcontrol.myserver.xx SIP peer state: Connected
jigasi.sh[22134]: 2016-01-21 10:47:41.736 INFO: [109] service.protocol.media.CallPeerMediaHandler.start().1932 Starting
jigasi.sh[22134]: 2016-01-21 10:47:42.245 SEVERE: [148] net.sf.fmj.media.Log.error()   Unable to handle format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed

It seems that this occurs in the latest builds of videobridge (621, 620, ...). The latest compatible version is build 618. Anyone who has the same problem?

**Comment by damencho** [comment]
What is the error that you face, what is not working? Last time I was using jigasi I have seen this error and the calls were successful. The thing was that for some reason DTLS is not working for jigasi. You need to make sure jvb is not dropping non-dtls packets. There is a property for that: org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.dropUnencryptedPkts=false

**Comment by driesken** [comment]
The error is the one in the post above, jigasi successfully makes the call but no audio is received at all. The property you suggested unfortunately doesn't fix that.

**Comment by damencho** [comment]
You put the property in video bridge and restarted it?

**Comment by driesken** [comment]
Yes, I tried adding it to logging.properties (since there was already a org.jitsi.impl.neomedia entry there) and restarted the videobridge but the problem remains.

I see a lot of these warnings:
jvb.sh[10863]: 2016-01-21 20:28:37.593 WARNING: [86] org.jitsi.impl.neomedia.rtp.translator.OutputDataStreamImpl.warn() Will not translate RTP packet.

**Comment by damencho** [comment]
You need to add it to sip-communicator.properties for videobridge and
restart it.

**Comment by driesken** [comment]
I believe I don't have a sip-communicator.properties in the videobridge directory? I took one of the builds listed at https://download.jitsi.org/jitsi-videobridge/linux/.

I only have such a file for jigasi...

**Comment by damencho** [comment]
Well if you install it from package the the file is in /etc/jitsi/videobridge/sip-communicator.properties. From the archive folder, I think it uses the home to be the folder where it is extracted. So you need to create .sip-communicator folder and place the file there. Information about that should be written in the beginning of the logs or console output. 
For installed from deb package it is:
net.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi
net.java.sip.communicator.SC_HOME_DIR_NAME=videobridge
Which forms /etc/jitsi/videobridge/sip-communicator.properties.
You need to make sure jvb founds your config file.

**Comment by driesken** [comment]
Thanks, found the file. I've added the parameter and did a restart, videobridge enabled it:
jvb.sh[15182]: 2016-01-21 21:04:43.832 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.dropUnencryptedPkts=false

However, the warnings still appear and jigasi doesn't produce any audio. It throws the same errors as in my first post. Is it possible that it tries to use opus (haven't installed it on the server, nor on the SIP server). When I used a previous version like 618, it immediately works again.

**Comment by damencho** [comment]
I don't see any change after 618 that can break it, it must use opus. But there is nothing extra to install. I remembered a problem I faced, I didn't make it working with asterisk and jigasi on one machine, if that is the case try moving asterisk on different machine. I didn't had time to investigate the problem. But this doesn't explain how it is working with 618.

**Comment by driesken** [comment]
Indeed, very weird since the only thing I do is replacing the original videobridge directory (618 build) with the 621 build and restarting the videobridge.

The Asterisk runs on a different server so that shouldn't be the cause of it. For now I'll stick with build 618 and try again in a few weeks. Thanks for the effort though!

**Comment by Kidav** [comment]
Hi, any news here? I have not working jigasi too https://github.com/jitsi/jigasi/issues/26 . But I am not sure if 618 version will work for me.  Can you give me deb or link for your videobridge please?

**Comment by driesken** [comment]
For now I'm still stuck at 618 (haven't tried anything else since). It seems that the older builds are no longer available for download using the link above. You can still grab build 618 over here: http://raspi.degendt.com/jitsi-videobridge-linux-x64-618.zip
(Please send a reply when you've got the file)

**Comment by Kidav** [comment]
Got it. thx! I will check it later

**Comment by Kidav** [comment]
Checked. Unfortunately, there is also problem with new jicofo too. For example: if I use videobridge 618 , jicofo 1.0-68-1, jigasi 1.0-99 then all work as expected; If I use videobridge 618 , jicofo 1.0-211-1, jigasi 1.0-99 then sip calls not work. Too bad that new jitsi-meet is not compatible with old jicofo. So now I have to choose between Firefox support and SIP calls

**Comment by sysreq0** [comment]
I'm experiencing the same issue. No audio on incoming/outgoing calls between Asterisk and Jigasi/Jitsi-Videobridge when using Jitsi-Videobridge version 659. When I revert back to 513, with no configuration changes, it starts working again immediately.

**Comment by hisham1402** [comment]
Hi driesken,

I'm facing same issue, could you please upload videobridge 618 again.
I want to try it maybe it will solve mine.

BR

**Comment by driesken** [comment]
@hisham1402 
I've uploaded the file again.

**Comment by hisham1402** [comment]
Got it, Thanks a lot.

**Comment by hisham1402** [comment]
OK I tired it and the audio start working, unfortunately the video not working.

I got this message:

jvb,log:
2016-03-07 13:40:24.045 WARNING: [286] org.ice4j.stack.Connector.run() Connector died: x.x.x.x:10002/udp -> null
java.net.SocketException: Socket closed

and this error keep repeating 
java.util.prefs.checkLockFile0ErrorCode() Could not lock User prefs.  Unix error code 2.

jigasi.log:
"No ICE media stream for media: video - ignored candidates"

Thanks a lot

**Comment by driesken** [comment]
The error "java.util.prefs.checkLockFile0ErrorCode" appears to be caused by the home dir not being writable. Have you tried running the videobridge as root?

**Comment by hisham1402** [comment]
Hi

Thanks for your kind support, I changed the owner of /usr/share/jitsi-videobridge to jvb:jitsi
Same error, then I started jitsi-videobridge, jicofo and jigasi using root and I got same behavior: Audio OK but no video:
My installation done using quick method on ubuntu 14.04 with openJDK8
Thanks in advance 

jigasi.log:
2016-03-07 15:22:48.872 INFO: [375] service.protocol.media.CallPeerMediaHandler.start().1932 Starting
(Stopped here no other log)

jvb.log:
2016-03-07 15:23:50.618 INFO: [14] org.ice4j.ice.Agent.setState() ICE state changed from Waiting to Terminated
2016-03-07 15:23:50.618 INFO: [184] org.jitsi.videobridge.IceUdpTransportManager.info() Cannot start DTLS, no sockets from ICE.

jicofo.log
Jicofo 2016-03-07 15:24:01.724 SEVERE: [93] org.jitsi.jicofo.JvbDoctor.error() Unexpected error returned by the bridge: jitsi-videobridge.myjitsi, err: <iq id="yXom5-362" to="focus@auth.meetme.swcc.gov.sa/focus6652979841" from="jitsi-videobridge.myjitis" type="error"><error code="501" type="CANCEL"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

**Comment by driesken** [comment]
I haven't tried it on ubuntu 14.04 using the quick install (did a manual install on Centos 7), so I don't have a lot of experience with that.

You could try to do some more verbose logging?
https://github.com/jitsi/jitsi-videobridge/blob/master/lib/logging.properties

Also, you could use Wireshark to analyze the streams for the presence of video.

**Comment by hisham1402** [comment]
Thanks for your help.

I'll do fresh installation and try to start all services using root. also I'll do manual installation.

Thanks again for your valuable info.

**Comment by maxdrash** [comment]
Hi,

I have the same issue with jvb 704.

2016-04-04 16:33:53.163 GRAVE: [902] net.sf.fmj.media.Log.error()   Unable to handle format: LINEAR, 48000.0 Hz, 16-bit, Mono, LittleEndian, Signed
2016-04-04 16:33:53.164 GRAVE: [902] net.sf.fmj.media.Log.error() Failed to prefetch: net.sf.fmj.media.ProcessEngine@136b5a9
2016-04-04 16:33:53.164 GRAVE: [901] net.sf.fmj.media.Log.error() Error: Unable to prefetch net.sf.fmj.media.ProcessEngine@136b5a9


I can't retrieve the last working version in deb format, can you help me ?

Good luck to find a fix :)

**Comment by haovn577** [comment]
Same here jvb704, Ubuntu 14.04, as @maxdrash  wrote.

**Comment by haovn577** [comment]
@hisham1402 : have you passed this issue? any suggestions, thanks.

**Comment by peererror** [comment]
I am also facing the same issue with no audio and video from sip client (linphone) .I am using opensips as  sip server and also tried freeswitch but having the same problem. I have installed jitsi-meet and jigasi on same ubuntu 14.04 machine  with quick installation guide.

**Comment by ibauersachs** [comment]
Video with jigasi isn't supported and never was (or did I miss something there @damencho?).

**Comment by damencho** [comment]
Yes, that is correct. Only audio is available from jigasi deployments.

**Comment by peererror** [comment]
Oh so only audio is supported sorry for misunderstanding on my end.So then I am not hearing any audio from sip client but sip client is able to join the "siptest" room on the server .

**Comment by shock143** [comment]
Hi 
I have same problem No Audio :(

**Comment by damencho** [comment]
I've created an issue to track update and fixing latest jigasi.
https://github.com/jitsi/jigasi/issues/29
If there are comments or suggestions please feel free to step in and write in that issue.

**Comment by Dzaito** [comment]
Why this module can't support video? Can anybody help me ? Thanks.

**Comment by TheReal1604** [comment]
@damencho this is also actual for the current releases. I open another issue with logs tomorrow.
