### ISSUE TITLE
debian postinst gets multiline value for $APIS_VALUE

### ISSUE THREAD

**Issue by narcisgarcia** [jitsi/jitsi-videobridge#1254]
This line (120):
`APIS_VALUE=$(grep -oPe '--apis=\K(\w*,*\w*)' $CONFIG || true)`
needs a next line to avoid installation failure (I've tested with upgrading):
`APIS_VALUE="$(echo $APIS_VALUE | sed -e 's/ //g')"`

**Comment by obfusk** [comment]
I don't see any problems with that code. Could you provide a bit more detail?

**Comment by narcisgarcia** [comment]
I had a dpkg error in a server because of this bug ($APIS_VALUE variable resulted multiline string), and had to fix with this proposed solution to succeed packages upgrade.
Next I did was to publish here the patch.

**Comment by obfusk** [comment]
Could you provide (the relevant portion of) your configuration file?
And have you modified it manually?
It seems to me that there should not normally be a multiline string (there certainly isn't on my server).

**Comment by narcisgarcia** [comment]
```
$ cat /etc/jitsi/videobridge/config

# Jitsi Videobridge settings

# sets the XMPP domain (default: none)
JVB_HOSTNAME=meets.example.net

# sets the hostname of the XMPP server (default: domain if set, localhost otherwise)
JVB_HOST=

# sets the port of the XMPP server (default: 5275)
JVB_PORT=5347

# sets the shared secret used to authenticate to the XMPP server
JVB_SECRET=*****

# extra options to pass to the JVB daemon
#JVB_OPTS="--apis=,"
JVB_OPTS="--apis=rest,xmpp"

VIDEOBRIDGE_MAX_MEMORY=10240m

# adds java system props that are passed to jvb (default are for home and logging config file)
JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/var/log/jitsi -Djava.util.lo$
```
