### ISSUE TITLE
Runing jitsi-meet and video-bridge on same port 443

### ISSUE THREAD

**Issue by ips972** [jitsi/jitsi-videobridge#1263]
Hi Every one, 

would really appreciate any help - really urgent.

I have been running installs and reinstall from every guide i could find. 
I'm new to jitsi and its very important to me to be able to serve jitsi meet web and video on TCP/443
and not the UDP/10000. 
the people i need connecting to the server run behind strict proxy that allow only TCP:80 or 443.
direct UDP/10000 through that or directly is not possible. 
the server is behind NAT (FW holds the real world IP) 

i installed a new ubuntu 19.10 and ran jitsi install guide with apt-get install
First install the Jitsi repository key onto your system:
wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | sudo apt-key add -
Create a sources.list.d file with the repository:
sudo sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"
Update your package list:
sudo apt-get -y update
Install the full suite:
sudo apt-get -y install jitsi-meet

All went fine. default server config runs great. (using my own certs)

>>> Up to here server works fine.

i then used UFW to allow only port 443 and block UDP/10000

also tried  changing the /etc/jitsi/meet/<domain>-config.js settings to disable UDP:

 webrtcIceUdpDisable: true,

I disabled STUN servers and disabled P2P.

I've tried this guide: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/http.md
but this doesn't work or I don't understand what needs to be changed in the sip properties. 

but as soon as second party joins the test meeting both are thrown out with 

if I bring back the installation sip.properties file from apt installation server works again.
(also reenable UDP 10000 in config.js)

I'm a real noob (sorry to say) to this and would really appreciate a fool proof guide.

the errors in JVB.log:
2020-05-17 20:14:04.111 SEVERE: [25] AbstractHealthCheckService.run#174: Health check failed in PT0S:
java.lang.Exception: No XMPP components
        at org.jitsi.videobridge.health.Health.checkXmppConnection(Health.java:124)
        at org.jitsi.videobridge.health.Health.performCheck(Health.java:203)
        at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
2020-05-17 20:14:04.728 SEVERE: [29] ComponentMain.lambda$getConnectCallable$0#293: host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

The errors I see in Jicofo jogs:
Jicofo 2020-05-17 19:54:25.875 WARNING: [69] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-17 19:54:25.875 SEVERE: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-17 19:54:25.875 WARNING: [69] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-17 19:54:25.875 SEVERE: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.

**Comment by ips972** [comment]
anyone?

**Comment by damencho** [comment]
When you have questions or problems use the community forum before opening new issues.

**Comment by damencho** [comment]
First you have a problem that there is no bridge:
`Jicofo 2020-05-17 19:54:25.875 SEVERE: [69] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.`
So default stable install will not use components where is the error from your JVB log.

**Comment by damencho** [comment]
Default stable installation defaults to nginx and installs multiplexing of https traffic serving web or forwarding it to the turn server. 
So without any modifications you should correctly fallback to TCP when udp is not enabled. 
It is not recommended to use TCP from the bridge, and anyway if you want to do that, you need to move it to another machine, to have a different public ip address as it cannot share port 443 with Nginx on the same IP address.

**Comment by damencho** [comment]
I'm not sure whether http proxy will work, but if it works if you use meet.jit.si, then it is possible to achieve it.

**Comment by ips972** [comment]
> Default stable installation defaults to nginx and installs multiplexing of https traffic serving web or forwarding it to the turn server.
> So without any modifications you should correctly fallback to TCP when udp is not enabled.
> It is not recommended to use TCP from the bridge, and anyway if you want to do that, you need to move it to another machine, to have a different public ip address as it cannot share port 443 with Nginx on the same IP address.

can you please point me to a guide on how to install two separate servers 
1. jitsi meet with nginx
2. video bridge (xmpp) 

I can't find a guide and cant figure it out as i'm total noob to this area.

please reopen the issue so people might help with this...

**Comment by damencho** [comment]
This is not an issue, so it does not belong here. 

There is no guide of installing jvb on a second machine. JVB on a second machine will help you configure jvb tcp, but with that you may have other problems ... as it is not the recommended approach.
If you want to go that path, make sure you have one machine running and working correctly, then you can copy /etc/jitsi/videobridge folder to the other machine install jvb, open port 5222 on your xmpp server and change the xmpp server from localhost to the ip-address of that machine in the config file and stop the jvb on the first machine and try using the second one till you succeed.

**Comment by ips972** [comment]
> change the xmpp server from localhost to the ip-address of that machine in the config file and stop the jvb on the first machine and try using the second one till you succeed.


can you please elaborate on these steps.. where do i make the changes you are referencing. 
I'll build a lab with first full working server.. 

then copy the directory you said to second server. 
how do i run the service on the second server and register it to load on next reboot as service? 

the port 5222 will be ok since no UFW and same network segment. 

then with config file and settings do i change? where exactly?

**Comment by damencho** [comment]
/etc/jitsi/videobridge/sip-communicator.properties

org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
should be changed to the correct ip of the xmpp server.
