### ISSUE TITLE
jitsi-videobridge, performs IP Address lookups, transparency request.

### ISSUE THREAD

**Issue by linuxmagic-mp** [jitsi/jitsi-videobridge#1269]
**Is your feature request related to a problem you are facing?**
Please describe the problem you are trying to solve.

Security Auditing, noticed system making a callout to Amazon.. This sets off alarm bells, if it isnt' transparent. 

**Describe the solution you'd like**
Please describe the desired behavior.

 The package preinst should ASK if they would like to Automatically discover the external IP Address or specifiy the IP Address, and NOT do a STUN request without permission.  AS well, especially since it goes to Amazon EC2, it is more suspect that the EC2 instance does not have a PTR record, reflecting it's purpose.. Suggest that 8x8 get a PTR record on that STUN server, so sysadmin's don't panic, and have to trace down this 'phone home'.

host 52.60.135.22
22.135.60.52.in-addr.arpa domain name pointer ec2-52-60-135-22.ca-central-1.compute.amazonaws.com

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by damencho** [comment]
You can just disable the stun mapping harvester and add statically your private and public address and no lookup will be done.

**Comment by damencho** [comment]
We had added automatic discovery of ip addresses as we were getting hundreds issues a day saying 'but when the third joins there is no media'.

**Comment by damencho** [comment]
> org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true

That is another different method that can be used only on aws instances.

**Comment by linuxmagic-mp** [comment]
Again, respectively suggest, that IF you are adding automatic discovery of IP Addresses, you give the user a choice whether they want Automatic (This connects to our STUN server) or Manual.  Also, you didn't comment on the fact that the Amazon IP Address does not have a PTR that reflects Jitsi or 8x8, eg.. naming it 'stun.discover.jitsi.org' or something like that..
And I might add, when you say 'disable stun mapping harvestor', given that you say that isn't DISABLE_AWS_HARVESTOR, and several google queries later.. could you link to what documentation shows how to disable the stun mapping harvestor? Or an example?

**Comment by damencho** [comment]
Just remove it from the config.

**Comment by linuxmagic-mp** [comment]
You aren't very elequent with your responses.. remove 'what', as you previously said ..

**Comment by linuxmagic-mp** [comment]
"That is another different method that can be used only on aws instances."

**Comment by damencho** [comment]
Those configurations are described here:
https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestdisable_aws_harvester
https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharveststun_mapping_harvester_addresses
And are set in /etc/jitsi/videobridge/sip-communicator.properties

You can use this https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address
and this 
https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_public_address
As described in the quick install guide. 



> You aren't very elequent with your responses.. remove 'what', as you previously said ..

Excuse me, but I'm trying to read hundreds of posts in my free time and try to help as much as I can, sometimes from my phone and I cannot easily send you the links. I was expecting that you had checked the quick install guide where configuration files are described and checking that you will see from where the query and address used to query come from.

**Comment by linuxmagic-mp** [comment]
Thanks, that is better.. And I get it.. In the software business ourselves.. And the only reason I am posting, is to give back and make this a better product.. If I run into these issues, I know others do as well. And of course, I read the docs, but that isn't clear, as pointed out in the original post.  The assumption would automatically be that there would be something like DISABLE_STUN_DISCOVERY option.. many of the jitsi 'configuration' items are still scattered around, or not clearly documented.. eg.. options for disabling IPv6 hidden in /usr/lib/prosody/core/portmanager.lua documentation, and not in a debian conf file.

So, while you have given me a 'work around', it would be better if some of this was in the conf file, eg disabling stun server discovery, IPv6, and some would be better as a question during install, all which are small design/programming changes, but simplify the life of an admin, and GREATLY reduce those hundreds of posts you have to answer in your spare time ;)

**Comment by damencho** [comment]
> So, while you have given me a 'work around', it would be better if some of this was in the conf file, eg disabling stun server discovery, IPv6, and some would be better as a question during install, all which are small design/programming changes, but simplify the life of an admin, and GREATLY reduce those hundreds of posts you have to answer in your spare time ;)

I disagree, as complicated as it becomes more questions will come. And the goal of the meta package is to provide as simple as possible install, one or two questions and that's it.

**Comment by linuxmagic-mp** [comment]
One last comment, slightly unrelated but also pertaining to the videobridge package.  If a person has ONLY installed prosody, or other XMPP server, and JUST installs the videobridge package, it would be better to warn the user of an issue, rather than the service running, and filling up logs..

**Comment by linuxmagic-mp** [comment]
2020-05-22 13:51:19.995 INFO: [18] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Initialized mapping harvesters (delay=573ms).  stunDiscoveryFailed=false
2020-05-22 13:51:20.971 INFO: [20] [hostname=localhost id=shard] MucClient$1.connected#266: Connected.
2020-05-22 13:51:20.971 INFO: [20] [hostname=localhost id=shard] MucClient.lambda$getConnectAndLoginCallable$7#648: Logging in.
2020-05-22 13:51:21.125 SEVERE: [20] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by damencho** [comment]
Logs is how you communicate with a service and it complains 'not-authorized'.

**Comment by linuxmagic-mp** [comment]
Sorry, keep hitting <shift|control><enter> and posting before I am complete.  It would be better if the problem was a little more self explanatory that 'not-authorized', eg is this a problem because other packages aren't yet installed, or a default user created, or an SSL issue preventing authentication, or SHA-1 deprecated .. well, you get my drift.

**Comment by linuxmagic-mp** [comment]
But I recognize that the logs can't aways show that for security, but the package or start up service can give better information, eg if a common control file has not yet been setup to make the service usable, tell the end user to install the required package, or direct him how to deal with it in a custom way, before allowing the service to start.. make sense?

**Comment by damencho** [comment]
Yeah, make sense. As I said any PRs are welcome.

**Comment by linuxmagic-mp** [comment]
After I finished running through all this package install procedures and catch all the gotcha's, and write up the blog article, hoping to actually get time and contribute some patches to make it all cleaner for those who follow.. This bug report will help to keep all the potential improvements on record,  (another small nitpick from logs, after video bridge package installed, prosody shows 
May 22 13:44:51 portmanager	info	Activated service 'http' on [*]:5280, and I already had to modify /etc/prosody/prosody.cfg.lua for, c2s_interfaces,s2s_interfaces,component_interface, to prevent IPv6 and listening on all devices, what service is 'http'? a better name would have been nice and what control entry would affect that, as a sample in the config.. finally figured out that http_interfaces would handle that .. but since XMPP and bosh both used that port, a heads up in the service name might be helpful) Seems like more than a few people got stumped with that, maybe later packages are supposed to fix that up.. but.. anyways, turned off https for 5281, and now to the last of the related issues with the videobridge package, it fails to authenticate, but that is probably because the jifoco package is not installed, and that is responsible for adding the correct user I am guessing.. So, manually ran prosodyctl passwd jvb@auth.my.domain.com, and then of course received a problem with the authentication methods.. 

No supported and enabled SASL Mechanism provided by server. Server announced mechanisms: []. Registered SASL mechanisms with Smack: [SASL Mech: GSSAPI, Prio: 100, SASL Mech: SCRAM-SHA-1-PLUS, Prio: 100, SASL Mech: SCRAM-SHA-1, Prio: 110, SASL Mech: DIGEST-MD5, Prio: 200, SASL Mech: CRAM-MD5, Prio: 300, SASL Mech: PLAIN, Prio: 400, SASL Mech: X-OAUTH2, Prio: 410, SASL Mech: EXTERNAL, Prio: 500, SASL Mech: ANONYMOUS, Prio: 500]. Enabled SASL mechanisms for this connection: null. Blacklisted SASL mechanisms: [SCRAM-SHA-1-PLUS].

Adding consider_websocket_secure = true; to the prosody.cg.lua allowed us to move past that, however then into another error.. 

2020-05-22 16:01:50.669 INFO: [19] Videobridge.createConference#320: create_conf, id=f6e07184c8f8dc24 gid=null logging=false
2020-05-22 16:01:50.690 SEVERE: [19] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.videobridge.sctp.SctpManager
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:868)
	at org.jitsi.videobridge.health.Health.check(Health.java:77)
	at org.jitsi.videobridge.health.Health.performCheck(Health.java:211)
	at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

All these steps and problems could be bypasswed and handled by better packaging and configuration IMHO, noone should have to google for error(s) in the logs when they can be avoided in the first place. 

Which to mean means it tried to start a conference, but couldn't..  which is probably because what is needed to start a conference isn't yet available, probably provided by another package, correct? That would seem like a 'dependency', or the package should have been smart enough to realize it could not start the conference, and advise the admin of the correct course of action.

But that's enough 'playing' for today, better put my real work hat back on .. I wil pickup from here tomorrow.

**Comment by licaon-kter** [comment]
@linuxmagic-mp What OS? Hardware?

**Comment by awlx** [comment]
Why don’t you install via the meta package if you need all services on this machine?

It’s perfectly fine that the videobridge package does not depend on the other packages for installation. As we for example run many videobridges on many servers but only a few remote signaling nodes. So prosody and jicofo are not needed on those servers.

**Comment by linuxmagic-mp** [comment]
For the record, have installed it several times, both with the meta package, and individual packages.  I have been installing it on Debian/ARM and Debian/Intel64.  This isn't about just making it work, it's about auditing the packages, what is required, what isn't.. how does it conform to packaging standards, and is it intuitive.. And even if you install using the Meta packages, it still attempts to perform the 'phone home' described in the original topic. It adds convidence in the maintainers and the software, if/why such a 'phone home' is done, and for some, it may give rise to a privacy concern. But as to your comment, yes.. the videobridge could easily be a standalone package, providing it doesn't rely on components from other packages to operate out of the box..

**Comment by licaon-kter** [comment]
I've asked a specific question, because on ARM you'd need to also compile (then replace in the installed folder) SCTP and SRTP. And your error is about SCTP

**Comment by linuxmagic-mp** [comment]
Sorry, I didn't see the ask.. ;) Yeah, I figured that out.. on Arm I had to recompile the sctp.. Sorry, thought that was on a different ticket I filed.. regarding ARM packaging .. be nice if they didn't package it as ALL, when the sctp for arm not included.  But actually, in this ticket was reporting that even with SCTP disabled, the health checks for it were still called.. But, if the videobridge is standalone, their should be local options in config file for health checks and disabling SCTP.. I was confused earlier on, as it appeared that options from meet were affecting videobridge.

**Comment by linuxmagic-mp** [comment]
Issue is long in the tooth, and may not be relavent any more.
