### ISSUE TITLE
How do i extract audio and video streams from the JVB

### ISSUE THREAD

**Issue by sid17291729** [jitsi/jitsi-videobridge#1272]
I want to extract audio for each client from the JVB. It would be great if someone could help me out.

**Comment by bgrozev** [comment]
The bridge doesn't decode the audio streams. There's currently no nice hooks to access the encoded streams, but you can look at `RtpTransceiver`, `RtpReceiver`, `RtpSender` in jitsi-media-transform.

**Comment by sid17291729** [comment]
Thanks a lot.
