### ISSUE TITLE
jvb log is not rotated

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-videobridge#1276]
`/etc/logrotate.d/jvb` is not provided and `/var/log/jitsi/jvb.log` is not rotated.

```
% cat /etc/apt/sources.list.d/jitsi.list 
deb https://download.jitsi.org stable/

% apt policy jitsi-videobridge2
jitsi-videobridge2:
  Installed: 2.1-197-g38256192-1
```

**Comment by sanvila** [comment]
Note: there is some Java-specific rotating stuff here:

`/etc/jitsi/videobridge/log4j2.xml`

but I believe it does not work by default because of this comment at the end:

```
<!-- 
-Dlog4j.configurationFile=config/log4j2.xml has to be used in VM args
 -->
```

In either case I also prefer logrotate, and would love if logrotate was the default rotating mechanism.

**Comment by 532910** [comment]
Hm, but in fact logrotate config is present in the source, https://github.com/jitsi/jitsi-videobridge/blob/2c9389d68ed90077efa7843ad2f1f38b99be69c2/config/logrotate, on the host: `/etc/logrotate.d/jitsi-videobridge` and it works:
```
# ls -1 /var/log/jitsi/jvb*
/var/log/jitsi/jvb.log
/var/log/jitsi/jvb.log.1
```
