### ISSUE TITLE
Cache local Maven repository in GitHub workflow

### ISSUE THREAD

**Issue by Marcono1234** [jitsi/jitsi-videobridge#1287]
## Description
The [current GitHub workflow](https://github.com/jitsi/jitsi-videobridge/blob/master/.github/workflows/maven.yml) for building with Maven downloads the dependencies every time. It would be good to use the [`cache` action](https://github.com/actions/cache) to cache the dependencies to decrease the build time.

You can see an example for caching the local Maven repository [here](https://github.com/actions/cache/blob/master/examples.md#java---maven). Note that you might additionally might want to set "name: Cache local Maven repository" for this step so it has a descriptive name in log files of the workflows.
And you can read more about caching dependencies [here](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows).

**Comment by bbaldino** [comment]
Thanks. Want to open a PR?

**Comment by Marcono1234** [comment]
Sorry, I don't really want to sign the CLA just for that. But you can copy the [example](https://github.com/actions/cache/blob/master/examples.md#java---maven) to your workflow file before line 23:
https://github.com/jitsi/jitsi-videobridge/blob/8009bd6cbfc44e2e3d830eae07cae091e4bec955/.github/workflows/maven.yml#L23

Additionally you can also add a `name` for the cache step (as shown in https://github.com/actions/cache/pull/341) so it has a more descriptive name in the workflow log, though that is optional of course.
