### ISSUE TITLE
Video can not be established in meeting, ICE seems to be okay

### ISSUE THREAD

**Issue by ralfi** [jitsi/jitsi-videobridge#1314]
## Description
---
Could not set video communication behind NAT with STUN / TURN Servers
## Current behavior
---
Video could not established
## Expected Behavior
---
Video establish in meeting
## Possible Solution
---
SCTP connection or data channel stack problem
## Steps to reproduce
---
Do no know on other configs ...
# Environment details
---
docker-jitsi-meet behind fritz.box; Ports 443,4443,1000/udp connected, local TURN Server,
settings adopted from kuketz-meet

Dear Jitsis all,

after a long time playing around with my local docker-jitsi-meet install everything works fine but  video in meetings do no work with devices across LAN borders. Now i have configured a local TURN Server and it seems to me this works fine, see below at the from jitsi videobridge.

But i dont know what fails here with establish a SCTP socket connection. Are there config mistakes? Complete Logfile as attachment.

from LOG File Videobridge the TURN Communication ...

INFO: Pair succeeded: JITSI_VIDEOBRIDGE_IP:10000/udp/host -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: Adding allowed address: EXTERNAL_SMARTPHONE_IP:20079/udp,
INFO: Pair validated: EXTERNAL_IP:10000/udp/srflx -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: Nominate (first valid): EXTERNAL_IP:10000/udp/srflx -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: verify if nominated pair answer again,
INFO: IsControlling: true USE-CANDIDATE:false.,
INFO: Pair succeeded: EXTERNAL_IP:10000/udp/srflx -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: Pair validated: EXTERNAL_IP:10000/udp/srflx -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: IsControlling: true USE-CANDIDATE:true.,
INFO: Nomination confirmed for pair: EXTERNAL_IP:10000/udp/srflx -> EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP).,
INFO: Selected pair for stream stream-61891deb.RTP: EXTERNAL_IP:10000/udp/srflx -> 
EXTERNAL_SMARTPHONE_IP:20079/udp/prflx (stream-61891deb.RTP),

**INFO: CheckList of stream stream-61891deb is COMPLETED,
INFO: ICE state changed from Running to Completed.,
INFO: ICE state changed old=Running new=Completed,
INFO: ICE connected,**

Seems to me that everything ist fine ...

INFO: Starting DTLS handshake,
INFO: Harvester used for selected pair for stream-61891deb.RTP: srflx,
INFO: Negotiated DTLS version DTLS 1.2,
INFO: DTLS handshake complete,
INFO: Attempting to establish SCTP socket connection,

**Got sctp association state update: 1,
sctp is now up.  was ready? false,
INFO: SCTP connection is ready, creating the Data channel stack,
INFO: Will wait for the remote side to open the data channel.,
SEVERE: Could not find data channel for sid 1,
SEVERE: Could not find data channel for sid 1,
INFO: Received data channel open message,
INFO: Remote side opened a data channel.,
INFO: ICE state changed from Completed to Terminated.,
INFO: ICE state changed old=Completed new=Terminated,
INFO: create_conf, id=672b4c505e3a963a gid=null logging=false,
INFO: Performed a successful health check in PT0.005S. Sticky failure: false,
INFO: create_conf, id=da9b7cf03c63b3a1 gid=null logging=false,
INFO: Performed a successful health check in PT0.005S. Sticky failure: false,
INFO: Expiring.,
INFO: ds_change ds_id=61891deb,
INFO: Tearing down,**

INFO: Tearing down,
INFO: Tearing down,
INFO: Stopping,
INFO: Stopping,
INFO: ICE state changed from Running to Terminated.,
INFO: ICE state changed old=Running new=Terminated,
INFO: Closing.,
INFO: Expired.,'

Here are the related Logfile entries completed ...

[Jitsi-TURN-communication-failed.txt](https://github.com/jitsi/jitsi-videobridge/files/4793493/Jitsi-TURN-communication-failed.txt)

Thanks in advance!

**Comment by ralfi** [comment]
Okay, there is problem to establish or communicate to / or from TURN Server.

**Comment by liangguohao66** [comment]
is it bug or config issue?
