### ISSUE TITLE
Simulcast Setting Documentation

### ISSUE THREAD

**Issue by stongo** [jitsi/jitsi-videobridge#138]
Not having any luck getting simulcast working properly.
What setting should be in sip-communicator.properties to enable rewrite mode?

**Comment by gpolitis** [comment]
Hi @stongo there's no special configuration in the bridge as it gets setup based on COLIBRI signaling. If you correctly configure your client to stream simulcast and you signal that to the bridge, it should enable all the required bits and pieces automatically. The bridge rewrites into the first SSRC of the simulcast group.

**Comment by gpolitis** [comment]
You can find more about the COLIBRI required in the simulcast documentation [here](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/simulcast.md). If you think there's something missing from the documentation please open a specific issue.

**Comment by stongo** [comment]
Is simulcast required now? Is there a way to disable simulcast?

**Comment by gpolitis** [comment]
Simulcast is not required, but it is enabled by default. You can disable if you want to by setting `disableSimulcast: true` in your `config.js`. That's not documented anywhere, that's a mistake on our side.

**Comment by stongo** [comment]
@gpolitis: I'm not running Jitsi Meet in this case.

**Comment by gpolitis** [comment]
Oh, so no, it's not enabled by default. It is enabled if you use appropriate signaling with COLIBRI.

**Comment by stongo** [comment]
I think I was being confused by this https://github.com/jitsi/jitsi-videobridge/blob/4de4792074a6282986c413ac6eec371101d18782/src/main/java/org/jitsi/videobridge/VideoChannel.java#L1024-L1030
"Aborting: simulcast mode is not set, but it is required." was misleading

**Comment by gpolitis** [comment]
I see now, this should probably be a debug log, not a warning. And it should also be less scary :)
