### ISSUE TITLE
Does Jvb support rtp header extension ?

### ISSUE THREAD

**Issue by zhiweny1122** [jitsi/jitsi-videobridge#1394]
It looks like the chrome use rtp header extension in simulcast of openh264 ? 
I didn't find the code of rtp header extension in media-transform and jvb.
It is very helpful if someone can give some comments.

**Comment by bgrozev** [comment]
It supports header extensions in general (see [jitsi-rtp](https://github.com/jitsi/jitsi-rtp) for the implementation), but not a specific one for h264 and simulcast.
