### ISSUE TITLE
jvb and gitlab ce problem

### ISSUE THREAD

**Issue by Tealk** [jitsi/jitsi-videobridge#1404]
Hello,

i have installed jitsi and gitlab ce on a server. I think it is connected to port 8080, but I don't know where in the jvb config I can change this port.

JVB:
`java      20865               jvb  170u  IPv6 72687182      0t0  TCP 127.0.0.1:8080 (LISTEN)`

GitLab:
```
bundle     6109               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6496               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6498               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6500               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6502               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6504               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6506               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6508               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
bundle     6512               git   19u  IPv4 72839198      0t0  TCP 127.0.0.1:8080 (LISTEN)
```

**Comment by leo-lb** [comment]
It's documented here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md

`org.jitsi.videobridge.rest.private.jetty.port` default value is `8080`

**Comment by Tealk** [comment]
Thanks @leo-lb for your answer
in which file does it belong? Because the variables in "/etc/jitsi/videobridge/config" all start with "JVB_" and not with "org.jitsi.videobridge.rest."

**Comment by bbaldino** [comment]
> Thanks @leo-lb for your answer
> in which file does it belong? Because the variables in "/etc/jitsi/videobridge/config" all start with "JVB_" and not with "org.jitsi.videobridge.rest."

That value should go in `/etc/jitsi/videobridge/sip-communicator.properties`.  There is a new setting in the new config file, but I haven't updated the doc yet, so you can put it there for now (it will still work).

**Comment by Tealk** [comment]
Thank you
