### ISSUE TITLE
Colibri Message ReceiverVideoConstraintsChangedEvent is considered unexpected

### ISSUE THREAD

**Issue by jienco** [jitsi/jitsi-videobridge#1458]
## Description

We are trying to make use of the ReceiverVideoConstraintsChangedEvent message, so that our client code (using lib-jitsi-meet) can specify the resolution constraint for each of the remote participants by ID. Currently lib-jitsi-meet does not support sending this message, but we are adding that code with the goal of creating a PR in lib-jitsi-meet, following the ideas of https://github.com/jitsi/lib-jitsi-meet/issues/1175#issuecomment-634765227.

## Current behavior

When we send a message like this one:

```
{
     colibriClass: 'ReceiverVideoConstraintsChangedEvent',
     videoConstraints: [
         { "id": "ccb8ecc5", "idealHeight": 720 },
         { "id": "022d9fa9", "idealHeight": 360 },
         { "id": "b42af35f", "idealHeight": 360 }, 
         { "id": "28ab2220", "idealHeight": 180 }
     ]
}
```
We get this message in the videobridge log:

```
WARNING: Received a message with an unexpected type: ReceiverVideoConstraintsChangedEvent
```

## Expected Behavior

We would like if the message could be honored so that the client defines the quality to receive for each remote endpoint.

## Possible Solution

Possibly this could be solved by adding a new method in `EndpointMessageTransport` class, which would handle this message.

## Steps to reproduce

Using the code of this PR jitsi/lib-jitsi-meet#1324, send the message ReceiverVideoConstraintsChangedEvent as specified in the current behavior sample. This can be done through the new public method JitsiConference.setReceiverVideoConstraints added in the PR.

# Environment details

Self-hosted deployment, using jitsi-videobridge version 2.1-304-g8488f77d-1, custom web application using lib-jitsi-meet with the mentioned PR code.

**Comment by veemex** [comment]
@gpolitis , this is related to your work I think . It seems on the vide-bridge side it is implemented. Is somebody able to guide us in a direction regarding this functionality ? Thanks @all :)

**Comment by bgrozev** [comment]
@veemex We had to interrupt this work, so the code is still incomplete. We'll resume this week and we should have updates soon.

**Comment by veemex** [comment]
> @veemex We had to interrupt this work, so the code is still incomplete. We'll resume this week and we should have updates soon.

Wow ! Great news ! Thank you for your quick response !

**Comment by jienco** [comment]
Thank you very much @bgrozev looking forward to this feature

**Comment by zWaR** [comment]
@bgrozev we are also interested in this, it'd help us too if our client end could pick the quality. Do you have an ETA of implementation?

**Comment by dilbert007** [comment]
OH MAN!!!!

This is a very good feature, I can't wait to get ready!

And thank you very much for your work, guys you are AWESOME, much appreciated.

**Comment by jienco** [comment]
@bgrozev @gpolitis Hi, first of all thanks for your amazing work with Videobridge. I wanted to ask you how is it going with the plans for processing the `ReceiverVideoConstraintsChangedEvent` message.

According to https://github.com/jitsi/lib-jitsi-meet/issues/1175#issuecomment-634765227 this would replace 4 different messages (setting last-n, setting selected endpoints, setting pinned endpoints and setting the max resolution), is that still on the plans?

The reason I ask is not only because of flexible quality management per endpoint (https://github.com/jitsi/lib-jitsi-meet/issues/1175), but also because after upgrading to latest Videeobridge `2.1-376-g9f12bfe2`, we are having problems when using LastN where active speakers replace the ones that are in stage (selected endpoints) in our custom UI, causing stage participants to freeze video. We believe that with the unification of these messages, by having the client determine the endpoints he selects (staged endpoints) they would be pinned and kept within Last N, even if other users that are not on stage become active speakers.

I opened this PR https://github.com/jitsi/jitsi-videobridge/pull/1492 but then I closed it because I see that the involved classes are being refactored.

**Comment by bgrozev** [comment]
We're working on it, but progress is slow due other tasks coming up. The plan is to review and potentially change the message format, which is why I'm resistant to just hooking up the existing message in the bridge.

Consider describing the LastN issue you're running into, it's not something we expect.

**Comment by jienco** [comment]
Thanks very much for the quick reply @bgrozev and for explaining the plans, we really appreciate it.

Regarding the LastN issue, here is the description: We have a custom UI with lib-jitsi-meet. In this UI we have a stage where we can have from 1 to 4 participants, and we also have a collapsible panel to view all participants in low resolution. The stage is shared between all participants, meaning they all see the same endpoints there. When a participant closes the panel and has only stage, we use LastN and selectParticipants for that client to save bandwidth and only get the video feeds that are on stage.

We achieve that by doing these two calls in lib-jitsi-meet:

```
conference.setLastN(numberOfParticipantsOnStage);
conference.selectParticipants(arrayOfStageParticipantIds);
```

This was working well for us. Now after this update (we went from Jitsi Videobridge `2.1-273-g072dd44b` to `2.1-376-g9f12bfe2` the problem we have is as follows: Let's say that we have participants with Endpoint IDs (real example): `49d41a92, 7222785b, b13094d2, 44f76001`. Now `49d41a92` and `7222785b` are sent to the stage. `b13094d2` client is watching only stage so he calls `setLastN` with `2`, and `selectParticipants` with IDs `49d41a92,7222785b` (as shown in these client logs):

```
2020-10-21T20:04:11.264Z [modules/RTC/BridgeChannel.js] <l.sendSelectedEndpointsMessage>:  Sending selected endpoints: 49d41a92,7222785b.
Logger.js:154 2020-10-21T20:04:11.265Z [modules/RTC/BridgeChannel.js] <l.sendSetLastNMessage>:  Sending lastN=2.
```

That works well. But now `44f76001` starts talking, and he becomes dominant speaker:

```
2020-10-21T20:07:37.870Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage [as __zone_symbol__ON_PROPERTYmessage]>:  New dominant speaker: 44f76001.
Logger.js:154 2020-10-21T20:07:37.872Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage [as __zone_symbol__ON_PROPERTYmessage]>:  New forwarded endpoints: 44f76001,49d41a92
```

From that moment on, `b13094d2` sees `7222785b` as frozen. As shown in the logs, the Videobridge has now decided to forward `44f76001` and `49d41a92`, where `44f76001` has replaced `7222785b` in our original participant list. The `7222785b` Participant Connection Status changes from active to inactive for `b13094d2`. This is easy to replicate for us and happens also when there is only one participant on stage. The dominant speaker replaces the forwarded endpoints when using LastN to get an exact amount of videos, even if we have called to select specific endpoints.

We would like to be able to call `pinParticipants` which might solve this problem but lib-jitsi-meet allows to pin only one endpoint and our stage can have multiple ones.

I hope the explanation of the issue makes sense. If there is any way we can help through PRs or testing, if you point us in the right direction we are available to contribute code and test. We would like to contribute to this amazing project if we could be of any help.

**Comment by M0rph3v5** [comment]
@jienco we have the same issue, even participant pinning seems to be overridden with the dominant speaker. This is a serious issue tbh, any way to fix this?

**Comment by jienco** [comment]
Hi @M0rph3v5 It is good to know we are not the only ones experiencing this issue. For now we are just not using `lastN` to limit video feeds (we are just getting all feeds using `channelLastN` with value `-1`) due to this issue... Maybe we have to create a separate issue for this problem.

**Comment by barisinanc** [comment]
We are also having the same problem. We have created a custom application with pagination support. We only want to stream videos that are on the active page in order to save bandwidth. If active page users' microphone is in the muted state, the video stream is not becoming active when the participant id is selected or even pinned.

**Comment by jienco** [comment]
@M0rph3v5 @barisinanc I created a separate issue for the problem we are describing https://github.com/jitsi/jitsi-videobridge/issues/1520

**Comment by jienco** [comment]
@bgrozev Regarding this refactor, with the idea of use the new messaging for signaling receiver video constraints per each endpoint, is there any plans to work on it in the short term future? Just for us to know

**Comment by bgrozev** [comment]
> @bgrozev Regarding this refactor, with the idea of use the new messaging for signaling receiver video constraints per each endpoint, is there any plans to work on it in the short term future? Just for us to know

Yes, I am currently working on it. Progress has been slow because high priority tasks kept coming up, but I hope to have something soon.

**Comment by jienco** [comment]
@bgrozev I heard in the Jitsi Call today that the `BitrateController` refactor PR is close to be merged, thank you so much for the excellent work. Let me know if I can help with the client side of it (lib-jitsi-meet), I had opened a PR with the original message idea https://github.com/jitsi/lib-jitsi-meet/pull/1324. Does the message stay the same or it has changed?

**Comment by bgrozev** [comment]
The `BitrateController` refactor PR is in #1530.

#1541 Adds the new signaling format, this is still up for discussion. Perhaps you can coordinate with @jallamsetty1 about work in the client.

**Comment by jienco** [comment]
Amazing thanks @bgrozev! I see the new message format, `BandwidthAllocationSettings` looks great. The documentation is very clear and useful.

@jallamsetty1 If it is of any help, I am open to work in the `lib-jitsi-meet` part of it, perhaps adjusting the original PR I had done https://github.com/jitsi/lib-jitsi-meet/pull/1324 or starting it from scratch.

**Comment by jallamsetty1** [comment]
> Amazing thanks @bgrozev! I see the new message format, `BandwidthAllocationSettings` looks great. The documentation is very clear and useful.
> 
> @jallamsetty1 If it is of any help, I am open to work in the `lib-jitsi-meet` part of it, perhaps adjusting the original PR I had done [jitsi/lib-jitsi-meet#1324](https://github.com/jitsi/lib-jitsi-meet/pull/1324) or starting it from scratch.

Thanks for offering to help @jienco. Like Boris said, the new signaling format is still under discussion. Once we have decided on the format we can start the client side work.

**Comment by engesin** [comment]
Hi everyone,

We are excitedly waiting for this feature to come out :) 

is there any decision about new signaling format?

Thank you :)

**Comment by bgrozev** [comment]
Hi @engesin,

We merged it [recently](https://github.com/jitsi/jitsi-videobridge/pull/1530). See docs about the format [here](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/allocation.md).

**Comment by engesin** [comment]
hi @bgrozev,

Thank you very much, I love this community 😍
