### ISSUE TITLE
Make statistics endpoint public

### ISSUE THREAD

**Issue by agross** [jitsi/jitsi-videobridge#1474]
# Description

I'm running Jitsi inside docker using the official docker-jitsi-meet repo. After upgrading to the latest version, the JVB statistics endpoint is no longer public, and I cannot get its values from outside the JVB container.

As far as I understand this is due to the statistics being on the "private" REST endpoint now.

---

## Possible Solution

Provide a config item to make the statistics API public (i.e. inside a docker network).

---

The older version of JVB listens on 0.0.0.0. I can use a separate container running Telegraf to read statistics into e.g. InfluxDB.

```sh
$ docker exec jitsi_jvb_1 netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
```

The updated JVB container listens on 127.0.0.1, making it impossible to use e.g. Telegraf to read the statistics values.

```sh
docker exec jitsi_jvb_1 netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -
```

**Comment by agross** [comment]
https://github.com/jitsi/docker-jitsi-meet/issues/758

**Comment by bbaldino** [comment]
Are you looking to be able to configure the bind addresses of the http servers in the bridge?  Or to change _which_ http server the stats endpoint is added on?  If it's the former, I don't think there's anything to do here on the bridge: it's just a question of config for the docker container.  If it's the latter, then that would be work in both places.

**Comment by agross** [comment]
I'm not sure either.

The issue seems rather specific to a docker install where binding to 127.0.0.1 essentially means binding to the container's network. JVB might also run on a host where I think having private APIs accessible from localhost only by default is a good idea.
