### ISSUE TITLE
It advertises local IPv4 address as ICE candidate

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-videobridge#1525]
## Description
---

We are using the docker deployment.
I guess the jvb discovers by itself the local docker IPv4 address.
Then it discovers (thanks to stun) it's real public IPv4 address.

When you check in about:webrtc tab in firefox, you then see all the private IPv4 candidate.

I already opened a similar bug in [ice4j](https://github.com/jitsi/ice4j/issues/220) but was told that jvb is probably a better place to tackle that. 

## Current behavior
---

I guess that because of these local IPv4 candidates it slows a bit down the process for the browser to find the right ICE candidate.

## Expected Behavior
---

No local IPv4 are advertised. So that the browser just tries the "good" candidates.

## Possible Solution
---

A configuration switch to filter out local IPv4.
(I understand that there are some setups where is is desirable to advertise local IPs)

## Steps to reproduce
---

Use the docker setup, try a conference, check about:webrtc tab (in ff), and see the IPv4 candidates.

**Comment by ludovicm67** [comment]
Hi, I'm really interested to this feature. Any update on this when it will be implemented?
Has someone some workarounds to have it working now?
Just for information, I navigated across issues and found one similar one: #677.

**Comment by haofanning** [comment]
Same issue here

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-videobridge/blob/0d62166cecc0856190f261a23b9c661eb6b4861a/jvb/src/main/resources/reference.conf#L296
