### ISSUE TITLE
Clarify WebSocket documentation

### ISSUE THREAD

**Issue by reetp** [jitsi/jitsi-videobridge#1558]
## Description

Trying to set up websockets the "Client configuration" section here is confusing

https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md

It appears I have a working web socket as identified by this:

`wss://my.jitsi.com/colibri-ws/jvbjitsi/19796d4324138337/9dbebbc6?pwd=randonlettersandnumber`

( I also have the standard socket as per this `wss://my.jitsi.com/xmpp-websocket?room=test1` )

But the documentation says:

> To enable Colibri WebSocket in the jitsi-meet client, set the following in config.js:
> openBridgeChannel: 'websocket'

So I go to the config.js and uncomment the line and restart at which point I can no longer access the web page.

Comment the line out and restart and it is back to working again.

**Comment by reetp** [comment]
FYI

jitsi-meet                             2.0.5390-3
jitsi-meet-prosody                     1.0.4628-1
jitsi-meet-tokens                      1.0.4628-1
jitsi-meet-web                         1.0.4628-1
jitsi-meet-web-config                  1.0.4628-1
jitsi-videobridge2                     2.1-416-g2f43d1b4-1
prosody-trunk                          1nightly1322-1~stretch

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Most probably you are missing the `,` at that line which breaks your config.js, and commenting it out fixes it.

**Comment by bgrozev** [comment]
> But the documentation says:
> 
> > To enable Colibri WebSocket in the jitsi-meet client, set the following in config.js:
> > openBridgeChannel: 'websocket'

That's no longer necessary, I'll update the doc. Thanks.

**Comment by reetp** [comment]
> Please, when you have questions or problems use the community forum before opening new issues, thank you.

It was at the least a bug in the docs, which I was pretty sure about. I would not have opened it otherwise. I don't believe in wasting peoples time any more than you do.

> Most probably you are missing the `,` at that line which breaks your config.js, and commenting it out fixes it.

Nope - it is there, as installed. This is from the config file - been like this a long time and I have never touched it until I started trying to enable websockets, as per your documentation.

//openBridgeChannel: true,
//openBridgeChannel: websocket,

Never did anything but uncomment it - as per the documentation - and uncommenting still breaks it. I would say that is a bug as well having tested it repeatedly.

Though I presume that it is no longer required as it is enabled by default?

That all needs clarifying. It would save a lot of wasted time.

Thanks.
