### ISSUE TITLE
Colibri websocket unusable

### ISSUE THREAD

**Issue by badfiles** [jitsi/jitsi-videobridge#1560]
## Description
---
Documentation says that I can use websocket instead of WebRTC https://github.com/jitsi/jitsi-videobridge/blob/25c5f8db14a300b6e1ef83e7c7214f79dbf7b342/doc/web-sockets.md,

however the code has been removed from jitsi-meet https://github.com/jitsi/jitsi-meet/commit/0f2be8c6421f4c6ce5552f54c5c2f3c557eeb637

Is this feature still available?
## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

The config was removed as this is controlled now, not from the clients, but from the backend.

**Comment by badfiles** [comment]
OK, but what you've said makes my report a valid doc bug report.
Please fix the doc.

**Comment by bgrozev** [comment]
Already fixed in #1559
