### ISSUE TITLE
Streams added later not working

### ISSUE THREAD

**Issue by jensengar** [jitsi/jitsi-videobridge#157]
I confess I'm relatively new to webrtc and I don't know how all the really low level internals work. I have 2 participants in a video conference each providing a stream with audio and video. The first participant adds a stream (screenshare) but it is never received by the second participant. I have verify the signaling is working as desired and the new description is being set for participant 2 contains the 2 different video sources, but the PeerConnection only registers a single stream. I don't know how the stream gets added to the PeerConnection, I had always assumed its magic based on the description. This works when I have a true p2p connection without using the bridge so I assume something needs to happen on the jitsi side before it gets "activated"? Here is the description for participant 2:

![image](https://cloud.githubusercontent.com/assets/6035507/13464148/c5ab0f5a-e05d-11e5-854e-ee8bc69c7cdc.png)

**Comment by jensengar** [comment]
Turns out this is a canary bug.

**Comment by Kenny-House** [comment]
@jensengar do you have any more info on the Canary bug you reference?

The SDP you posted looks familiar to the issue I filed yesterday at https://bugs.chromium.org/p/webrtc/issues/detail?id=5616 but I was wasn't sure if this was a bug or some change in the behavior of how Chrome was handling streams and tracks.

**Comment by fippo** [comment]
@Kenny-House filed as https://bugs.chromium.org/p/webrtc/issues/detail?id=5624 by @xdumaine
