### ISSUE TITLE
Incorrect values for bit_rate_upload and bit_rate_download in statistics endpoint

### ISSUE THREAD

**Issue by BlueIce** [jitsi/jitsi-videobridge#1583]
## Description

The statistics endpoint (https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md) produces incorrect values for bit_rate_upload and bit_rate_download.

## Current behavior

If there are no conferences active the values are:
`"bit_rate_upload": 0.5,`
`"bit_rate_download": 0.5,`

## Expected Behavior

`"bit_rate_upload": 0,`
`"bit_rate_download": 0,`

## Possible Solution

I think the culprit is in https://github.com/jitsi/jitsi-videobridge/blob/0e680bd48ffec2a804012e1cb44066d320d50058/src/main/java/org/jitsi/videobridge/stats/VideobridgeStatistics.java#L717-L722

## Steps to reproduce

Query statistics endpoint while no conferences are active

## Environment details
Docker setup, Version [stable-5390-3](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5390-3)

**Comment by bgrozev** [comment]
Thanks for reporting. The values are now `double`, so we don't need to apply integer rounding. Fixed in #1584

**Comment by BlueIce** [comment]
Thanks for the super fast fix. :smiley:
