### ISSUE TITLE
Logger output incomplete - log shows does not show the causing classname

### ISSUE THREAD

**Issue by uvwild** [jitsi/jitsi-videobridge#1587]
I am trying to understand problems with my failed Pairing in JVB. But the log output is incomplete.
I believe the logger has a small code defect regarding printing the correct classname. 

I find this line which sets the classname in the src which looks OK. 
 public AbstractEndpointMessageTransport(@NotNull Logger parentLogger)
   { this.logger = parentLogger.createChildLogger(getClass().getName());   }

However, in the output I only find the loggerImpl classname which nobody is interested in.
`Feb 26, 2021 1:16:11 PM org.jitsi.utils.logging2.LoggerImpl log`
This makes the log almost useless.
Maybe its the missing  `Map<String,String> context`  parameter in the createChildLogger call?

**Version**
This is in the videobridge jar on the docker container _jitsi/jvb:stable-5390-3_
which was the latest stable image when I started. 

```
Manifest-Version: 1.0
Implementation-Title: jitsi-videobridge
Implementation-Version: 2.1-416-g2f43d1b4
Build-Jdk-Spec: 1.8
Created-By: Maven Jar Plugin 3.2.0
```

**Comment by uvwild** [comment]
I just installed a current build and the logging info is still incomplete.

**Comment by damencho** [comment]
Are you using this logging file https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/lib/logging.properties that comes by default with the debian package?

**Comment by bgrozev** [comment]
You are probably using the wrong (old?) log formatter. Can you include a sample of the log, the parameters of the JVM (specifically `-Djava.util.logging.config.file`), and the contents of the logging config file?

**Comment by uvwild** [comment]
Thanks for the feedback.
I am using a helmchart and of course the logging.props where outdated....
no mpre  net.java.sip.communicator.util.ScLogFormatter

**java.util.logging.ConsoleHandler.formatter = org.jitsi.utils.logging2.JitsiLogFormatter**
