### ISSUE TITLE
SysV init script does not export VIDEOBRIDGE_MAX_MEMORY

### ISSUE THREAD

**Issue by flxbt** [jitsi/jitsi-videobridge#1604]
The Debian sysv init script [1] does not export the variable 'VIDEOBRIDGE_MAX_MEMORY', so it can not be defined in the sourced '/etc/jitsi/videobridge/config'. Defining it in '/usr/share/jitsi-videobridge/lib/videobridge.rc' results in it being overwritten on the next update. 

Suggested solution: Add the following line to the beginning of the init script's 'start()' function:

`export VIDEOBRIDGE_MAX_MEMORY`

or as diff:

```
70a71
>     export VIDEOBRIDGE_MAX_MEMORY
```

[1] https://github.com/jitsi/jitsi-videobridge/blob/master/debian/init.d

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues., thank you.

In '/etc/jitsi/videobridge/config' you can add both:
`export VIDEOBRIDGE_MAX_MEMORY=...` and `VIDEOBRIDGE_MAX_MEMORY=...` and one of the works with init.d the other one works with systemd.

**Comment by flxbt** [comment]
Hallo Demian,

thank you for the hint, I should have been aware of this - I assume, that the `export VIDEOBRIDGE_MAX_MEMORY=...` in `/etc/jitsi/videobridge/config` variant also works for systemd based installations.

Nevertheless, not only for of the config's bidirectional exchangeability between different init systems, but also for consistency with the Jicofo configuration, as well as for the sake of simplicity and clearness, I think that it would make sense to have the export of this required variable done by the init script. 

(BTW, thank you for the great work and, as it seems, your never ending patience with the community!)
