### ISSUE TITLE
org.jitsi.videobridge.ENABLE_STATISTICS=false (default) breaks conferencing

### ISSUE THREAD

**Issue by willymilkytron** [jitsi/jitsi-videobridge#1613]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

Conferencing breaks when statistics are disabled (!?)

## Current behavior
---

Conferencing rooms disconnects both parties as soon as the second one joins:

![image](https://user-images.githubusercontent.com/62460473/111868622-4a920b80-897b-11eb-9ef5-ea32c7468502.png)

## Expected Behavior
---

Everything working as usual

## Possible Solution
---

Explicitly enable statistics (i believe the Debian installer does by default)

## Steps to reproduce
---

set `org.jitsi.videobridge.ENABLE_STATISTICS=false` in `/etc/jitsi/videobridge/sip-communicator.properties`.

# Environment details
---
```
root@jitsi:~# dpkg -l | grep jitsi
ii  jitsi-meet                      2.0.5390-3                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody              1.0.4628-1                   all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver           1.0.4628-1                   all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                  1.0.4628-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config           1.0.4628-1                   all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2              2.1-416-g2f43d1b4-1          all          WebRTC compatible Selective Forwarding Unit (SFU)
root@jitsi:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@jitsi:~# 
```

Machine in behind NAT and reverse proxy (nginx)

**Comment by willymilkytron** [comment]
```
==> /var/log/jitsi/jicofo.log <==
Jicofo 2021-03-20 12:29:04.390 INFO: [72] org.jitsi.jicofo.xmpp.IqHandler.log() Logout IQ received: <iq to='focus.jitsi.[my.tld]' from='1ylqz-9oegyyvjzf@jitsi.[my.tld]/5h55WPnx' id='9b98ee7a-6226-4abe-b6a6-dc43129fdbf1:sendIQ' type='set'><conference xmlns='http://jitsi.org/protocol/focus' room='test@conference.jitsi.[my.tld]' machine-uid='ddced4c1e01eca63624494801306641b'><property xmlns='http://jitsi.org/protocol/focus' name='disableRtx' value='false'/></conference></iq>
Jicofo 2021-03-20 12:29:04.390 INFO: [72] org.jitsi.jicofo.xmpp.ConferenceIqHandler.log() Focus request for room: test@conference.jitsi.[my.tld]
Jicofo 2021-03-20 12:29:04.792 INFO: [88] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@20d422d5 member=ChatMember[test@conference.jitsi.[my.tld]/6a6c27d0, jid: null]@1487943837]
Jicofo 2021-03-20 12:29:04.792 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.jitsi.[my.tld]/6a6c27d0 joined.
Jicofo 2021-03-20 12:29:04.793 WARNING: [88] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2021-03-20 12:29:04.793 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2021-03-20 12:29:04.793 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Failed to select a bridge for Participant[test@conference.jitsi.[my.tld]/5b92a50b]@618193716
Jicofo 2021-03-20 12:29:04.794 WARNING: [88] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2021-03-20 12:29:04.794 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2021-03-20 12:29:04.794 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Failed to select a bridge for Participant[test@conference.jitsi.[my.tld]/6a6c27d0]@622571504
Jicofo 2021-03-20 12:29:05.538 INFO: [88] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@20d422d5 member=ChatMember[test@conference.jitsi.[my.tld]/6a6c27d0, jid: null]@1487943837]
Jicofo 2021-03-20 12:29:05.539 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member test@conference.jitsi.[my.tld]/6a6c27d0 is leaving
Jicofo 2021-03-20 12:29:05.541 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Terminating Participant[test@conference.jitsi.[my.tld]/6a6c27d0]@622571504, reason: gone, send st: false
Jicofo 2021-03-20 12:29:05.541 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, test@conference.jitsi.[my.tld]/6a6c27d0

```

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before creating new issues. 

What do the jvb logs show? As it seems the jvb did not join the brewery room according to your jicofo logs.

**Comment by willymilkytron** [comment]
This is a bug report, why would i use the community forum to report a bug when Github provides an issue tracking functionality? Unbelievable!

**Comment by damencho** [comment]
Have you discussed it on the community forum, if that is the case, sorry?
Github issues are confirmed issues as described in the template.

**Comment by willymilkytron** [comment]
>  **Github issues are confirmed issues as described in the template**.

Where does the issues template say that, exactly?

This is how i read (and respond to) `bug-report.md`:

> This Issue tracker is only for reporting bugs and tracking code related issues.

Cool, i found an issue: i'm in the right place!

> Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.

Checked community (and google), no similar issues have been found [1].

> General questions, installation help, and feature requests can also be posted to community.jitsi.org

That's ok, i'm not going to ask for help, features or general questions: i found a bug and i want to report it.

NOTE 1: i kind of lied, there's someone else have the same issue, but either they didn't bother reporting it or they did in fact report it but you immediately close their issue like you did with mine: https://git.oopen.de/install/jitsi/-/blob/84d313c1fb6fe7dd19e8c06f65239bda65c2d1c4/README.install#L298

**Comment by willymilkytron** [comment]
Anyway, closing issues like this is very rude and certainly doesn't help grow and helpful community.

**Comment by damencho** [comment]
Bare with us, maybe we need to further update the templates ... but we get tons of issues which are configuration problems, or just questions that make the issue tracker useless. 

In your case, for example, I tested it and it is a matter of updating docs or if we consider it is a bug, that is a bug in jicofo in my opinion and the bug should be opened there ... so that's why we need to first examine and discuss it on the community forum before opening the report, as it may seem it is in jvb but it is actually a bug in another repo or it may be in some of the dependent libraries. 
And you see, even I said, I consider it is a bug in jicofo, that's why it is a discussion as I'm not sure and want to hear the opinion of other team members.
