### ISSUE TITLE
No requests are sent to TURN server when using Google Chrome

### ISSUE THREAD

**Issue by joushx** [jitsi/jitsi-videobridge#1637]
## Description
We just upgraded Jitsi from Version 5142 to 5765 and found the video connection not working any more when using chrome. We use the option for XEP-0215 where TURN credentials are stored in the prosody config.

## Current behavior
When monitoring the network requests made by the videobridge, we can see UDP requests to the TURN server after joining the conference. Also manual UDP requests can be seen when made from the pod. However, despite the logs that indicate a request beeing sent to check the candidate, no request can be found in the recorded requests. As a result, the ICE fails and no video can be seen in the room

```
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: Starting ICE connectivity establishment
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: start check for 10.36.0.16:443/udp/host -> 95.217.x.x:60262/udp/relay (stream-d277cdc8.RTP) tid 0xD43AD9F378011C0AD4A2DD80
Apr 21, 2021 11:53:23 AM org.ice4j.stack.StunClientTransaction sendRequest FINE: sending STUN  tid 0xD43AD9F378011C0AD4A2DD80 from 10.36.0.16:443/udp to 95.217.x.x:60262/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Update remote candidate for stream-b7a659d1.RTP: 95.217.x.x:51004/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: new Pair added: 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP).
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: Transport description:
<transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='7ctu2oeqn82g471pp842rmpubf' ufrag='9c64p1f3ptiecf'><rtcp-mux/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' setup='passive' hash='sha-256'>94:0E:5F:56:1B:0E:99:43:16:8D:29:DD:BC:E6:DE:7F:0D:47:70:1C:9D:2A:DD:1F:4E:6C:7E:80:8E:77:13:58</fingerprint><web-socket xmlns='http://jitsi.org/protocol/colibri' url='wss://xxx/colibri-ws/jitsitest1/5b899349f0787ae9/b7a659d1?pwd=7ctu2oeqn82g471pp842rmpubf'/><candidate component='1' foundation='1' generation='0' id='5aba16bc3b00190b039e19ad3' network='0' priority='2130706431' protocol='udp' type='host' ip='10.36.0.16' port='443'/><candidate component='1' foundation='2' generation='0' id='7c2fa7183b00190b0ffffffff8f97646c' network='0' priority='1694498815' protocol='udp' type='srflx' ip='95.217.x.x' port='443' rel-addr='10.36.0.16' rel-port='443'/></transport>
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Pair failed: 10.36.0.16:443/udp/host -> 95.217.x.x:60262/udp/relay (stream-d277cdc8.RTP)
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log FINE: start check for 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP) tid 0xE73AD9F37801A50123DA8980
Apr 21, 2021 11:53:23 AM org.ice4j.stack.StunClientTransaction sendRequest FINE: sending STUN  tid 0xE73AD9F37801A50123DA8980 from 10.36.0.16:443/udp to 95.217.x.x:51004/udp
Apr 21, 2021 11:53:23 AM org.jitsi.utils.logging2.LoggerImpl log INFO: Pair failed: 10.36.0.16:443/udp/host -> 95.217.x.x:51004/udp/relay (stream-b7a659d1.RTP)
```

## Expected Behavior
A STUN request should be sent in order to establish a connection via the TURN server

## Possible Solution
Did the behavior change in any way? How can this be depend on the browser? Do we need to change the configuration? Could it be that the request is never sent although the logs?

## Steps to reproduce
1. Open a conference using chrome
2. Join with a second user
3. ICE fails

# Environment details
Kubernetes Cluster with Jitsi Components running in pods

JVB Version: 2.1-478-gc6da57bd-1
CoTurn Version: 4.5.1.3
Chrome Version: 90.0.4430.85

**Comment by bgrozev** [comment]
This is especially strange since the ice4j version hasn't changed between the two versions (both use ice4j 3.0-25-g5a299cd):
https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5142
https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5765

**Comment by joushx** [comment]
Okay, that is really strange. Somehow ice4j must be called differently when using Chrome.

I will close this issue in favor of the issue in the main repository: https://github.com/jitsi/jitsi-meet/issues/9056
