### ISSUE TITLE
ShareScreen with more than 2 participants not working from Android APP but working from PC browsers using self jitsi server.

### ISSUE THREAD

**Issue by abnerh69** [jitsi/jitsi-videobridge#1639]
Assuming is a videobridge issue in my config.

Using latest version (as today) of Jitsi and Android SDK with Flutter/jitsi_meet package works like a charm when switch to ScreenShare only if I try APP with meet.jit.si server url.  

But if I try ScreenShare (from APP) with my own server url, sharing with only other one participant it works but not if participant is iPhone.

If participant is other than iPhone it works until another participant enter on meeting, then it shows  gray or freeze last scene if my camera was on.

If I try ScreenShare from browser PC (Safari/Chrome) it works without problems no matter how many participants.

Again, if I connect to meet.jit.si, Android APP works like a charm.

Already double checked ports?

What am I missing in my server configuration (jitsi / jicofo / prosody / videobridge) ?

Appreciate any help.

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Have you updated to latest stable?

**Comment by Vamsi-Rayapati** [comment]
> Assuming is a videobridge issue in my config.
> 
> Using latest version (as today) of Jitsi and Android SDK with Flutter/jitsi_meet package works like a charm when switch to ScreenShare only if I try APP with meet.jit.si server url.
> 
> But if I try ScreenShare (from APP) with my own server url, sharing with only other one participant it works but not if participant is iPhone.
> 
> If participant is other than iPhone it works until another participant enter on meeting, then it shows gray or freeze last scene if my camera was on.
> 
> If I try ScreenShare from browser PC (Safari/Chrome) it works without problems no matter how many participants.
> 
> Again, if I connect to meet.jit.si, Android APP works like a charm.
> 
> Already double checked ports?
> 
> What am I missing in my server configuration (jitsi / jicofo / prosody / videobridge) ?
> 
> Appreciate any help.

@abnerh69  isit resolved ????
