### ISSUE TITLE
SetSenderConstraints does not work properly since 2.1-488-g80d06a63-1

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-videobridge#1646]
## Description

Hi, using JVB `2.1.488-g80d06a63-1`

Test case is simple. There are 2 endpoints: `A`, `B`. Endpoint `A` moves endpoint `B` to stage, sending:

``` json
{
   "colibriClass":"ReceiverVideoConstraints",
   "onStageEndpoints":["B"],
   "defaultConstraints":{"maxHeight":180},
   "lastN":-1,
   "constraints":{"B":{"maxHeight":720}}}
```

Endpoint `B` receive:

``` json
{
   "colibriClass":"SenderVideoConstraints", 
   "videoConstraints":{"idealHeight":720}
}
```

It's ok. Then Endpoint `A` moves `B` out from the stage:

``` json
{
    "colibriClass":"ReceiverVideoConstraints",
    "lastN":-1,
    "defaultConstraints":{"maxHeight":360},
    "constraints":{},
   "onStageEndpoints":[]
}
```

Bridge stops sending `SenderVideoConstraints` for endpoint `B`. Endpoint `B` does not receive `SenderVideoConstraints` anymore.

`2.1-486-gfaf93379-1` works, but in this case endpoint `B` receive 2 messages (zero and target constraint):

``` json
{"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":0}}
```

``` json
{"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":360}}
```

## Expected Behavior

Bridge should not stop sending `SenderVideoConstraints` messages and endpoint `B` should receive one message, like:

``` json
{"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":360}}
```

**Comment by bukharin** [comment]
BTW, `2.1-487-g5bf40485-1` works same as `2.1-486-gfaf93379-1`. I guess the reason is [this commit](https://github.com/jitsi/jitsi-videobridge/commit/80d06a63d1633ccdc634085338835846b122d494)

**Comment by bgrozev** [comment]
Thanks for the report, I'm trying to trace it. 

To clarify:
1. You expect the bridge to send a single message to B, constraining to 360p.
2. `2.1-487` behaves correctly.
3. `2.1-488` sends two messages, first constraining to 0, then to 360.

I'm having trouble reproducing, but I can't get the same messages from the client. Do you use something other than Jitsi Meet?

**Comment by bukharin** [comment]
@bgrozev we have own application that uses `lib-jitsi-meet` and new receiver constraints api

`2.1-487` and `2.1-488` does not behaves correctly. `2.1-487` sends expected messages but also send `0` constraint. `2.1-488` don't send constraint messages anymore after first message with `720` constraint

Two screenshots to illustrate the problem:

`2.1-487` for endpoint `B`:

![image](https://user-images.githubusercontent.com/3126568/117095375-a8d64a80-ad7f-11eb-80a2-a431dcb4e5bb.png)

`2.1-488` for endpoint `B`:

![image](https://user-images.githubusercontent.com/3126568/117095582-28641980-ad80-11eb-9bf4-6db091a77d44.png)

**Comment by bgrozev** [comment]
Thanks for the clarification. I think #1647 fixes the problem with the missing constraints.

I am not sure about the problem with the extra constraints being sent, as it might depend on what the client signals. With the jitsi-meet client, I observe a problem with the constarints being set high instead of 0.

BTW, I notice your client sends the old style `SelectedEndpointsChangedEvent`. This should be deprecated in favor of `ReceiverVideoConstraints`. Mixing the two might lead to unexpected behavior (I don't know if it's related to the issues you see). I am also not sure if this is something to be fixed in your client or in lib-jitsi-meet.

**Comment by bukharin** [comment]
@bgrozev Thank you! I confirm that `2.1-490` fixes this issue.

`lib-jitsi-meet` send `SelectedEndpointsChangedEvent` message as default if no constraints provided during conference connection. Our app waits `BridgeChannelOpened` event to send new receiver constraints. Will fix it.
