### ISSUE TITLE
Button "update" too small

### ISSUE THREAD

**Issue by petmue** [jitsi/jitsi-videobridge#167]
Hi! Opening the settings page on https://meet.jit.si/channel I found that the button appears too small for the text:

![jitsi_videobridge_button_too_small](https://cloud.githubusercontent.com/assets/16270886/13757312/2ae4f0aa-ea24-11e5-81fa-2d6efb276fc5.png)

Changing its CSS to 
` width: auto;
  display: block;
  margin: 10px auto;
`
would fix it. However, I don't where I can find the css file in your project folder in case you are interested in a PR.

**Comment by damencho** [comment]
There is already a PR that we will be merging soon, that removes this button.
