### ISSUE TITLE
🚀 QUESTION - SFU integration 🚀

### ISSUE THREAD

**Issue by miroslavpejic85** [jitsi/jitsi-videobridge#1672]
First `thank you very much` for this `open source project`. 
I'm looking for `SFU solutions` to integrate into my current project [mirotalk](https://github.com/miroslavpejic85/mirotalk)
More details on why [here](https://github.com/miroslavpejic85/mirotalk/issues/35) do you think that `jitsi-videobridge` could be `compatible`? 
I'm collecting some information around concerning the `SFU` servers, to get to the goal. 🏆
Any `feedback - contributions` would be highly `appreciated`! ❤️
`Thanks` guys again and `keep it up`! 💪

**Comment by damencho** [comment]
Please if you have questions or problems use the community forum before opening new issues, thank you.
JVB is an [SFU](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/sfu.md) and you can use it, you can control it using xmpp and the [colibri protocol ](https://xmpp.org/extensions/xep-0340.html)or using [rest API ](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-colibri.md).
More docs you can find at https://github.com/jitsi/jitsi-videobridge/tree/master/doc

**Comment by miroslavpejic85** [comment]
Hi @damencho sorry! 
Thank you so much for the fast reply! 😇
