### ISSUE TITLE
Please remove .DS_Store file from the source

### ISSUE THREAD

**Issue by nirgal** [jitsi/jitsi-videobridge#1693]
Hi

Please remove binary file /jvb/src/main/java/org/jitsi/videobridge/.DS_Store from the sources.
This is a "Apple Desktop Services Store" file, and has nothing to do here.

Note that this file is already ignored by .gitignore, so it might be a bit tricky to remove.

Thanks

**Comment by bgrozev** [comment]
Thanks, fixed in #1694
