### ISSUE TITLE
New statistic tossedPacketsEnergy incompatible with Promtheus metrics naming convention

### ISSUE THREAD

**Issue by D1eter** [jitsi/jitsi-videobridge#1714]
## Description
---
The new statistic "tossedPacketsEnergy" introduced in https://github.com/jitsi/jitsi-videobridge/pull/1677 uses characters incompatible with Prometheus naming conventions. This complicates retrieving and graphing statistics.

## Current behavior
---
Statistics are reported with `"<= ", "<=" ,"> "` as in
`"tossedPacketsEnergy":{"average":null,"max":0,"total_value":0,"total_count":0,"buckets":{"<= 7":0,"<= 15":0,"<= 23":0,"<= 31":0,"<= 39":0,"<= 47":0,"<= 55":0,"<= 63":0,"<= 71":0,"<= 79":0,"<= 87":0,"<= 95":0,"<= 103":0,"<= 111":0,"<= 119":0,"> 119":0,"p99<=":-1,"p999<=":-1}},`
this breaks automatic translation into Prometheus metric names.
## Expected Behavior
---
Continue to report all statistics in a manner compatible with Prometheus naming conventions, as was the case previously
## Possible Solution
---
replacing `"<= "` by `"lt_"`, `"<="` by `"lt"` and `"> "` by `"gt"` avoids the problem
## Steps to reproduce
---
Get https://github.com/shiroyagicorp/prometheus-json-exporter and use that to translate statistics from JSON format to Prometheus metrics like so:

curl -s http://localhost:9116/probe?target=http://localhost:8080/colibri/stats

This used to work nicely but is now broken

# Environment details
---
Can be reproduced on any host with the latest stable JVB version 2.1-538 (or newer, as long as this is not addressed) installed

**Comment by bgrozev** [comment]
Sorry for the slow response. I intend to fix this eventually, but it has low priority right now.

**Comment by D1eter** [comment]
Thanks. Take your time.
