### ISSUE TITLE
[Question] colibriClass: DebugMessage

### ISSUE THREAD

**Issue by TrueBober** [jitsi/jitsi-videobridge#1765]
Good afternoon. I found the following type of message in one client:
{"colibriClass": "DebugMessage", "message": "ssrc = 1111111111111111target = 180p / 30.0 ideal = 180p / 30.0"}
What is this message type and where can I find its description?

**Comment by bgrozev** [comment]
> {"colibriClass": "DebugMessage",

This is not a message type supported by jitsi-videobridge. It was probably used with a custom build.

**Comment by TrueBober** [comment]
OK. thanks for the answer
