### ISSUE TITLE
*jitsi-videobridge2* still includes `/etc/jitsi/videobridge/log4j2.xml` after log4j removal

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-videobridge#1787]
Merge/pull request https://github.com/jitsi/jitsi-videobridge/pull/1786 removed all use of log4j, but the .deb package *jitsi-videobridge2* 2.1-600-gc5a59056-1 still includes `/etc/jitsi/videobridge/log4j2.xml`.

    $ dpkg -S log4j
    jitsi-videobridge2: /etc/jitsi/videobridge/log4j2.xml

**Comment by bgrozev** [comment]
Was this a fresh install of 2.1-600, or an update to it?

**Comment by paulmenzel** [comment]
It was an upgrade:

    2021-12-21 08:11:36 upgrade jitsi-videobridge2:all 2.1-599-gbd22ff3f-1 2.1-600-gc5a59056-1

**Comment by bgrozev** [comment]
We don't explicitly remove it on upgrade.

**Comment by paulmenzel** [comment]
Yes, the log4j jar’s were removed just fine. I thought you are also doing cleanup, as you edit a lot in `/etc` already.
