### ISSUE TITLE
no audio/video  in videobridge

### ISSUE THREAD

**Issue by neerajnagi** [jitsi/jitsi-videobridge#18]
I am having weird issue. Only chat is working among client in videobridge, there  is no audio/video in conference. Only error I see is 

Aug 24, 2014 6:06:26 PM net.java.sip.communicator.util.Logger info
INFO: Ignoring invalid port range [null to null]

in openfire logs

I am running openfire on window 2008 
firewall is turned off. Also there is no udp traffic whatsoever

**Comment by yanas** [comment]
Please reopen if this is still an issue with the current version of Jitsi-Videobridge.
