### ISSUE TITLE
Cannot install jitsi-videobridge2 on ubuntu 22.04

### ISSUE THREAD

**Issue by debendraoli** [jitsi/jitsi-videobridge#1870]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Cannot install jitsi-videobridge due to broken package

## Current behavior
```
The following packages have unmet dependencies:
jitsi-videobridge2 : PreDepends: libssl1.1 but it is not installable
```

## Expected Behavior
Should install correctly.

## Possible Solution
Upgrade libssl

## Steps to reproduce
Install jitsi-videobridge2 on ubuntu 22.04 lts

# Environment details

OS: Ubuntu 22.04

**Comment by damencho** [comment]
https://community.jitsi.org/t/cant-install-on-22-04lts-no-libssl1-1/113871/2?u=damencho
