### ISSUE TITLE
BouncyCastle update to > 1.68

### ISSUE THREAD

**Issue by nils-ohlmeier** [jitsi/jitsi-videobridge#1881]
We attempted an update from BouncyCastle 1.68 to version 1.70, but had to revert back to 1.68 because of a new issue in BouncyCastle >= 1.69, which prevents the media path between the JVB and Jigasi getting established (see #1878 for details).

We created an issue on the BouncyCastle end https://github.com/bcgit/bc-java/issues/1159 to get this resolved.

This ticket is mostly for keeping track of this blocker and update once the issue is fixed on the BouncyCastle side.

Note: a possible alternative is that once Jitsi Desktop is updated to support DTLS 1.2 and is used/available for Jigasi we could probably switch to a recent version of BouncyCastle as well, as the issue above only affects DTLS 1.0 clients.

**Comment by Neustradamus** [comment]
@nils-ohlmeier: It has been fixed by https://github.com/jitsi/jitsi-videobridge/pull/1884?

**Comment by Neustradamus** [comment]
@nils-ohlmeier: What is the status of this ticket?

- https://github.com/jitsi/jitsi-videobridge
- https://github.com/jitsi/jitsi-videobridge/blob/master/pom.xml
- https://github.com/jitsi/jitsi-videobridge/blob/master/jitsi-media-transform/pom.xml
- https://github.com/jitsi/jitsi-videobridge/pull/2036
- https://github.com/jitsi/jitsi-videobridge/pull/1983
- https://github.com/jitsi/jitsi-videobridge/pull/1884
- https://github.com/jitsi/jitsi-videobridge/issues/1881
- https://github.com/jitsi/jitsi-videobridge/pull/806
- https://github.com/jitsi/jitsi-videobridge/pull/123

Linked to:
- https://github.com/jitsi/jitsi/issues/745

**Comment by bgrozev** [comment]
The current version of bouncycastle is 1.75
