### ISSUE TITLE
[feat/bug?] largest_active_conference stat / long living conferences without endpoints

### ISSUE THREAD

**Issue by psi-4ward** [jitsi/jitsi-videobridge#1890]
When using octo, conferences seems like to be alive _long time_ but without any active endpoints:

```bash
# curl -sS http://localhost:8080/colibri/stats | jq .largest_conference
8
```

```bash
# curl -sS http://localhost:8080/debug?full=true | jq '.conferences[] .tentacle.octoEndpoints.ids'
"[754b3d32, d830af6c, 6ce0f6a5, 2f30c58f]"
"[d9ff3ee4]"
"[33e85d30]"
"[185da4ec, dff72eb5, 92461599, c37f4278, eeed3369, 9f4f8c04, aea4e5f4, 8e468f7c]"
```

```bash
# curl -sS http://localhost:8080/debug?full=true | jq '.conferences[] .endpoints'
{}
{}
{}
{}
```

I think most ppl would expect to represent `largest_conference` to be the conference with most participants (without octo endpoints). 
Probably would be a good way to introduce a `largest_active_conference` stat to represent the conference with most participants, excluding octo but having at least one sender. 

I could see the conferences listed in the debug endpoint do not have any real participant for (many) hours - so I do not understand why there are still octo endpoints connected and the conference is _alive_.

It's also a bit misleading that `conferences[i].endpoints` does not include octo endpoints cause the stats docu suggests 
> endpoints - the current number of endpoints, including octo endpoints.

**Comment by bgrozev** [comment]
> When using octo, conferences seems like to be alive _long time_ but without any active endpoints:

This is a known issue with colibri v1. Do you see anything similar with colibri v2 / secure-octo?

**Comment by psi-4ward** [comment]
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/octo.md#secure-octo

huh, missed that. Would take some time to adopt it - thanks for the clarification

**Comment by bgrozev** [comment]
Seems like a colibri v1 problem, re-open if necessary
