### ISSUE TITLE
Save  rtp tracks

### ISSUE THREAD

**Issue by SkyTaurus** [jitsi/jitsi-videobridge#1922]
Is it possible to record rtp packets for audio and video tracks for each participant?

**Comment by bgrozev** [comment]
Yes, you can enable it for a specific endpoint by POSTing to `/debug/features/endpoint/CONFERENCE_ID/ENDPOINT_ID/pcap-dump/enable`. You also need to enable it in jvb.conf by setting `jmt.debug.pcap.enabled=true`.

Please use community.jitsi.org for questions.
