### ISSUE TITLE
Cannot compile jitsi-videobridge on Mageia Linux

### ISSUE THREAD

**Issue by iii0s** [jitsi/jitsi-videobridge#1937]
Hi;

I am interested in packaging Jitsi for Mageia, so I am trying to follow the instructions at https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual.

I cloned the repo at https://github.com/jitsi/jitsi-videobridge and tried to use maven as indicated. By no means I am an expert on maven, but at least I am trying.

The issue that I am having is an error of build failure:
...
The following artifacts could not be resolved: org.jitsi:jitsi-media-transform:jar:2.1-SNAPSHOT, org.jitsi:rtp:jar:2.1-SNAPSHOT: Could not find artifact org.jitsi:jitsi-media-transform:jar:2.1-SNAPSHOT in jitsi-maven-repository-snapshots...

I have noticed that there is actually a jitsi-media-transform folder in the repo.

Could you please point me to the right direction to solve this?

Thank you in advance.

**Comment by bgrozev** [comment]
Hi,

You should be able to get a package by running `mvn install` in the root directory of the repo (you might get the errors you see if you run it inside `jvb`). Look for `jvb/target/jitsi-videobridge-2.1-SNAPSHOT-archive.zip`. If you run into problems, please post the exact command and output.

**Comment by iii0s** [comment]
Hi,

At the end of the videobridge page there is this command:

JVB_HOME="The path to your JVB clone."

mvn compile exec:exec -Dexec.executable=java -Dexec.args="-cp %classpath org.jitsi.videobridge.MainKt -Djava.library.path=$JVB_HOME/lib/native/linux-64 -Djava.util.logging.config.file=$JVB_HOME/lib/logging.properties -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=.jitsi-videobridge "

SO after cloning the repo and trying to follow these instructions I get the error.

Are you suggesting that I only us mvn install instead?

**Comment by bgrozev** [comment]
> Are you suggesting that I only us mvn install instead?

Yes, and make sure you're in the root directory of the repo. I just opened a PR to clarify the instructions in the readme.
