### ISSUE TITLE
Videobridge considers endpoints with muted video when building lastN list

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-videobridge#1962]
## Description

JVB takes endpoints with muted video track when signals clients about LastN changes

## Steps to reproduce

Create conference with `A`, `B` and `C` endpoints with active video tracks. Make `B` as dominant speaker. 

- Endpoint `A` ask only 1 video:

```
{"colibriClass":"ReceiverVideoConstraints","lastN":1,"defaultConstraints":{"maxHeight":180}}
```
JVB answer (correct)

```
{"colibriClass":"LastNEndpointsChangeEvent","lastNEndpoints":["B"]}
```

- **Mute video track** for endpoint `C`. Make `C` as dominant speaker. JVB sends:

```
{"colibriClass":"LastNEndpointsChangeEvent","lastNEndpoints":[]}
```

## Expected Behavior

I expect that JVB will not change LastN list and last event will not sent to client

## Possible Solution

Exclude endpoints with muted video track when forming LastN list.

# Environment details

Version: `2.2.46-gf19f7758`

**Comment by bgrozev** [comment]
I agree with your expectation, but wasn't able to reproduce the problem in a unit test (and I don't think it's easy to simulate with jitsi-meet either). It would be helpful if you can give a way to reproduce with jitsi-meet, or in a unit test. See my attempt here:
https://github.com/bgrozev/jitsi-videobridge/tree/audio-only-test

**Comment by bukharin** [comment]
@bgrozev Ok I will try to reproduce soon. 

I would like to clarify the case: it reproduces only if endpoint `C` joins with video track and mutes them later. If it joins in audio only mode - JVB works as expected

**Comment by bukharin** [comment]
@bgrozev in your attempt you create audio only participany with empty array of `MediaSourceDesc`. 

I guess that in my case `Endpoint` has muted `MediaSourceDesc` in mediaSources list and [getEffectiveContraints](https://github.com/jitsi/jitsi-videobridge/blob/620dfa5dd33a391dd321812efd22f6bd1ba349b0/jvb/src/main/kotlin/org/jitsi/videobridge/cc/allocation/Prioritize.kt#L42) ignores this to determine which sources sould be forwarded

**Comment by bukharin** [comment]
@bgrozev  I found a way to reproduce the problem on meet.jit.si:

1. Open 3 tabs with url: [https://meet.jit.si/blablabla#config.#config.channelLastN=1](https://meet.jit.si/blablabla#config.#config.channelLastN=1). All tabs will ask JVB to receive lastN=1
2. Join on all tabs with active cameras and muted mic
3. Switch to tab 2, unmute mic and say something to set dominant speaker
4. Tab 1 receive from JVB (meet.jit.si uses source signaling and messages are different, but it does not matter)

```
{"colibriClass":"ForwardedSources","forwardedSources":["%tab-B-source-name%"]}
```

Correct.

5. Mute mic on tab 2, switch to tab 3, **mute video** and unmute mic (to set new dominant speaker).
6. Tab 1 receives empty forwarded sources:

```
{"colibriClass":"ForwardedSources","forwardedSources":[]}
```

**Comment by bgrozev** [comment]
> @bgrozev I found a way to reproduce the problem on meet.jit.si:

I can also reproduce on meet.jit.si. After testing a few versions I think I somehow accidentally fixed it in #1963. 🤦 

 Can you check if you see the problem on beta.meet.jit.si? Does the problem still occur in your application with jvb after #1963? Note that your app needs to notify jvb that a source was muted by sending something like this (like jitsi-meet does)
 
 `{"colibriClass":"SourceVideoTypeMessage","sourceName":"1d98d1eb-v0","videoType":"none"}`

**Comment by bukharin** [comment]
@bgrozev I can confirm that problem not reproduces on beta.meet.jit.si and in `2.2-57-g1158321d` version. Thank you!

There is an understanding how long this problem exists? It may be part of [long standing issue](https://community.jitsi.org/t/videostream-stopps-and-goes-to-connection-status-inactive/36981) with inactive status, because JVB not forwarding video participants in priority of participants with muted video.

**Comment by bgrozev** [comment]
It was probably introduced in early 2022 with the multi-stream feature. The bug only triggers when multi-stream is enabled, and it was enabled by default in on June 28 (#1912). I think the thread you linked to has multiple confounding issues (some of them fixed back in 2020/2021), but it's possible some of the more recent reports are related.

**Comment by bukharin** [comment]
@bgrozev  I found similar behaivour in JVB with enabled multistream mode. It occurs when one of videostreams of participant goes to muted state.

One of participants sends 2 streams (desktop + camera).. Remote participant ask 3 lastN

``` json
{
   "colibriClass":"ReceiverVideoConstraints",
   "lastN":3,
   "defaultConstraints":{"maxHeight":180},
   "constraints":
   { 
      "55952e51-v1":{"maxHeight":2160},
      "55952e51-v0":{"maxHeight":180}
   },
   "onStageSources":["55952e51-v1","55952e51-v0"],
   "selectedEndpoints":[]
}
```

JVB asnwers correct and forward 3 last-n video streams

``` json
{
  "colibriClass":"ForwardedSources",
  "forwardedSources":["55952e51-v1","55952e51-v0","ad0f89aa-v0"]
}
```

If I mute `55952e51-v0` source, JVB start sending only 2 last-n streams, but conference has more participants with unmuted videos:

``` json
{
   "colibriClass":"ForwardedSources",
   "forwardedSources":["55952e51-v1","ad0f89aa-v0"]
}
```

**Comment by bgrozev** [comment]
Thanks for the details, I think I have a fix. The code which moves the disabled streams down the list (ConferenceSpeechActivity) works at the endpoint and since your endpoint `hasVideoAvailable` it stays high in the list. We then just concatenate all endpoints' sources which leaves a disabled source high in the list.

Would you be able to test #1989?

**Comment by bukharin** [comment]
@bgrozev this patch fixes the problem  🎉
