### ISSUE TITLE
Bug with Jitsi Videobridge and Jigasi still exists and is not fixed

### ISSUE THREAD

**Issue by holzi1005** [jitsi/jitsi-videobridge#1976]
I have already create an issue about this bug with the new version of the videobridge2 and jigasi.
The previous issue with all logs and configs: https://github.com/jitsi/jitsi-videobridge/issues/1973

The last working release of videobridge together with jigasi is jitsi-videobridge2=2.2-45*
In all later releases, jigasi SIP calllers can not join the conference and will kicked out immediately after joining the conference.

**Comment by bgrozev** [comment]
We use this tracker for issues that require changes to the code. We're succesfully using the latest versions of jitsi-videobridge and jigasi, so it is likely not a general issue, but is somehow related to your environment. Please use https://community.jitsi.org to diagnose the issue (and make sure you use an up-to-date jicofo version as a similar problem was resolved recently, as mentioned in #1973).
