### ISSUE TITLE
AV1 support?

### ISSUE THREAD

**Issue by DanielMcAssey** [jitsi/jitsi-videobridge#1977]
Is there any plans to support AV1 codec, considering the bitrate benefits?

**Comment by alfredonodo** [comment]
I agree, nowadays the AV1 codec is very important, especially for very high resolutions, 2k+. The implementation of AV1 was part of [GSoC 2022](https://github.com/jitsi/gsoc-ideas/tree/master/2022), but I don't know if anyone has implemented it.

**Comment by ProdigyView** [comment]
@DanielMcAssey @alfredonodo  if anyone has time to lend, see here: https://github.com/jitsi/jicofo/pull/994

**Comment by ProdigyView** [comment]
The code above was merged in, which I think means can signal the beginning of AV1 support for the video bridge.

**Comment by bgrozev** [comment]
> The code above was merged in, which I think means can signal the beginning of AV1 support for the video bridge.

This is just a small part that enables the signaling. The bridge still doesn't support it, but there's ongoing work.

**Comment by ProdigyView** [comment]
Just keeping this up-to-date, two new PRs are being worked on:

- https://github.com/jitsi/jitsi-videobridge/pull/1998
- https://github.com/jitsi/jitsi-videobridge/pull/1996

**Comment by alfredonodo** [comment]
Hi,
any news about this?
Thank you

**Comment by JosefWN** [comment]
Is there any umbrella ticket tracking what is left to do to offer support throughout the whole Jitsi stack?

**Comment by danryu** [comment]
> Is there any umbrella ticket tracking what is left to do to offer support throughout the whole Jitsi stack?

From a brief look, it seems that full support is covered by https://github.com/jitsi/jitsi-videobridge/pull/1998 and https://github.com/jitsi/lib-jitsi-meet/pull/2350 (and these are both merged to master now).

If @JonathanLennox / @jallamsetty1 could confirm (?) I would definitely be happy to start some early testing :)

**Comment by jallamsetty1** [comment]
Yes, Av1 is fully supported in master with the exception of the case when a visitor (visitor mode that hasn't been released) joining the call doesn't support Av1.
The testing flag for the client side needs to be set - https://github.com/jitsi/jitsi-meet/blob/master/config.js#L88 in addition to the settings mentioned in this post - https://community.jitsi.org/t/how-to-enable-av1-codec/128518.
Happy testing!

**Comment by alfredonodo** [comment]
Is there any update on the release in the stable version?

**Comment by damencho** [comment]
That was already release in stable. You can enable it be following the steps above

**Comment by alfredonodo** [comment]
That's great. I thought there would be a [blog post](https://jitsi.org/blog/). Also, in theory it should be on by default and clients should negotiate the supported codec.

**Comment by jallamsetty1** [comment]
We will be enabling AV1 by default in the next stable. You will still have to set it as the preferred codec on your deployment. We plan to publish a blog post about it soon.

**Comment by outlaw-dame** [comment]
Do you have an idea how soon?
