### ISSUE TITLE
speechActivityEndpointsChanged can be called on a channel before the lastN value is initialized

### ISSUE THREAD

**Issue by brianh5** [jitsi/jitsi-videobridge#202]
I've run into a problem where speechActivityEndpointsChanged can be called on a channel whose last-n value was set in colibri, but isn't set on the channel before the speechActivityEndpointsChanged is called.  The result of this is that speechActivityEndpointsChanged sees a last-n of -1 so it forwards all streams instead of a limited amount.  I've attached a log where this happens, and pasted the specifically relevant bits below.  (Logs include some extra print statements I added).

> JVB 2016-04-01 17:09:29.254 INFO: [36] org.jitsi.videobridge.Content.info() Created channel 6614529142d6bf37 of content video of conference ced34408e1351448. The total number of conferences is now 1, channels 8, video streams 7.
> JVB 2016-04-01 17:09:29.254 INFO: [45] org.jitsi.videobridge.LastNController.info() BB: speechActivityEndpointsChanged for channel 6614529142d6bf37 got active endpoints [org.jitsi.videobridge.Endpoint 8, org.jitsi.videobridge.Endpoint 7, org.jitsi.videobridge.Endpoint 9]
> JVB 2016-04-01 17:09:29.254 INFO: [36] org.jitsi.videobridge.LastNController.info() BB: videochannel 6614529142d6bf37 Setting lastN=1
> JVB 2016-04-01 17:09:29.254 INFO: [45] org.jitsi.videobridge.LastNController.info() BB: update for channel 6614529142d6bf37 got new conference endpoints [8, 7, 9], last n is -1
> JVB 2016-04-01 17:09:29.255 INFO: [45] org.jitsi.videobridge.LastNController.info() BB: channel 6614529142d6bf37 last n not set, adding everyone

The 

> JVB 2016-04-01 17:09:29.254 INFO: [36] org.jitsi.videobridge.LastNController.info() BB: videochannel 6614529142d6bf37 Setting lastN=1

print is made before acquiring the lock, not at the actual place it gets set.  But you can see the chain from speechActivityEndpointsChanged gets executed without ever seeing the proper last-n value.

[jvb_channel_6614529142d6bf37_active_speaker_event_before_lastn_initialized.txt](https://github.com/jitsi/jitsi-videobridge/files/200585/jvb_channel_6614529142d6bf37_active_speaker_event_before_lastn_initialized.txt)

This happens because we parse the channel creation and last-n settings of a channel in two different places when parsing the colibri iq message, which is reasonable, but unfortunately it can totally break last-n if there's a chance an active speaker change occurs in that space of time (which I think is reasonably likely, because the new endpoint itself could frequently trigger that, I was able to repro it every time in my testing).

**Comment by bgrozev** [comment]
Hey Brian,

I don't understand this fully. After setLastN(1) and speechActivityEndpointsChanged(7,8,9) finish, regardless of the order they run in, we should have lastN=1 and forwardedEndpoints={7}. We may have sent more than one event over the data channel, but the last one should have lastNEndpoints={7}. Do you see an inconsistent state of LastNController, or a problem with the data channel messages (or both)?

**Comment by brianh5** [comment]
Hey Boris!
Hoping I remember this right.  Yes, the behavior will eventually converge on the right thing, but there's a period there where it could be wrong, i.e. a chance where a client joins a meeting with 5 people, has last-n set to 2, but gets all 5 video streams for a period of time.  I can't remember if perhaps some state got set that made it problematic for last-n to actually converge correctly, or if it was just that it's a bit awkward/waste of bandwidth/slow down call set up and make debugging confusing.

**Comment by bgrozev** [comment]
Now that I think about it, if it is just the race between setLastN and a dominant speaker change, I would expect this to have no real effect, because setLastN would execute early on, during channel creation, before ICE has completed. So it must be something else. If you do run into it again, please let us know.

**Comment by brianh5** [comment]
Hey Boris,
I definitely saw instances of active speaker change events firing before setLastN was being called.  Those are the logs I have in the original post.

**Comment by bgrozev** [comment]
Yeah, sure, but that shouldn't create any problems, because setLastN will still execute before ICE completes (and so before we send a data channel message, and before any video packets are routed).

**Comment by brianh5** [comment]
That may be true, though I'm fairly certain I remember the message actually making it to the client.  Either way, it's a race condition that we're relying on never happening as opposed to implementing it in such a way that there's no race.  Perhaps not the most urgent bug to fix, though.  I'll keep an eye out for it, and how about we leave the bug open?

**Comment by bgrozev** [comment]
This is probably outdated because of all the refactoring. Please reopen if necessary.
