### ISSUE TITLE
Collibri relay ws connection problem

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-videobridge#2065]
## Description

Collibri relay ws not works on latest build

## Current behavior

Collibri ws relay broken. JVB's does not exchanges any collibri messages with an error

```
RelayMessageTransport.webSocketTextReceived#379: Received text from an unknown web socket.
```

May be related to  https://github.com/jitsi/jitsi-videobridge/commit/37da7e13f2afea81128e5bf6da17dd431764a6a0

Does not reproduces on latest stable release

**Comment by bgrozev** [comment]
Thanks for the report @bukharin. I found something suspicious in the code, and fixed it in #2066, but I don't know if it will make a difference. Can you test?

What's strange is that we've been running with https://github.com/jitsi/jitsi-videobridge/commit/37da7e13f2afea81128e5bf6da17dd431764a6a0 on meet-jit-si for a while and haven't seen this problem or any problem connecting relays. Are you using jicofo or something else to control the bridges?

**Comment by bukharin** [comment]
@bgrozev yes, we use jicofo to control the bridge

I see that you merge the brunch, are you able to reproduce the problem? 

I can confirm that `2.3-59-g5c48e421` works fine, thank you!

**Comment by bgrozev** [comment]
Great, thanks for confirming!
