### ISSUE TITLE
SIP in jitsi-meet conference does not have any audio/video 

### ISSUE THREAD

**Issue by Farrukh-Haroon** [jitsi/jitsi-videobridge#208]
I follow the instructions in the quick installation guide, firstly i deployed a jitsi-meet on ubuntu and then the kamailo sip server on the seperate machine and finally the jigasi gateway for sip on the same machine where the jitsi-meet is presence, during jigasi its prompts me the sip account to use for invite the other sip accounts. all things i guess is perfectly deployed. now from the jitsi-meet conference i dialed the sip number registered with the kamailo server get in to the meeting but no media is showing on both sides, what is the problem ? and how can i dial into the conference from the any sip phone .!
Please any jitsi expert help me out .!

**Comment by damencho** [comment]
It is a known issue, check jigasi issues or mailinglist. We will be working on fixing it soon. Any help is welcome.

**Comment by Farrukh-Haroon** [comment]
In future is there any plan to provide a video of sip client in meeting and
then vice versa?

**Comment by Farrukh-Haroon** [comment]
And please tell me that how can I setup and old version of jitsi-meet
/jigasi ? To provide the only audio feature of sip client in a meeting.!

**Comment by damencho** [comment]
You need to setup jigasi, jitsi-meet, jicofo and jvb from source. And
versions need to be maybe from bigining of November last year, not sure
about the versions though there were several reports on the mailinglist and
some of them mention the last working combination of versions.

**Comment by djonrikk0** [comment]
In jigasi status is not yet implemented, how to connect in jisti meet, any can solve my problem?

**Comment by damencho** [comment]
Please use the mailinglist. Jigasi is working, I'm not sure for which status you are talking about.
