### ISSUE TITLE
How to monitor Video Bridge using Prometheus/ Blackbox exporter?

### ISSUE THREAD

**Issue by amit-tewari** [jitsi/jitsi-videobridge#2082]
I need to implement a monitoring solution for Jitsi setup, however monitoring UDP services is proving to be a bit tricky. `nc -zuv HOST PORT` works to an extent but not as clean and maintainable as a probe of a proper monitoring solution.

Looking at [DNS prober in blackbox exporter](https://github.com/prometheus/blackbox_exporter/blob/master/prober/dns.go) it seems best way is to implement a protocol level ping on port 10000. However while searching the internet, I could not figure out what could be that minimal ping/ pong response that could be implemented using go (because then it could become part of blackbox exporter) or some other high level language.

Any clues/ pointer will be appreciated, to any existing solution or how this could be implemented.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Have you checked
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/health-checks.md

**Comment by amit-tewari** [comment]
Hi @damencho ,

Thank you for your reply.
Apologies for not checking the community forum first.

https://community.jitsi.org/t/jvb-udp-based-health-check/93570 was similar question asked, but has unfortunately been unanswered for 3 years. I'll post my query on this question thread, closing this question/ issue.

https://github.com/jitsi/jitsi-videobridge/blob/master/doc/health-checks.md is relevant for checking http port and if JVB is functioning, which is different from the use-case I have (possibly many other people too).

**Comment by bgrozev** [comment]
There's also the standard prometheus interface at `/metrics`. Why do you want to monitor the udp port in particular? It won't respond to your packets unless you make a conference/endpoint allocation first (which is probably too much hassle)
