### ISSUE TITLE
Crashes on Browser (Tabs) when screensharing / "Colibri websocket error: null" shown on JVB when tcp websocket connection is unexpectedly aborted (client)

### ISSUE THREAD

**Issue by amsnek** [jitsi/jitsi-videobridge#2092]
## Description
This is a custom Jitsi Setup, no Docker. Release 2.0.9220. These crashes have been appearing seemingly random for some time. They only occur when screensharing is active, for the person that is sharing.

the jitisi-videobridge log shows the following error on crash: 
`Feb  6 13:29:32 hostname jitsi-videobridge[1556]: 2024-02-06 13:29:32.255 SEVERE: [1885] [confId=347a036a28a27b47 conf_name=meeting@conference.meet.domain.tld meeting_id=3037aa9b epId=9d208350 stats_id=Gudrun-zyn] EndpointMessageTransport.webSocketError#382: Colibri websocket error: null`

These exceptions correlate with Client "disconnects" (the TCP session was unexpectedly aborted by the client) of the colibri websocket on the reverse proxy infront (the session was in the DATA phase). 
Something seems to interrupt the connection -> could this cause the *crash* of the tab when screensharing? If so, should it not attempt to reconnect and "hang" instead for the duration of the reconnect? 

Afterthought: would it be possible to not use websockets and thus increase the resilience (ugly workaround)?

**Comment by damencho** [comment]
Crash like: 
<img width="379" alt="image" src="https://github.com/jitsi/jitsi-videobridge/assets/3263098/0e0fab7d-f5f8-4944-a9fb-e0940eb698ef">?

**Comment by amsnek** [comment]
> Crash like: <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/3263098/302718326-0e0fab7d-f5f8-4944-a9fb-e0940eb698ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzk5MTIsIm5iZiI6MTcwNzIzOTYxMiwicGF0aCI6Ii8zMjYzMDk4LzMwMjcxODMyNi0wZTBmYWI3ZC1mNWY4LTQ5NDQtYTlmYi1lMDk0MGViNjk4ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTcxMzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc1NWU3M2QwNzJlMmUwZDEzOTIxNGJmNGU5ZTRhOGM1OGQwMWI2NTcxYWMwYTBhYzc2ODI1ODdkMWU2ZTg5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ad8nMh4PiQaLl4sR6967hkW3Tv7-Y4FLOYpCUFKCWOQ">?

yes, exactly

**Comment by damencho** [comment]
You should report that to the bug tracker of the browser you are using.

**Comment by amsnek** [comment]
thanks, I was fearing this is something Browser related entirely. It happens with Chrome and Edge (seemingly less common there). 
As a stopgap, is not using websockets still possible? 🙈

**Comment by damencho** [comment]
It is possible, but I do not think that is your problem. If you are able to reproduce, I would start with changing the codec that is used in the meeting. It also may turn out it is a browser issue on a specific operating system.. 

https://github.com/jitsi/jicofo/blob/e20abda9ce7c5097481c1daefa88ca11d98155f3/jicofo-selector/src/main/resources/reference.conf#L346
https://github.com/jitsi/jitsi-videobridge/blob/a015be96887fd907a6c5579f94fb8c15659d81b2/jvb/src/main/resources/reference.conf#L217
https://github.com/jitsi/jitsi-meet/blob/d5ee7f3069c94819494d9cf8958bbf5c33dfff81/config.js#L73

You can enable sctp, which is default on in jicofo and bridge and add to the web config that to be the preferred method. 

And I do not think that is a bridge problem, so I will close it for now. If it is something to be fixed/workaround that is in lib-jitsi-meet.
Please when you have problems or questions use the community forum before opening new issues.
