### ISSUE TITLE
jitsi-video bridge starting error.

### ISSUE THREAD

**Issue by sparashetti820** [jitsi/jitsi-videobridge#2097]
ster (localAddress=xxx.xxx.xxx.xx:0/udp).
JVB 2024-02-15 12:19:16.579 SEVERE: [1] MainKt.main$lambda$0#55: An uncaught exception occurred in thread=Thread[main,5,main]
java.lang.NoSuchMethodError: 'void org.jitsi.utils.stats.BucketStats.<init>(java.util.List, java.lang.String, java.lang.String)'
        at org.jitsi.nlj.stats.DelayStats.<init>(DelayStats.kt:27)
        at org.jitsi.videobridge.xmpp.XmppConnection.<clinit>(XmppConnection.kt:287)
        at org.jitsi.videobridge.MainKt.main(Main.kt:96)
        at org.jitsi.videobridge.MainKt.main(Main.kt)
JVB 2024-02-15 12:19:16.614 INFO: [17] org.ice4j.ice.har

## Description
getting above error in logs and jitsi-videobrigde failed to start.

## Current behavior
how to resolve?

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by sparashetti820** [comment]
version 2 .3-74-ga015be96-1

**Comment by bgrozev** [comment]
How did you install and run it? Looks like the jitsi-utils jar is not loaded

**Comment by sparashetti820** [comment]
apt-get -y install jitsi-videobridge2=2.3-74-ga015be96-1 used this command

**Comment by damencho** [comment]
@sparashetti820 I just tested `dpkg -i ...` on a clean vm with java11 and java17 and I do not see such an error. 
What is the output of `dpkg -l | grep videobridge`?

**Comment by sparashetti820** [comment]
after re-installing luarocks. it works.

**Comment by damencho** [comment]
There is no lua in the bridge, probably something else was the problem
