### ISSUE TITLE
high packet loss reported when audio is silenced

### ISSUE THREAD

**Issue by fippo** [jitsi/jitsi-videobridge#21]
I just noticed that chrome reports a high packet loss when sending audio that is physically muted.

Steps to reproduce:
1) go to meet.jit.si twice, have chrome://webrtc-externals open
2) use a headset or mic that can be physically muted -- @emcho's big mic might work.
3) check the ssrc_12345_send statistics for packetsLost -- should be close to zero
4) mute the mic
5) watch the packetsLost counter increase at almost the same rate as the packetsSent

Not sure what happens exactly. It doesn't happen in chrome when doing p2p.
Maybe the cumulative number of packets lost or the highest sequence number received is not properly updated in the RTCP RR. Or it is and chrome expects something else?

**Comment by yanas** [comment]
All related issues have been fixed and if there's something left feel free to enter a new specific ticket indicating only the remaining problem.
