### ISSUE TITLE
JVB 2.3.105 (9457) can't connect to old jicofo as octo?

### ISSUE THREAD

**Issue by pouriamoosavi** [jitsi/jitsi-videobridge#2130]
# Description
---
We have a setup of multiple Octo JVBs and one jicofo+prosody server (main server). JVB is stopped on main server. <br>
Our JVB servers are all version 2.3.61 and they all work properly. If we add a new server with jvb 2.3.61, it can also introduce itself as Octo fine and if a user joins an old conference it will use the new jvb. <br>
But if we add a new server with jvb 2.3.105, or even update one of old servers (using `apt upgrade`) that specific server won't work properly as octo. It can work as a node but only new conferences will go to this new server and if a user joins an old conference it will go to one of other servers. <br>
In jicofo logs it seems to be no difference between these servers (except jvb version):
```
Jicofo 2024-05-06 10:30:45.556 INFO: [110830] [type=bridge brewery=jvbbrewery] BaseBrewery.addInstance#347: Added brewery instance: jvbbrewery@internal.auth.xxx.com/9c3a222a-1bfd-4c9e-af89-e2ffc2c51b2e
Jicofo 2024-05-06 10:30:45.556 INFO: [110830] BridgeSelector.addJvbAddress#96: Added new videobridge: Bridge[jid=jvbbrewery@internal.auth.xxx.com/9c3a222a-1bfd-4c9e-af89-e2ffc2c51b2e, version=2.3.61-g814bffd6, relayId=xx.xx.xx.28, region=xx.xx.xx.28, stress=0.00]
Jicofo 2024-05-06 10:30:45.557 INFO: [38] JvbDoctor.bridgeAdded#132: Scheduled health-check task for: Bridge[jid=jvbbrewery@internal.auth.xxx.com/9c3a222a-1bfd-4c9e-af89-e2ffc2c51b2e, version=2.3.61-g814bffd6, relayId=xx.xx.xx.28, region=xx.xx.xx.28, stress=0.00]
```
```
Jicofo 2024-05-06 10:29:13.271 INFO: [110860] [type=bridge brewery=jvbbrewery] BaseBrewery.addInstance#347: Added brewery instance: jvbbrewery@internal.auth.xxx.com/d678f8a6-51e6-4b49-bdae-0009361cff9e
Jicofo 2024-05-06 10:29:13.271 INFO: [110860] BridgeSelector.addJvbAddress#96: Added new videobridge: Bridge[jid=jvbbrewery@internal.auth.xxx.com/d678f8a6-51e6-4b49-bdae-0009361cff9e, version=2.3.105-ge155b81e, relayId=xx.xx.xx.247, region=xx.xx.xx.247, stress=0.00]
Jicofo 2024-05-06 10:29:13.271 INFO: [38] JvbDoctor.bridgeAdded#132: Scheduled health-check task for: Bridge[jid=jvbbrewery@internal.auth.xxx.com/d678f8a6-51e6-4b49-bdae-0009361cff9e, version=2.3.105-ge155b81e, relayId=xx.xx.xx.247, region=xx.xx.xx.247, stress=0.00]
```

## Current behavior
---
jvb 2.3.105 can't work as octo with old jicofo, but 2.3.61 can.
## Expected Behavior
---
jvb 2.3.105 works like 2.3.61.
## Possible Solution
---
No idea!
## Steps to reproduce
---

# Environment details
---
main server:
`jicofo/stable,now 1.0-1057-1 all`
`jitsi-meet-prosody/stable,now 1.0.7658-1 all`
`jitsi-meet-turnserver/stable,now 1.0.7658-1 all`
`jitsi-meet/stable,now 2.0.9111-1 all`
`jitsi-videobridge2/stable,now 2.3-61-g814bffd6-1 all`

jvb server (not working):
`jitsi-videobridge2/stable,now 2.3.105-ge155b81e-1 all`

jvb server (working):
`jitsi-videobridge2/stable,now 2.3.61-g814bffd6-1 all`

**Comment by damencho** [comment]
Are you mixing versions of jvb on same deployment by any chance?

**Comment by pouriamoosavi** [comment]
Yes we are. Is it not fine? (We didn't know that)

**Comment by damencho** [comment]
Yep, that is not supported. You need just one version.

**Comment by pouriamoosavi** [comment]
OK thanks. Will remove this issue
Sorry
