### ISSUE TITLE
Rejoin now when second person join to conference

### ISSUE THREAD

**Issue by therock42** [jitsi/jitsi-videobridge#2162]
For the Installation i have Internet Access.
After that the Server is used offline in a LAN & I have local Domain.
when end of installation I test it it's working fine but when test it offline it's not work when second person join to conference.
when back it to access internet it's working .

**Comment by aaronkvanmeerten** [comment]
I have transferred your issue out of the docker-jitsi-meet project in order to better associate it with correct type of project and stop any confusion about docker.

**Comment by aaronkvanmeerten** [comment]
As far as configuration goes, you shouldn't reference any thing docker-specific, which means you shouldn't use the 172.1x.x.x network either.

This is far outside my expertise as I have never run this for a local network. 
 You'll probably need to look up what internal IP address your instance has, and configure that for both sides of static mapping.  I'll also ask some of the team today to see if anyone else has any tips.

**Comment by therock42** [comment]
> As far as configuration goes, you shouldn't reference any thing docker-specific, which means you shouldn't use the 172.1x.x.x network either.
> 
> This is far outside my expertise as I have never run this for a local network. You'll probably need to look up what internal IP address your instance has, and configure that for both sides of static mapping. I'll also ask some of the team today to see if anyone else has any tips.

if there are to side jitsi on 172.16.x.x and other side is 192.168.x.x
what's configuration i could edit

**Comment by saghul** [comment]
Then out the loca IP to the 172 one and the public part to 192.

**Comment by therock42** [comment]
> Then out the loca IP to the 172 one and the public part to 192.

my local ip is single (jitsi ip addr) but the public will be network like 192.168.x.x/24

**Comment by aaronkvanmeerten** [comment]
> if there are to side jitsi on 172.16.x.x and other side is 192.168.x.x
> what's configuration i could edit

If you aren't running jitsi in docker, please do not configure any docker networking.  The 172.16.x.x network is going to be docker-specific which means ONLY accessible on the one machine running docker containers.  Unless your jitsi is running inside this docker container (if you followed the instructions you linked, it won't be), then you can disregard anything docker-specific (like the 172.16.x.x network).

So, you have a VM with a 192.168.x.x address.  Then traditionally it's using STUN to detect its public address (while you are connected to the internet).  We have suggested configurations that disable this STUN automated mapping, which requires a static mapping.  The static mapping would simply reference the same 192.168.x.x address and port in both public and private side.

**Comment by therock42** [comment]
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.ji>
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.jitsi.su.sd
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=BioAAIza
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.jitsi.s>
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=3c601c28-440c-4d42-9ac9-84ce>

What needs to be modified

**Comment by aaronkvanmeerten** [comment]
Hi, I suggest you stop using the sip-communicator.properties file for any of this, as they are deprecated and should simply not be used.

Please use the jvb.conf syntax as suggested in this thread instead.

**Comment by damencho** [comment]
> pro i don't know if my jitsi docker or not i'm install it from https://www.digitalocean.com/community/tutorials/how-to-install-jitsi-meet-on-ubuntu-22-04
> 
> plz help me i wanna to start it locally without internet access after install it

That ^ guide is outdated. 
https://jitsi.org/qi is the one we support and keep updated.

**Comment by therock42** [comment]
> > what is right configuration to add it?
> 
> So specifically for disabling harvesting and hard-coding a static mapping:
> 
> ```
> ice4j {
>   harvest {
>     mapping.stun.enabled = false
>             static-mappings = [
>                 {
>                     local-address = "<docker address>"
>                     local-port = <docker port>
>                     public-address = "<public address>"
>                     public-port = "<public port>"
>                     name = "<something unique>"
>                 }
>             ]
>     }
>   }
> }
> ```

what about docher port?
is local port is: 1000?
public port is :1000?

**Comment by aaronkvanmeerten** [comment]
> is local port is: 1000?
> public port is :1000?

Yes, in this case it's not docker port, but rather local port and remote port.  Since you aren't doing any host->docker translations of port, the 10000 is correct in both cases.  Make sure you make it 10000, not 1000 as you have posted here.

**Comment by therock42** [comment]
> > is local port is: 1000?
> > public port is :1000?
> 
> Yes, in this case it's not docker port, but rather local port and remote port. Since you aren't doing any host->docker translations of port, the 10000 is correct in both cases. Make sure you make it 10000, not 1000 as you have posted here.

videobridge {
    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "jitsi.su.sd:443"
        tls = true
    }
}

ice4j {
  harvest {
    mapping.stun.enabled = false
            static-mappings = [
                {
                    local-address = "192.168.1.38"
                    local-port = 10000
                    public-address = "192.168.1.38"
                    public-port = "10000"
                    name = "therock"
                }
            ]
    }
  }
}

still not work

**Comment by therock42** [comment]
Jicofo 2024-06-03 13:26:51.680 INFO: [47] ConferenceIqHandler.handleConferenceIq#86: Conference request for room test4@conference.jitsi.su.sd, from 1p8r-ckvfmacprtna5arywl6@guest.jitsi.su.sd/uYtf23WukJ9c
Jicofo 2024-06-03 13:26:51.681 INFO: [47] AbstractAuthAuthority.authenticateJidWithSession#431: Authenticated jid: 1p8r-ckvfmacprtna5arywl6@guest.jitsi.su.sd/uYtf23WukJ9c with session: AuthSession[ID=usr@jitsi.su.sd, JID=1p8r-ckvfmacprtna5arywl6@guest.jitsi.su.sd/uYtf23WukJ9c, SID=3620e045-e7ee-4d04-967f-8c3449ef1eb5, MUID=9a98efb3eddda97a9c6200d0ed023e4d, LIFE_TM_SEC=297, R=test3@conference.jitsi.su.sd]@297203553
Jicofo 2024-06-03 13:26:51.682 INFO: [47] AbstractAuthAuthority.notifyUserAuthenticated#339: Jid 1p8r-ckvfmacprtna5arywl6@guest.jitsi.su.sd/uYtf23WukJ9c authenticated as: usr@jitsi.su.sd
Jicofo 2024-06-03 13:26:51.684 INFO: [47] [room=test4@conference.jitsi.su.sd] JitsiMeetConferenceImpl.<init>#308: Created new conference.
Jicofo 2024-06-03 13:26:51.685 INFO: [47] [room=test4@conference.jitsi.su.sd] JitsiMeetConferenceImpl.joinTheRoom#499: Joining test4@conference.jitsi.su.sd
Jicofo 2024-06-03 13:26:51.941 INFO: [47] [xmpp_connection=client] XmppProvider.discoverFeatures#248: Discovered features for test4@conference.jitsi.su.sd/6b67eccf in 0 ms.
Jicofo 2024-06-03 13:26:51.942 INFO: [47] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.onMemberJoined#743: Member joined:6b67eccf stats-id=Rosamond-PjN region=null audioMuted=true videoMuted=true role=PARTICIPANT isJibri=false isJigasi=false isTranscriber=false, room=main
Jicofo 2024-06-03 13:27:04.263 INFO: [47] ConferenceIqHandler.handleConferenceIq#86: Conference request for room test4@conference.jitsi.su.sd, from su03ervuhwznvert8z-vcvra@guest.jitsi.su.sd/8_iTQM5FK9uU
Jicofo 2024-06-03 13:27:04.563 INFO: [47] [xmpp_connection=client] XmppProvider.discoverFeatures#248: Discovered features for test4@conference.jitsi.su.sd/5467efd9 in 0 ms.
Jicofo 2024-06-03 13:27:04.564 INFO: [47] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.onMemberJoined#743: Member joined:5467efd9 stats-id=Hilton-Wgl region=null audioMuted=true videoMuted=true role=PARTICIPANT isJibri=false isJigasi=false isTranscriber=false, room=main
Jicofo 2024-06-03 13:27:04.565 INFO: [47] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.inviteChatMember#815: Creating participant 6b67eccf with features=[XMPP_CAPS, JSON_SOURCES, RECEIVE_MULTIPLE_STREAMS, REMB, SOURCE_NAMES, SSRC_REWRITING_V1, TCC, VISITORS_V1, RTX, JINGLE, DTLS, JINGLE_RTP, AUDIO, VIDEO, SCTP, JINGLE_ICE, RAYO]
Jicofo 2024-06-03 13:27:04.566 INFO: [47] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.<init>#81: Using org.jitsi.jicofo.bridge.SingleMeshTopologyStrategy
Jicofo 2024-06-03 13:27:04.566 INFO: [47] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.inviteChatMember#815: Creating participant 5467efd9 with features=[XMPP_CAPS, JSON_SOURCES, RECEIVE_MULTIPLE_STREAMS, REMB, SOURCE_NAMES, SSRC_REWRITING_V1, TCC, VISITORS_V1, E2EE, RTX, JINGLE, DTLS, JINGLE_RTP, AUDIO, VIDEO, SCTP, JINGLE_ICE, RAYO]
Jicofo 2024-06-03 13:27:04.568 INFO: [51] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.allocate#278: Allocating for 6b67eccf
Jicofo 2024-06-03 13:27:04.568 WARNING: [51] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-06-03 13:27:04.569 SEVERE: [51] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70 participant=6b67eccf] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
Jicofo 2024-06-03 13:27:04.583 INFO: [52] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.allocate#278: Allocating for 5467efd9
Jicofo 2024-06-03 13:27:04.591 WARNING: [52] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-06-03 13:27:04.592 SEVERE: [52] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70 participant=5467efd9] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
Jicofo 2024-06-03 13:27:04.827 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.onMemberLeft#957: Member left:6b67eccf
Jicofo 2024-06-03 13:27:04.834 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.terminateParticipant#1036: Terminating 6b67eccf, reason: gone, send session-terminate: false
Jicofo 2024-06-03 13:27:04.835 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.terminateParticipant#1050: Removed participant 6b67eccf removed=true
Jicofo 2024-06-03 13:27:04.835 WARNING: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.removeParticipant#126: Can not remove 6b67eccf, no participantInfo
Jicofo 2024-06-03 13:27:04.835 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.rescheduleSingleParticipantTimeout#2028: Scheduled single person timeout.
Jicofo 2024-06-03 13:27:05.983 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.onMemberLeft#957: Member left:5467efd9
Jicofo 2024-06-03 13:27:05.983 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.terminateParticipant#1036: Terminating 5467efd9, reason: gone, send session-terminate: false
Jicofo 2024-06-03 13:27:05.984 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.terminateParticipant#1050: Removed participant 5467efd9 removed=true
Jicofo 2024-06-03 13:27:05.984 WARNING: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.removeParticipant#126: Can not remove 5467efd9, no participantInfo
Jicofo 2024-06-03 13:27:05.984 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.expire#110: Expiring.
Jicofo 2024-06-03 13:27:05.984 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.maybeStop#1004: Last member left, stopping.
Jicofo 2024-06-03 13:27:05.984 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] ColibriV2SessionManager.expire#110: Expiring.
Jicofo 2024-06-03 13:27:05.989 INFO: [49] [room=test4@conference.jitsi.su.sd meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70] JitsiMeetConferenceImpl.stop#476: Stopped.


same issue

**Comment by therock42** [comment]
i need to disabe stun ?

how to disable it on /etc/jitsi/videobridge/jvb.conf ?

**Comment by aaronkvanmeerten** [comment]
> mapping.stun.enabled = false

You already have it disabled via the above.

**Comment by aaronkvanmeerten** [comment]
```
Jicofo 2024-06-03 13:27:04.568 WARNING: [51] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-06-03 13:27:04.569 SEVERE: [51] [room=[test4@conference.jitsi.su.sd](mailto:test4@conference.jitsi.su.sd) meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70 participant=6b67eccf] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
```

This indicates that your bridge is not successfully configured to connect to your prosody, so your jicofo isn't finding it.  How do you have the prosody configuration set up today in jvb.conf?

**Comment by therock42** [comment]
> ```
> Jicofo 2024-06-03 13:27:04.568 WARNING: [51] BridgeSelector.selectBridge#182: There are no operational bridges.
> Jicofo 2024-06-03 13:27:04.569 SEVERE: [51] [room=[test4@conference.jitsi.su.sd](mailto:test4@conference.jitsi.su.sd) meeting_id=b8f74b96-b226-4af6-99e2-3b91acc04b70 participant=6b67eccf] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
> ```
> 
> This indicates that your bridge is not successfully configured to connect to your prosody, so your jicofo isn't finding it. How do you have the prosody configuration set up today in jvb.conf?

i sent sudo nano /etc/jitsi/videobridge/jvb.conf above

**Comment by aaronkvanmeerten** [comment]
I believe you are missing the xmpp configuration.  This should all have been configured by default via the debian installer during setup if you followed this one:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/

so I'm not sure why you'd be missing it now.  Can you send again the current contents of you sip-communicator.properties

**Comment by therock42** [comment]
> I believe you are missing the xmpp configuration. This should all have been configured by default via the debian installer during setup if you followed this one: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/
> 
> so I'm not sure why you'd be missing it now. Can you send again the current contents of you sip-communicator.properties

org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=meet-jit-si-turnrelay.jitsi.net:443
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc
org.jitsi.videobridge.xmpp.user.shard.HOSTNAME=localhost
org.jitsi.videobridge.xmpp.user.shard.DOMAIN=auth.jitsi.su.sd
org.jitsi.videobridge.xmpp.user.shard.USERNAME=jvb
org.jitsi.videobridge.xmpp.user.shard.PASSWORD=4Fr0Oq1d
org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS=JvbBrewery@internal.auth.jitsi.su.sd
org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=0aa2842b-b2d9-43e1-9735-3060c961073f

**Comment by aaronkvanmeerten** [comment]
this all looks correct to me then, can you restart your videobridge service with a `sudo service jitsi-videobridge restart` and see if that helps?

**Comment by therock42** [comment]
> this all looks correct to me then, can you restart your videobridge service with a `sudo service jitsi-videobridge restart` and see if that helps?
i do it not solve
i'm trying docker

**Comment by therock42** [comment]
![image](https://github.com/jitsi/jitsi-videobridge/assets/171142648/32716a0f-090f-45d9-add8-96b9100303a9)
![image](https://github.com/jitsi/jitsi-videobridge/assets/171142648/4354b196-7afb-4a49-bc7d-5efe6aefaad2)

**Comment by saghul** [comment]
We don't recommend to use root for running your containers. At any rate, is it working?

**Comment by therock42** [comment]
> We don't recommend to use root for running your containers. At any rate, is it working?

it isn't working

**Comment by therock42** [comment]
> > We don't recommend to use root for running your containers. At any rate, is it working?
> 
> it isn't working

**Comment by therock42** [comment]
![image](https://github.com/jitsi/jitsi-videobridge/assets/171142648/96ab781d-270e-40e7-a227-320704a0235b)

**Comment by saghul** [comment]
Please share logs EVERY TIME, a screenshot tells us virtually nothing.

Also, your TLS cert is not good.

**Comment by therock42** [comment]
dears its solved 
thanks a lot for support 
added port for PUBLIC_URL=192.168.x.x:8443

**Comment by badfiles** [comment]
> added port for PUBLIC_URL=192.168.x.x:8443

there is no reference to PUBLIC_URL in this discussion
