### ISSUE TITLE
please add logrotating

### ISSUE THREAD

**Issue by DanScharon** [jitsi/jitsi-videobridge#217]
At the moment jvb.log increases infinitely, unless the videobridge is restarted. Please add a logrotate definition as a template or, even better include it into the postinst of the packaging.

An example content could be:
```
/var/log/jitsi/jvb.log {
  copytruncate
  daily
  rotate 7
  compress
  missingok
  create 640 jvb jitsi
}
```

**Comment by damencho** [comment]
This will not work, as long as you rotate the logs you will lose the logs as log new log file will stay with size zero. The best approach for the moment is to use syslog. Otherwise the way logging is done currently needs to be changed, the init script starting the process, any patches are welcome.

**Comment by DanScharon** [comment]
I see, I've changed the title accordingly

**Comment by photoninger** [comment]
I'm using the following logrotate config and it works:
`/var/log/jitsi/jicofo.log {
        daily
        missingok
        rotate 7
        compress
        delaycompress
        notifempty
        copytruncate
        su jicofo jitsi
}

/var/log/jitsi/jvb.log {
        daily
        missingok
        rotate 7
        compress
        delaycompress
        notifempty
        copytruncate
        su jvb jitsi
}
`
copytruncate does the magic, when the logging process does not close and reopen it's file handles.

**Comment by damencho** [comment]
@DanScharon does this solves the problem for you? @photoninger thanks for the update.

**Comment by DanScharon** [comment]
@damencho yes, this definitely solves it. Would be nice to have it as template within the debian packaging @photoninger thanks for the quick hint!

**Comment by damencho** [comment]
logrotate has been added to latest versions of jicofo and jvb.
