### ISSUE TITLE
feat: Remove support for ICE/TCP. (#2194)

### ISSUE THREAD

**Issue by dvn2018** [jitsi/jitsi-videobridge#2222]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Feature is needed for Sealed Environments

## Current behavior
not working

## Expected Behavior
working

## Possible Solution
bring it back

## Steps to reproduce
only communication path is tcp/443

# Environment details
---

**Comment by damencho** [comment]
You can achieve that with coturn, which is the way to go.

**Comment by dvn2018** [comment]
Ok, thanks good to know, sometimes hard to find :-)

**Comment by dvn2018** [comment]
Hi, which coturn server do you use ?

**Comment by damencho** [comment]
What do you mean? https://github.com/coturn/coturn
There is a package available in Debian and Ubuntu.
https://github.com/jitsi/jitsi-meet/blob/2413b8977ebcfeadb541c160fe493ef457bc99f8/debian/control#L57
And this is the template we use for default coturn config when you install jitsi-meet package
https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-turn/turnserver.conf

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by dvn2018** [comment]
Ok. Undestood. Thank you
