### ISSUE TITLE
metrics are served in json by default

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-videobridge#2234]
metris are served in json by default:

```
# curl localhost:8080/metrics
{"endpoints_with_suspended_sources":0,"srtp_send_queue_excepti...
```

**Comment by bgrozev** [comment]
Thank you for the report! It looks like the default format we return (when no Accept header is set) is not set deterministically. I get different behavior after restarting the JVM, it probably has to do with the order in [which the annotations are processed](https://github.com/jitsi/jicoco/blob/fed03206725aab99ecc49e0f3ae0762fd4933959/jicoco-metrics-jetty/src/main/java/org/jitsi/rest/prometheus/Prometheus.java#L47).

I don't think it's a regression, as I can repro after restarting with 2.3.160 as well. To get consistent behavior add an "Accept" header like described here:
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md#prometheus


This behavior is bad and I'll fix it, but I'm not sure what default to go with. In jibri we use JSON as a default, and I'd like to keep it consistent between projects.

**Comment by 532910** [comment]
it's my fault, not a regression, sorry ):
