### ISSUE TITLE
Upgrading jitsi-videobridge (stable) fails on Ubuntu 22.04.05

### ISSUE THREAD

**Issue by bmilde** [jitsi/jitsi-videobridge#2253]
Upgrading jitsi-videobridge fails on 22.04 (Ubuntu 22.04.5 LTS GNU/Linux 6.8.0-48-generic x86_64) and results in a broken installation:

jitsi-videobridge2 (2.3-174-gd011ddf7-1) wird eingerichtet ...
/usr/lib/ruby/vendor_ruby/hocon/impl/path_parser.rb:84:in `parse_path_expression': Expecting a field name or path here, but got nothing (Hocon::ConfigError::ConfigBadPathError)
        from /usr/lib/ruby/vendor_ruby/hocon/impl/path_parser.rb:73:in `parse_path_node_expression'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:287:in `parse_key'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:397:in `parse_object'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:253:in `parse_value'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:404:in `parse_object'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:585:in `parse'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/config_document_parser.rb:38:in `parse'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:275:in `raw_parse_document_from_io'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:268:in `block in raw_parse_document'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:374:in `block in open'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:373:in `open'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:373:in `open'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:267:in `raw_parse_document'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:212:in `parse_document_from_origin'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:207:in `parse_document'
        from /usr/lib/ruby/vendor_ruby/hocon/impl/parseable.rb:280:in `parse_config_document'
        from /usr/lib/ruby/vendor_ruby/hocon/parser/config_document_factory.rb:34:in `parse_string'
        from /usr/lib/ruby/vendor_ruby/hocon/cli.rb:156:in `do_set'
        from /usr/lib/ruby/vendor_ruby/hocon/cli.rb:118:in `main'
        from /usr/bin/hocon:4:in `<main>'
dpkg: Fehler beim Bearbeiten des Paketes jitsi-videobridge2 (--configure):
 »installiertes jitsi-videobridge2-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
Fehler traten auf beim Bearbeiten von:
 jitsi-videobridge2
E: Sub-process /usr/bin/dpkg returned an error code (1)

I'm using the stable apt package source on this server:

deb [signed-by=/usr/share/keyrings/jitsi-keyring.gpg] https://download.jitsi.org stable/

**Comment by bmilde** [comment]
Maybe this commit is the culprint? 

https://github.com/jitsi/jitsi-videobridge/commit/6e441e62bd4a47bce8a75ded2dc8d886459eaaf9

It's the only recent change in the debian folder and the error message I'm getting is related to hocon.

**Comment by damencho** [comment]
What is the version that you upgrade? Can you share the jvb.conf you have masking any private info?

**Comment by bmilde** [comment]
I think it's trying to upgrade from 2.3-165 to 2.3-174:

myserver:~$ dpkg -s jitsi-videobridge2 | grep Version
Version: 2.3-174-gd011ddf7-1
Config-Version: 2.3-165-gb7dba824-1

Here's my jvb.conf:

videobridge {
    health {
    require-valid-address = false
    interval = 1 minute
    timeout = 90 seconds
    max-check-duration = 3 seconds
    sticky-failures = false
    require-stun = false

    http-servers {
        public {
            port = 9090
        }
    }
    websockets {
        enabled = true
        domain = "my.domain.redacted:443"
        tls = true
    }
    apis: {
      rest: {
        enabled: false
      }
    }
}

**Comment by damencho** [comment]
The cause of the problem is that your jvb.conf is broken, you forgot to close the health opening `{`.

**Comment by damencho** [comment]
Your jvb will barf with that broken conf file.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
