### ISSUE TITLE
Is it possible to have an RPM release in addition to DEB?

### ISSUE THREAD

**Issue by Ashaman-** [jitsi/jitsi-videobridge#315]
It would be nice to be able to run jvb and jicofo on CentOS without having to build from source or use a chroot/docker. And with repository updates.

**Comment by bryanasdev000** [comment]
+1 from me.

**Comment by damencho** [comment]
We had stated several times that we only support Debian as this is what we use. Adding one more packaging system is not feasible for us and we cannot support it as we do not use it and we do not have the resources to do it. Having something we do not use had proven in the past that it does not work.
You can use the docker images on any system ...
