### ISSUE TITLE
the rest api guide doesn't work

### ISSUE THREAD

**Issue by Place1** [jitsi/jitsi-videobridge#319]
Hi, total newb here.

I just wanted to explore the project and I started by getting jitsi videobridge 812 for OS X.
I started it using the --api=rest flag and I was able to curl /colibri/conferences and get an empty array "[]" back so it appears to be working.

So I started following the guide and doing:
```
curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d '[]' "http://localhost:8080/colibri/conferences/"
```
and i got a 406 Not Acceptable.

I also tried posting the other example in the docs:
```
{ 
    "contents" : 
    [ 
        {
             "name" : "audio", 
             "channels" : [ { "expire" : 60 } ] 
        }, 
        { 
            "name" : "video", 
            "channels" : [ { "expire" : 60 } ] 
        } 
    ] 
}
```
but I got the same results.

Could someone point me in the right direction or confirm this is a bug?

**Comment by jitsi-developers** [comment]
I think someone just posted a pull request to fix a typo in that
guide...the initial post should be an empty json object ("{}") instead of
an empty json array ("[]").  Give that a try and see if it fixes your
problem.

**Comment by Place1** [comment]
Yeah posing "{}" was one of the things I tried. Any other thoughts?

**Comment by jitsi-developers** [comment]
I just tried the same command as you on my bridge:

curl -X POST -H "Accept: application/json" -H "Content-Type:
application/json" -d "{}" <bridge url>

and I got a proper response back (a newly allocated conference id).
Looking at the bridge, that error seems to come from the bridge thinking it
hasn't received json application type (if this
<https://github.com/jitsi/jitsi-videobridge/blob/4310a452e067440385119bae78b74938b1330e1f/src/main/java/org/jitsi/videobridge/rest/HandlerImpl.java#L656>
if
statement fails, it'll return 406 for a post).  You could add some logs and
double check what content type the bridge is seeing.  Wireshark might be
able to shed some light there, too.

**Comment by Place1** [comment]
hmm. never mind. that curl seems to work for me too. I was using Postman so perhaps there some some weird interaction going on.
All good, sorry for you time and thanks for the quick help!
