### ISSUE TITLE
Error - Jitsi Videobridge is currently unavailable. Please try again later!

### ISSUE THREAD

**Issue by bugreport42** [jitsi/jitsi-videobridge#327]
That is the error that jitsi-meet throws randomly within an hour after booting. Active connections don't get interrupted, but you can't refresh and new users can't join. Stopping then starting the jitsi-videobridge service fixes it.

I'm running this on a VPS with Debian 8.6 and installed everything wih the [quick install](https://github.com/turint/jitsi-meet/blob/master/doc/quick-install.md).

Many thanks in advance!

**Comment by damencho** [comment]
Please us the mailinglist for asking question before opening issues.

After restarting jvb did you wait, sometimes it takes 30secs to a minute for jicofo to see the jvb, you can see that in the jicofo logs(not sure what is the default setting for that timeout). 

Also did you saw any errors in jvb or jicofo logs when this occurs.
