### ISSUE TITLE
support rtp rotation extension?

### ISSUE THREAD

**Issue by richmonkey** [jitsi/jitsi-videobridge#378]
I compiled webrtc from latest source(commitid:e36c46ede34a845f1304a8c750367ef7fde0a29c)
Local video is rotated 90 when phone is portrait.
Videobridge does't support rotation extension?

**Comment by bgrozev** [comment]
jitsi-videobridge will preserve any extensions which it does not recognize. That being said, the extension is likely not included in the offers that the client sets. Check webrtc-internals.

**Comment by richmonkey** [comment]
webrtc's issue.
avfoundationvideocapturer, videocapture rotate twice.
