### ISSUE TITLE
Openfire plugin

### ISSUE THREAD

**Issue by Pero1** [jitsi/jitsi-videobridge#397]
Hi!

Can anyone help me how can I start new video conference with Openfire and jitsi-videobridge plugin for Openfire. I built plugin for Openfire and installed it, but what now?

I'm using Openfire 4.1.1 and the latest jitsi-videobridge plugin in my localhost.

Thank you.

**Comment by damencho** [comment]
Could you please use the mailinglist for questions and problems before opening issues.

If you just want to use videobridge and openfire, currently you can use the jitsi desktop client to create a jitsi-videobridge conference. Other than that you can create a client to use it. You can use jitsi-meet and jicofo but there is no automated install and configure for those and you need to do it by yourself.
