### ISSUE TITLE
Start a video conference

### ISSUE THREAD

**Issue by sfreundlich** [jitsi/jitsi-videobridge#398]
Hi!

Can anyone help me how can I start a new video conference on with a chrome.
I have installed both jitsi-videobridge and OpenFire, connect them and now I can see the video bridge as an external component active session in the OpenFire admin console.
I'm trying to create a simple demo of a conference with 3 clients.

Thank you.

**Comment by damencho** [comment]
Could you please use the mailinglist for questions and problems before opening issues.

If you just want to use videobridge and openfire, currently you can use the jitsi desktop client to create a jitsi-videobridge conference. Other than that you can create a client to use it. You can use jitsi-meet and jicofo but there is no automated install and configure for those and you need to do it by yourself.
