### ISSUE TITLE
Make ICE to use local client address candidate

### ISSUE THREAD

**Issue by anzharip** [jitsi/jitsi-videobridge#399]
Is it possible to configure jitsi-videobridge/jitsi-meet (I'm not sure where to configure on between those two components) to allow local address candidate to be used for media stream, instead of their public IP address?
Both of web browser endpoint is in the same LAN and network segment, behind a NAT router. 
I'm running jitsi-meet on my Internet hosted servers.
Video and audio stream is working normally. 
I'm using Firefox 52 for both of my client.
I checked about:webrtc, and it shows in the ICE local and remote candidate both local ip address and public ip address, but the one with public ip address is always nominated and selected.
The reason: to help with media quality, during poor Internet bandwidth quality. 
I checked jitsi-meet, jitsi-videobridge, and ice4j docs, but I think I didn't find the configuraion related to this. 
Thanks!

**Comment by damencho** [comment]
Sending an email to the dev list is enough (as you already did, thanks) and there is no need to open issues for questoins.

**Comment by anzharip** [comment]
Sorry for the hassle! I'll continue on the dev mailing list.
