### ISSUE TITLE
Clean git

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-videobridge#441]
This git repo is 160.46MB, I'm not sure all the data are really needed.
Maybe a little clean could be handy :)

**Comment by damencho** [comment]
Could you please use the mailinglist when you want to discuss something, before opening issues. 
The repo is 3.6MB, the size you see is git history which we do not want to remove, the big size of history is coming from the time before moving artifacts to maven repo. If you do not want history just clone latest: git clone --depth 1 https://github.com/jitsi/jitsi-videobridge.git

**Comment by pierreozoux** [comment]
(sorry not to use the mailing list, but:
 - here it is so convenient
 - I really love the web, and the possibility to easily link things together
 - here it is aweful UI/UX: http://lists.jitsi.org/pipermail/dev/
 - and I don't want to subscribe to the full mailing list, but just specific issues
 - and your mailing list is not even secured... by https... http://lists.jitsi.org/mailman/listinfo/dev
 - and generally, projects in github just uses issues to discuss things, and not mailing list
 - the readme doesn't have a contributing.md to explain guidelines like this one
)

About the size, this is what I though, but you know that you shouldn't keep artifacts in git, it is not made for that. You can clean them. And if you want to keep them, upload them somewhere else.

It is just that if we are 100s downloading these 100MB, it is not green at all, and sorry by default, github doesn't offer to clone just latest.

Sorry, I'm not complaining here, just try to make the world a better place :)

And next time, I'll use the mailing list!

**Comment by damencho** [comment]
Yep, keeping artifacts is already fixed, we are using a maven repo for that, but we should not scrap the history.

**Comment by damencho** [comment]
The mainlinglist is our preferred way of communication. Lists archive is just an archive, communication goes over email which security is beyond this discussion. 
And we try to use issues only for issues, if this is not the case we should just close and not use that issues option on github, this is stated and all our README files.
