### ISSUE TITLE
JVB looks incompatible with desktop clients anymore

### ISSUE THREAD

**Issue by u07** [jitsi/jitsi-videobridge#460]
You know, there are two options, how to make a conference call using desktop client. You click "make a conference", and Jitsi instance routes RTP streams by itself, and it works. Or you click "make a videobridge call" and then a videobridge instance should do it's job. But.. hm.. Actually it does not.

I have a simple openfire+videobridge installation. Jitsi meet works, but when I make a videobridge call using desktop client, that guy "Videobridge" _does not want to resend incoming rtp streams_ to other participants. That's all. No another errors. No errors at all. Perfect logfiles.

The question is, is it just me, or you really have broken something? 

P.S. Logfiles https://yadi.sk/d/I_dVOhx73HXdD3
P.P.S. Topic in /users/ http://lists.jitsi.org/pipermail/users/2017-May/012872.html

**Comment by gpolitis** [comment]
It's possible that the adaptivity work has broken this. I can add a java sys prop that disables adaptivity completely so that we can A/B test things like this.

**Comment by u07** [comment]
Sounds reasonable. Could you, please?

**Comment by gpolitis** [comment]
I've had a discussion with @bgrozev and he let me know of a couple of other significant things that are broken. It looks like that at this point, it would take a significant effort to make the JVB compatible with the Jitsi client and we don't have the bandwidth for that.

**Comment by u07** [comment]
Okay, I understand, thanks. Just for clarification, is it over, the desktop client? Or it's destiny isn't clear enough to make any predictions?

**Comment by emcho** [comment]
As far as Atlassian is concerned, we don't have the resources to continue advancing it. There is work in the community on maintaining it though and everyone is welcome.

I am going to close this ticket now. If a volunteer is ready to work on it, we can reopen
