### ISSUE TITLE
Pull #457 for debian installer breaks OpenVZ upgrades/install due to sysctl

### ISSUE THREAD

**Issue by ericmoon** [jitsi/jitsi-videobridge#461]
The config/20-jvb-udp-buffers.conf file addition in pull #457 breaks the upgrade/install for anyone on OpenVZ.  OpenVZ containers do not typically allow permission to modify the kernel with sysctl config values.

Not sure how you want to handle - you can't cover every possible hosting situation -  but I wanted to document in case anyone else ran into the error.  Full error log from an 'apt-get upgrade' is below.  Workaround is to comment out the 2 lines in the config/20-jvb-udp-buffers.conf file

```

dpkg: error processing package jitsi-meet (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 jitsi-videobridge
 jitsi-meet
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up jitsi-videobridge (939-1) ...
* Applying /etc/sysctl.d/20-jvb-udp-buffers.conf ...
sysctl: permission denied on key 'net.core.rmem_max'
sysctl: permission denied on key 'net.core.netdev_max_backlog'
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.conf ...
dpkg: error processing package jitsi-videobridge (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of jitsi-meet:
 jitsi-meet depends on jitsi-videobridge (= 939-1); however:
  Package jitsi-videobridge is not configured yet.

dpkg: error processing package jitsi-meet (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 jitsi-videobridge
 jitsi-meet
```

**Comment by damencho** [comment]
Thanks for reporting it @ericmoon, can you test jvb version 940. You can delete /etc/sysctl.d/20-jvb-udp-buffers.conf before updating, so we test the same case as when you upgraded to 939.

It will still add that file and will try to do sysctl and you will see the prints about permission denied, but at least it will not break the update.

Thanks

**Comment by ericmoon** [comment]
Version 940 worked.  It reported the 'permission denied', but kept processing the packages.
Thanks for the quick fix! Closing...
