### ISSUE TITLE
BindException "Address already in use" on a non-default port

### ISSUE THREAD

**Issue by Jesse-V** [jitsi/jitsi-videobridge#465]
First off, thanks for the great software! I love using this as an alternative to Skype.

I am working on setting my own jitsi-meet instance on a VPS running Ubuntu 14.04. This VPS has two external IP addresses and has a web server running on 80 and 443, so I've been trying to set up the video bridge to use something like 8443. I have installed the stable edition of the jitsi-meet package and it seems to work great on the default 443 port once I shut down my web server (lighttpd) and then start the jicofo and jitsi-videobridge services. To avoid a conflict over 443, I tried to change the ports from 443 to 8443 in /etc/jitsi/videobridge/sip-communicator.properties, but this seems to break the video connection. I can open the room URL (/testing123) and approve my mic and webcam, but the self-video no longer appears. I see the following error messages in /var/log/jitsi/jvb.log:

> JVB 2017-05-07 19:47:35.509 WARNING: [47] org.jitsi.videobridge.IceUdpTransportManager.log() Failed to initialize TCP harvester on port 8443: java.net.BindException: Address already in use.
> JVB 2017-05-07 19:47:35.530 SEVERE: [68] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
> JVB 2017-05-07 19:47:35.535 WARNING: [47] org.jitsi.xmpp.component.ComponentBase.verifyProcessingTime().538 PROCESSING TIME LIMIT EXCEEDED - it took 325ms to process: <iq type="get" to="jitsi-videobridge.jitsi.MYDOMAIN.com" from="focus@auth.jitsi.MYDOMAIN.com/focus16115261940329847" id="qf1gg-25"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> JVB 2017-05-07 19:47:45.231 SEVERE: [134] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
> JVB 2017-05-07 19:48:05.227 SEVERE: [278] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
> JVB 2017-05-07 19:48:05.440 SEVERE: [289] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
> JVB 2017-05-07 19:48:05.445 WARNING: [244] org.jitsi.xmpp.component.ComponentBase.verifyProcessingTime().538 PROCESSING TIME LIMIT EXCEEDED - it took 239ms to process: <iq type="get" to="jitsi-videobridge.jitsi.MYDOMAIN.com" from="focus@auth.jitsi.MYDOMAIN.com/focus16115261940329847" id="qf1gg-39"><healthcheck xmlns="http://jitsi.org/protocol/healthcheck"/></iq>
> JVB 2017-05-07 19:48:55.223 SEVERE: [576] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.
> JVB 2017-05-07 19:48:55.224 SEVERE: [578] org.ice4j.socket.MergingDatagramSocket.log() Cannot find socket to remove.

This warning also appears in /var/log/jitsi/jicofo.log:
> Jicofo 2017-05-07 19:47:25.201 WARNING: [39] org.jitsi.jicofo.BridgeSelector.addJvbAddress().159 No pub-sub node mapped for jitsi-videobridge.jitsi.MYDOMAIN.com

I am confused why it works wonderfully when .rest.jetty.port, .jetty.tls.port, and .TCP_HARVESTER_PORT are all set to 443, but it no longer work when they are on 8443 or another port. No other software is using that port on any IP address. This sounds like a bug, but it could also be due to my lack of familiarity with the software. What could be causing this and how do I fix it?

**Comment by saghul** [comment]
If you leave all options commented out, it should bind to port 4443. Also note that you don't need to use the builtin Jetty server if you are already using your own web server to serve Jitsi Meet.

**Comment by Jesse-V** [comment]
Thanks @saghul. What options do I need to comment out to have it bind to 4443? Should I comment out everything in videobridge/sip-communicator.properties, or just .rest.jetty.port, .jetty.tls.port, and .TCP_HARVESTER_PORT?

**Comment by saghul** [comment]
@Jesse-V comment out everything in videobridge/sip-communicator.properties. That should do.

**Comment by Jesse-V** [comment]
@saghul I think the bigger issue was that it was running on Java 7. I hacked something together to get JRE 8 installed, which seems to have fixed the issues for now. I had some intermediate connectivity problems, but they may be unrelated.

**Comment by saghul** [comment]
Not sure how that could be related 🤷‍♂️ At any rate, holler if you need to reopen this, I'm closing this since you got it working.
