### ISSUE TITLE
Must implement sending RTCP PLI (in addition to FIR)

### ISSUE THREAD

**Issue by ibc** [jitsi/jitsi-videobridge#470]
I've been told in the mailing list that jitsi-videobridge cannot generate PLI but just FIR.

It happens that Microsoft Edge does not implement FIR but just PLI.

**Comment by gpolitis** [comment]
I believe this is now fixed, right @bgrozev?

**Comment by bgrozev** [comment]
Correct. In fact PLI is now preferred to FIR (used if both are advertised).
