### ISSUE TITLE
Wrong Links

### ISSUE THREAD

**Issue by hadmut** [jitsi/jitsi-videobridge#486]
Hi, the README.md contains three links to installation instructions for stable, unstable, nightly, and all three links are not valid (404 - Not Found)

**Comment by iwashi** [comment]
All three links seems alive to me,

- https://download.jitsi.org/stable/
- https://download.jitsi.org/testing/
- https://download.jitsi.org/unstable/

so this issue should be closed.

**Comment by damencho** [comment]
Thanks, yep there was a moment with problems like this while switching to the new site.
