### ISSUE TITLE
Broken link to Performance Evaluation

### ISSUE THREAD

**Issue by fabiodr** [jitsi/jitsi-videobridge#515]
The link [See our performance evaluation](https://jitsi.org/jitsi-videobridge/jitsi-videobridge-performance-evaluation/) in [https://jitsi.org/jitsi-videobridge/](https://jitsi.org/jitsi-videobridge/), **gives a "404 - Not Found" page**.

Has the URL changed? Where can i find basic benchmark or numbers?

Tks

**Comment by bgrozev** [comment]
The link was broken at some point, the new address is here (and I've fixed the link in the project page): https://jitsi.org/jitsi-videobridge-performance-evaluation 

Thanks for the report!

**Comment by fabiodr** [comment]
Thank you for fixing :)
