### ISSUE TITLE
build script for lib/native/* ?

### ISSUE THREAD

**Issue by pjz** [jitsi/jitsi-videobridge#54]
How does one go about building the bits in lib/native/* ?  The source looks to be in the https://github.com/jitsi/libsrc repo, but I don't see any kind of build script there.

I'm looking to get this working on a new arch (armhf, specificially the Beaglebone Black).

**Comment by bgrozev** [comment]
They come from libjitsi: https://github.com/jitsi/libjitsi/tree/master/src/native

Please use the dev@jitsi.org mailing list, and not the github issue tracker for questions.
