### ISSUE TITLE
Can I setup an audio only conferencing through jitsi videobridge?

### ISSUE THREAD

**Issue by PATRONANALYSIS** [jitsi/jitsi-videobridge#540]
Hi,

I need to integrate an audio only conferencing functionality in a live classroom module. Can I achieve this through Jitsi Videobridge? I would only need group audio chat, mic on/off permissions by Class Controller and kick out option. I do not require any other functionality of jitsi meet. Is this possible? Please advice. 

Look forward to your positive reply!

-- Thanks,

**Comment by iwashi** [comment]
This issue is almost a multi-post of https://github.com/jitsi/jitsi-meet/issues/1994 and should be queried to mailing-list.

I think you can achieve what you require, with Jitsi Videobridge (audio only) and your application (like kicking out) which you yourself need to write.

**Comment by PATRONANALYSIS** [comment]
Hi Yoshimasa, thank you for contributing. Sorry for not closing the issues however we are already setting up the group audio chat through Jitsi Videobridge which definitely seem out to be helping. We hope to have the output by next week. 

Thanks again. Closing both the issues now.
