### ISSUE TITLE
Videobridge giving error when trying to start

### ISSUE THREAD

**Issue by pzaver** [jitsi/jitsi-videobridge#544]
I have done the installation using quick guide of jitsi meet. When I try to start video bridge its giving me error
[Error.txt](https://github.com/jitsi/jitsi-videobridge/files/1369508/Error.txt)

SEVERE: conflict, host:localhost, port:5347
org.xmpp.component.ComponentException: conflict

**Comment by damencho** [comment]
This error indicates you have a component already registered in prosody using the same component address. Stop jitsi-videobridge, check at your process whether there is already another jitsi-videobridge process running, stop it or kill it and try again.

**Comment by pzaver** [comment]
How can I stop the videobridge and in the fresh ubuntu installation, I have only installed nginx and then did a quick install of jisti-meet. I have not done a manual installation.

**Comment by damencho** [comment]
Check to see videobridge process:
# ps ax | grep jitsi-videobridge

Stop it
# /etc/init.d/jitsi-videobridge stop
And then check again, you should not see it, if you still see a process kill it.

**Comment by pzaver** [comment]
Thanks a lot - this really helped. Was struggling to resolve this since couple of hours.

**Comment by yoosefi12** [comment]
Hi

I had the same problem, the solution mentioned here did not work for me. I killed the process which was listening to 5222.
# netstat -antpe | grep 5222

and restarted prosody, jicofo and jvb and the problem was solved.
