### ISSUE TITLE
How to test Videobridge

### ISSUE THREAD

**Issue by pzaver** [jitsi/jitsi-videobridge#545]
How can I test the installation and setup of videobridge. Other than running a command to check the status.

root@abc-desktop:/etc/init.d# sudo /etc/init.d/jitsi-videobridge status
sudo: /etc/sudoers.d is world writable
● jitsi-videobridge.service - LSB: Jitsi Videobridge
   Loaded: loaded (/etc/init.d/jitsi-videobridge; generated; vendor preset: enabled)
   **Active: active (running) since Tue 2017-10-10 00:56:08 IST; 4s ago**
     Docs: man:systemd-sysv-generator(8)
  Process: 30277 ExecStop=/etc/init.d/jitsi-videobridge stop (code=exited, status=0/SUCCESS)
  Process: 30718 ExecStart=/etc/init.d/jitsi-videobridge start (code=exited, status=0/SUCCESS)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/jitsi-videobridge.service
           └─30724 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDum...

Oct 10 00:56:08 abc-desktop systemd[1]: Starting LSB: Jitsi Videobridge...
Oct 10 00:56:08 abc-desktop jitsi-videobridge[30718]: Starting jitsi-videobri...
Oct 10 00:56:08 abc-desktop systemd[1]: Started LSB: Jitsi Videobridge.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by damencho** [comment]
With the current jitsi-meet default installation, you need to open 3 tabs in chrome and if you see video it works. If you open two tabs you can be in p2p mode and traffic will not be going through videobridge. This is the manual steps to verify deployment.
For automating stuff, there is jitsi-meet-torture project, that is doing some selenium integration tests to verify deployment.

Note that opening the tabs in the local network as the videobridge it may work, but still joining a conference from a network outside that network may not work because of port forwarding and running jitsi-videobridge behind nat (it needs additional configuration). As described here: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by pzaver** [comment]
But When I try to access localhost:5280/http-bind, its giving me unknown host error 
and 
when I try to access using domain jitsi-meet.example.com/http-bind its giving me can’t find the server at jitsi-meet.example.com

So whats the url to do the testing ?

Sorry I am doing the setup 1st time so not sure.

**Comment by damencho** [comment]
This is the domain name, you entered when installing and was prompted to input it. You need to have a DNS record for that domain name in order people to be able to access it, as regular web service.

**Comment by pzaver** [comment]
I have setup the DNS but as you had mentioned need to open 3 tabs so I am not sure what will be the url of these 3 tabs to do the testing. Can you please guide.
![2017-10-09_16-33-57](https://user-images.githubusercontent.com/32650381/31357451-d00f0f48-ad0f-11e7-905e-95ba80183558.jpg)

**Comment by damencho** [comment]
Try opening this one: https://jitsi-meet.example.com/somename
Or click "Go" on the first one you open and then copy the link and open it two more times.

**Comment by pzaver** [comment]
I opened 3 tab but everytime is switch the tab it again ask for the mic and camera access. For few seconds it shows # of people = 2 and then it gives message - [something went wrong. We are trying to fix it. Reconnecting...]

**Comment by damencho** [comment]
So it seems there is a problem with your deployment. The correct order of debugging is to first check the console logs when opening two windows it should have some error like that jicofo is missing or jvb is missing and when you identify which one, go and check the logs of that component.

**Comment by pzaver** [comment]
Hello For JVB its not able to bind to the port and finally when it tries to bind - its giving already in use error.
For Jicofo I just came accross 1 error - IllegalAccessException.
I didnt find any other error. Also my pc is very slow and I dont have camera with the pc so does that generate this kind of errors?
I am sharing the log files for your review and assistance.

Please guide me.

[jvblog.txt](https://github.com/jitsi/jitsi-videobridge/files/1369967/jvblog.txt)
[jicofolog.txt](https://github.com/jitsi/jitsi-videobridge/files/1369968/jicofolog.txt)

**Comment by damencho** [comment]
Health check failed on: jitsi-videobridge.jitsi-meet.example.com error: timeout
This is the problem. The videobridge didn't reply to a health check so it was removed from the pool of available bridges and you have no bridges and it is normal to see the reconnect screen.
I'm not sure why jvb cannot respond to healthchecks. 
Is there something on your machine that will forbid jvb to allocate ports? I'm wondering why you have all those bind fail messages.
