### ISSUE TITLE
Code on Windows

### ISSUE THREAD

**Issue by pzaver** [jitsi/jitsi-videobridge#548]
Is it possible to setup the code on Windows and run from eclipse ?  Are there any steps available. Can I get any kind of guidance because prosody is only for ubuntu and  same with nginx.

Please advise.

**Comment by damencho** [comment]
You can deploy a working jitsi-meet default deployment on a server. Than stop jitsi-videobridge and configure prosody to listen on all interfaces for component connections(default port is 5347) and configure to run jitsi-videobridge from your dev machine connecting to the deployment one and develop and test that way. This is how the devs are using it and developing it.

**Comment by pzaver** [comment]
Is there any guide or any help available to do the setup since I am doing it for the first time I am new to jitsi and prosody and nginx.

**Comment by pzaver** [comment]
Also I would like to make changes to Jitsi-meet code so is it possible to do on dev (windows) and then run it from dev box?

**Comment by damencho** [comment]
For the install read: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
For modifying jitsi-meet, there are few options but the easiest is:
cd jitsi-meet
WEBPACK_DEV_SERVER_PROXY_TARGET="https://damencho.myserver.com" node_modules/.bin/webpack-dev-server
Then open in the browser https://localhost:8080/
This way every modification in the code will be automatically compiled and the page will be autoreloaded with the new version, and for the serverside components it will use the deployment you have made (in the example it is set to be at address https://damencho.myserver.com).
