### ISSUE TITLE
mentioned code probably does not correspond with rest-colibri.md documentation

### ISSUE THREAD

**Issue by sidorovis** [jitsi/jitsi-videobridge#568]
https://github.com/jitsi/jitsi-videobridge/blob/796bc5b19b00dfbb042403e09d04382ce37ddafe/src/main/java/org/jitsi/videobridge/rest/JSONDeserializer.java#L554

After reading https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-colibri.md, as I understand next Json Node: 
"payload-types": [
            {
              "id": 127,
              "name": "H264",
              "clockrate": 90000,
              "channels": 0,
              "parameters": {
                "rtcp-fb": [
                  "127 ccm fir",
                  "127 nack",
                  "127 nack pli"
                ]
              }
            },

This should become RtcpFbPacketExtension on parsing, but... 
I have dirty fix, but it's better to improve this starting from tech docs / documentation: 
looking at XML based protocol, it requires some structs with fields "type", "subtype" and etc.
(https://xmpp.org/extensions/xep-0293.html:  \<rtcp-fb xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0' type='nack' subtype='sli'/\>)

Otherwise, I maybe there is another possibility to setup nack pli rtcp feedback.

**Comment by bgrozev** [comment]
Hi @sidorovis . Thanks for bringing this up!

I *think* that there's two problems here:
1. The rest-colibri.md doc is just wrong.
2. The JSONDeserializer doesn't support rtcp-fb. 

The format in the doc doesn't make much sense, so I would propose to move rtcp-fb to the payload-type object, and use explicit "type" and "subtype" properties. E.g.:
"payload-types": [
{
"id": 127,
"name": "H264",
"clockrate": 90000,
"channels": 0,
"parameters": {},
"rtcp-fb": [
{type: "ccm", subtype: "fir"},
{type: "nack"},
{type: "nack", subtype: "pli"}
]
}

**Comment by sidorovis** [comment]
changes merged
