### ISSUE TITLE
Updating lastN dynamically

### ISSUE THREAD

**Issue by oliverhausler** [jitsi/jitsi-videobridge#577]
We have a use case for updating lastN dynamically:

Imagine the video room changes in size, e.g. like switching a YouTube video from page to full-screen view, or when the browser is resized. In this case, the number of concurrently displayed remote streams may vary (just because the amount of stream estate varies).

- Would it be easily possible to implement changing `lastN` dynamically, while the stream is running?

What we currently do is end the connection and create a new one, but that's not a good way I guess.

**Comment by gpolitis** [comment]
The JVB already supports this. What does your setup look like? Are you using your own client?

**Comment by oliverhausler** [comment]
We use REST with either browser client or the Android AppRTC client.

**Comment by gpolitis** [comment]
Then you can patch the channel with an updated value for lastN and it should just work.

**Comment by oliverhausler** [comment]
That's cool :) I've been looking for this in SCTP handshaking.

Thank you George, you can close this I think. I'll get back to this in case I have difficulties.
