### ISSUE TITLE
Cannot effectively change front end port from 443

### ISSUE THREAD

**Issue by nbartos** [jitsi/jitsi-videobridge#578]
I have tried to change the gui web port from 443, without success.  Changing org.jitsi.videobridge.rest.jetty.port, org.jitsi.videobridge.rest.jetty.tls.port, and org.jitsi.videobridge.TCP_HARVESTER_PORT in /etc/jitsi/videobridge/sip-communicator.properties to a port other than 443 does change the tcp listeners (using netstat does not report anything bound to :443).

The welcome page does come up correctly on the new port.  Typing in a URL and clicking go brings me to the page asking for camera/microphone as expected.  However, after granting permissions, the page still displays "Jitsi Meet needs to use your microphone and camera.".  Using tcpdump on the jitsi host reveals that some packets are still going from the web browser to the jitsi host on port 443.  Using the Chrome debugger, I see that the "http-bind?room=foo" request seems to be the problem.

I have tested both Chrome and Firefox on Linux.  I am following the installation instructions on https://jitsi.org/downloads/ubuntu-debian-installations-instructions/ to install the full suite.  The jitsi host is running Ubuntu 16.04 server 32-bit.  When the port is put back to 443, it works as expected.  I reboot between the configuration changes, just to make sure everything is restarted correctly.

**Comment by damencho** [comment]
You also need to change the port for the bosh connections, this is in /etc/jitsi/meet/....-config.js, the default for bosh is 443.

**Comment by nbartos** [comment]
Thanks!  Is this documented anywhere?  I couldn't seem to find it.

**Comment by damencho** [comment]
Yep, it is in the config file, configurations that you can find in /etc/jitsi/meet/..config.js has comments above them. Here is the value of the template:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L41

**Comment by nbartos** [comment]
That's a bit obscure.  I think it should be in one of the usual doc files.  How about here?  https://github.com/jitsi/jitsi-videobridge/pull/579
