### ISSUE TITLE
Need a README file

### ISSUE THREAD

**Issue by jensenbox** [jitsi/jitsi-videobridge#59]
Could you include a readme file that explains how it all works? Port numbers, the software involved and how it relates to SIP or XMPP?

**Comment by yanas** [comment]
@jensenbox we don't currently have that one and we agree it's a good idea. A contribution in that direction is more than welcome!

**Comment by bgrozev** [comment]
FIxed in 46026f75e4eb742ed3c8035f38de4889419a70dc
