### ISSUE TITLE
Latest JVB fails on Opera/Firefox

### ISSUE THREAD

**Issue by webintoit** [jitsi/jitsi-videobridge#595]
Hi guys. 
When Firefox connects to conference, it can see video from chrome, chrome cannot see video from firefox (audio works fine).  Similar situation happens with opera -> firefox, firefox -> firefox, opera -> chrome. 
Issue was detected with JVB 1019  and cannot be reproduced with JVB 1013. 
Also it can be reproduced on `https://meet.jit.si`.

**Comment by webintoit** [comment]
Everything  works fine with JVB 1013
:white_check_mark:chrome --> chrome
:white_check_mark:chrome --> firefox
:white_check_mark:chrome  --> opera
:white_check_mark:firefox --> firefox
:white_check_mark:firefox --> opera
:white_check_mark:opera --> opera

JVB 1019 works only: 
:white_check_mark:chrome --> chrome

Firefox: 57.0.4
Chrome: 63.0.3239.132 
Opera: 50.0.2762.58 (PGO)

**Comment by gpolitis** [comment]
This looks like it's signaling related. @bgrozev @bbaldino wasn't there a PR that fixed this last week? @webintoit are you using the latest JVB?

**Comment by webintoit** [comment]
@gpolitis,  jvb 1013 works for me,
latest (1019) fails

**Comment by webintoit** [comment]
You can try it yourself. This bug can be reproduced on  https://meet.jit.si. 
You can also try JVB 1013 deployed here:  https://proficonf.com/

**Comment by bgrozev** [comment]
> Also it can be reproduced on https://meet.jit.si.

Can you please see if it appears on https://beta.meet.jit.si ?

**Comment by bgrozev** [comment]
meet.jit.si is known to have this issue, but it is supposed to be fixed in jvb 1019, and I can not repro it anymore on beta.meet.jit.si which runs 1019 now

**Comment by webintoit** [comment]
It works fine on beta.meet.jit.si. Will look at configuration.  Thanks.
