### ISSUE TITLE
output to an icecast server

### ISSUE THREAD

**Issue by jmcclelland** [jitsi/jitsi-videobridge#60]
I'm not even sure where or how this could be implemented, however, I suspect people would find the feature useful.

The specific use-case I have in mind is a conference panel that involves some people in person and some remote participants - all connecting via the jitsi video bridge. It would be nice if the panel could also be broadcast out to a large audience via icecast (which can be chained and distributed in a way to more easily handle bandwidth and seems more appropriate for passive listeners than having them join the video bridge directly). 

Currently, we can accomplish this by having one participant stream their desktop to icecast. However, that requires an experienced techie to manage.

Perhaps the video send to icecast could be the video of the currently talking person? 

Is the video bridge the right place to implement this? Or should it be implemented in the jitsi client or jit-meet?

Thanks for all your work on jitsi video bridge.

**Comment by stpeter** [comment]
Why not chain together JVB instances? I'm sure the bridge could scale up pretty well (but then I'm not sure what size you mean "large" audiences).

**Comment by jmcclelland** [comment]
I never thought of that - how do you chain together JVB bridges?

One of the advantages of icecast is that we have a lot of allies that are already running icecast, so building an icecast network is relatively easy compared to convincing them to install anew piece of software.

**Comment by stpeter** [comment]
Well if you're already embedded in the icecast community then what you're doing makes sense. Chaining together JVBs is an intriguing idea to me, but it might not be of general interest. I'd be curious to see what the Jitsi team thinks of it, though...

**Comment by yanas** [comment]
Sounds like an interesting idea. This is not currently on our roadmap, but a contribution will be more than welcome. If you're ready to work on that feel free to reopen the issue with maybe a first patch :)
