### ISSUE TITLE
What happened to RTCP termination strategies?

### ISSUE THREAD

**Issue by nojz** [jitsi/jitsi-videobridge#601]
After upgrading from 879 to 953 stable build I realized that RTCP termination strategies are gone. I have an own implementation that I used (it was set in the sip-communicator.properties) but it does not work anymore.
As the [documentation](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rtcp-termination.md) seems kinda outdated (and it is noted as well), could you tell me what happened and how I should adapt to these new changes?

**Comment by gpolitis** [comment]
Hi @nojz, there's been a rewrite of significant parts of the bridge about a year ago and the pluggable RTCP termination strategies architecture got removed. If the current implementation doesn't suite your needs, you can either patch the code to replace the current implementation with your own or propose a new pluggable RTCP termination architecture that's compatible with the new code.

**Comment by nojz** [comment]
Okay, I got it, thanks for the quick reply @gpolitis!
