### ISSUE TITLE
LipSyncHack is executed twice?

### ISSUE THREAD

**Issue by veljkopopovic-symphony** [jitsi/jitsi-videobridge#625]
In both VideoChannel (rtpTranslatorWillWrite method)  and RtpChannelTransformEngine (added to transformerList) ?

**Comment by bgrozev** [comment]
These are different: VideoChannel calls `LipSyncHack.onRTPTranslatorWillWriteVideo`, while the addition to the transformer list results in the `transform` and `reverseTransform` methods in `LipSyncHack.RTPTransformer` and `LipSyncHack.RTCPTransformer` to be called.

**Comment by veljkopopovic-symphony** [comment]
Sorry, my bad ... One of our old forks contains comment that hack should be moved to transform ... And when I saw that method call was not removed from VideoChannel but was introduced in transformations I have assumed that it might be a mistake ... Didn't dig any deeper ... Thanks for your time :D
