### ISSUE TITLE
More about load balance

### ISSUE THREAD

**Issue by soq2000** [jitsi/jitsi-videobridge#662]
Hi all,
It is an extension of the issue  [https://github.com/jitsi/jitsi-videobridge/issues/659](#659)
Thank you Damencho for your answer. I can see from the code that you have 2 two classes to select video bridges, namely SplitBridgeSelectionStrategy and SingleBridgeSelectionStrategy. The former chooses a bridge candidate randomly while the latter selects the first one. I miss the class implementing what you said : send new conferences to the least loaded bridge. Would you please tell me the name of the class doing that strategy.
Another thing interesting is that ' if we reach some network threshold a new bridge is created and added to the pool of existing bridges so it can take the load'. Would you please tell me where I can find the implementation of such mechanism.

Many thanks

**Comment by damencho** [comment]
The SingleBridgeSelectionStrategy chooses the first one from the sorted list of bridges (https://github.com/jitsi/jicofo/blob/4dda81cb97909d3e430fbec4fa67ef84e8a1f68e/src/main/java/org/jitsi/jicofo/BridgeSelector.java#L345) and it is sorted by video streams count (https://github.com/jitsi/jicofo/blob/4dda81cb97909d3e430fbec4fa67ef84e8a1f68e/src/main/java/org/jitsi/jicofo/Bridge.java#L276).
The auto-scaling mechanism is a standard auto-scaling option in aws, you can check it there in aws console.
