### ISSUE TITLE
Hardware crypto

### ISSUE THREAD

**Issue by paulkon** [jitsi/jitsi-videobridge#67]
Does the videobridge use hardware crypto libraries and if not is it possible to plug-in? Thanks.

**Comment by lyubomir** [comment]
Hardware AES is used if available and supported by the JRE (i.e. 1.8).

**Comment by paulkon** [comment]
So, comparing between E3-1240v2 (AVX) and E3-1240v3 (AVX 2.0), the v3 model
will provide visible performance improvements?

thanks!
