### ISSUE TITLE
jitsi-videobridge - last client sees no other streams

### ISSUE THREAD

**Issue by dixoncb** [jitsi/jitsi-videobridge#671]
We have a UWP client running on devices including HoloLens, using jitsi-videobridge via XMPP messaging. It runs well when it runs, but we have a reproducible issue that stops three clients, say, conferencing together. The sequence is:

A and B receive a session-initiate together as the first clients. They then receive a source-add containing their mutual sources. Media flows from B to A only. C joins. A and B receive the source-add, and now media flows between A and B, and from C - to A and B - but no media flows to C. 

The SDPs and Jingles involved - those which trigger media flow and those which don't - appear to be identical save for local ids. 

We're filtering out the "mixed" audio and video sources, owned by jvb, and we're running with trickle ICE and pranswer enabled.  We're fairly sure there are no threading issues involved. Maybe we're missing some XMPP handshakes with jitsi-videobridge?

**Comment by gpolitis** [comment]
@dixoncb the mixed sources, especially the one for video, are necessary for FIR termination and other things. Try that out and let us know how it goes and we'll try to help you solve any remaining issues.

**Comment by gpolitis** [comment]
@dixoncb is this still an issue in your use case?

**Comment by dixoncb** [comment]
Hello George

 

Thanks for the response. We figured out the issue over the weekend, which was to do with the fact we were trying to start with the last added client muted, then waiting for a source-add Jingle to change the client media SDP entries from inactive to sendrecv. We now know with can fix it by starting with all clients unmuted. So that part of it we seem to have solved.

 

This introduces a second problem, however. Our use case is that we select which webcams are broadcast to other clients using our own proprietary signalling. We really therefore do need to start with clients muted, because we don’t want to incur any excess bandwidth usage. We’d use our signalling to mute and unmute remotely. Ideally we’d just be able to tell jitsi videobridge in our session-accept that the local source exists, but it’s muted: and then we’d be able to turn it on or off using WebRTC’s PeerConnection::AddStream/RemoveStream. This doesn’t work though. At the moment we’re doing a lot of Googling and coding up some experiments. It would be good to get some guidance on the best way of achieving this result.

 

Just to clarify, when I say we are filtering out the mixedmedia sources – we are not removing these from the SDPs, or our session-accept Jingles, we’re just ignoring them as far as our local UI is concerned. 

 

Colin Dixon

Illustra Limited

**Comment by iwashi** [comment]
@dixoncb 
Hi, we're seeing the almost same issue described here; when the client joins the conference with muted audio and active video, then the other clients in the conference can't observe the video stream which should be sent by the client with muted audio.

You closed this issue but did you find the solution to this issue? If so, could you share it?
