### ISSUE TITLE
REST-API Timeout for PATCH in build 445

### ISSUE THREAD

**Issue by peili** [jitsi/jitsi-videobridge#69]
PATCH Method for HTTP gives a Timeout

**Comment by peili** [comment]
It's an issue related to ice4j, if you pass a dtls fingerprint to the HttpDemuxFilter it won't accept it because it doesn't support "PATCH". 
see:
https://github.com/opentelecoms-org/ice4j/blob/6234678fce94617436b315efe4abf17b21da17c8/src/org/ice4j/socket/HttpDemuxFilter.java#L51

**Comment by bgrozev** [comment]
Thanks, @peili ! I just added PATCH in ice4j (the jar is not yet updated in jitsi-videobridge).
