### ISSUE TITLE
How to deploy jitsi cluster to support 1 to many broadcast?

### ISSUE THREAD

**Issue by tomnotcat** [jitsi/jitsi-videobridge#690]
I'm looking for a webrtc server to support 1 to 10K users broadcast in a single live stream.
For that scale, a single server is not possible, So I need to deplay a cluster to broadcast the stream.
Does jitsi-videobridge support cluster deployment?

**Comment by saghul** [comment]
Not for that kind of scale yet. For that kind of broadcasting you'd be better off using jibri. Jibri is our broadcasting component, which at the moment is able to stream a conference to YouTube. In case you need to broadcast to another service / your own RTMP server some changes might be required, but those would be minimal.

I hope that helps.

**Comment by havid0707** [comment]
@saghul jvb cluster can solve this probleam? I want to know users in the same conference can connect to different jvbs in this case? or conference can only rely on one jvb?

**Comment by saghul** [comment]
I think with Octo this would be possible (@bgrozev can you confirm?). But still, streming the conference to an RTMP server makes more sense in this scenario IMHO.

**Comment by saghul** [comment]
At any rate, this is a topic better suited for our community: https://community.jitsi.org/ Please feel free to post there.

**Comment by damencho** [comment]
By default all participants in a conference are using the same jvb. In order to distribute you need https://github.com/jitsi/jitsi-videobridge/blob/master/doc/octo.md

**Comment by havid0707** [comment]
Thanks a lot

**Comment by havid0707** [comment]
@damencho I have read the link you provided.
So, I need to implement these two guide together, Right?
https://github.com/jitsi/jicofo/blob/master/doc/load_balancing.md
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/octo.md

because I have some confusion，the OCTO guide just lists the interfaces for communication between jvbs. How can jicofo know that there are other jvbs?

**Comment by webintoit** [comment]
@havid0707, there is a few mechanisms that makes it able to discover bridges for jicofo. 
When your bridges connected to same xmpp server, jicofo will poll each of them via xmpp component discovery. There is `pub/sub` mechanism also available. Each videobridge will send own stats to shared statistic pubsub node. jicofo will collect all the stats. 
So, it is the first step, jicofo knows about all available bridges. 
Second step is the bridge selection strategy. You can implement your own, but Borya made few useful and applicable strategies for your choice. 
When the participant will ask jicofo about conference allocation, jicofo will choose proper bridge / bridges depending on selection strategy. For example, you can implement strategy that will select closest to user  bridge that have less than 3 audio streams with lowest cpu consumption, you can play with it. 

OCTO thing is very useful for 1 to many scenario.

**Comment by havid0707** [comment]
@webintoit  Thanks for your reply. I want to balancing participants in one conference to jvbs.
 so my question asked below is Yes?
![image](https://user-images.githubusercontent.com/9440277/49795543-36f7a380-fd75-11e8-9156-527a5eeba406.png)

**Comment by webintoit** [comment]
> @webintoit Thanks for your reply. I want to balancing participants in one conference to jvbs.
> so my question asked below is Yes?
> ![image](https://user-images.githubusercontent.com/9440277/49795543-36f7a380-fd75-11e8-9156-527a5eeba406.png)

yes
