### ISSUE TITLE
Jvb class not found errors

### ISSUE THREAD

**Issue by lilei-1** [jitsi/jitsi-videobridge#695]
The same with #661 .

I have the same errors when I run latest released jvb(https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x64-1074.zip) and run the command in the manual install guide. jvb.sh shows the same errors.

Jicofo has the same behavior.

**Comment by damencho** [comment]
Works for me. I did:
```
unzip jitsi-videobridge-linux-x64-1074.zip
cd jitsi-videobridge-linux-x64-1074
./jvb.sh --host=xmpp_host--domain=my-domain --port=5347 --secret=jvb_secret
```

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.
