### ISSUE TITLE
REST/XMPP interface parity

### ISSUE THREAD

**Issue by paulkon** [jitsi/jitsi-videobridge#70]
In reference to http://lists.jitsi.org/pipermail/dev/2015-May/024203.html, like Mihail, I was wondering when we might see REST patches to bring it up to speed with the XMPP interface.

Thanks so much!

**Comment by paweldomas** [comment]
Hi,

This should not be very complicated, but we do not have resources to do it now. What about small contribution ? Sources related to JSON serialization/deserialization can be found here:

https://github.com/jitsi/jitsi-videobridge/tree/master/src/org/jitsi/videobridge/rest

Most important classes:

https://github.com/jitsi/jitsi-videobridge/blob/master/src/org/jitsi/videobridge/rest/JSONDeserializer.java
https://github.com/jitsi/jitsi-videobridge/blob/master/src/org/jitsi/videobridge/rest/JSONSerializer.java

Regards,
Pawel

**Comment by yanas** [comment]
This seems like a broad subject, so please create tickets for specific features you want to see.
