### ISSUE TITLE
Exception in ice4j when starting videobridge, because unable to create thread

### ISSUE THREAD

**Issue by pag-siweb** [jitsi/jitsi-videobridge#729]
When I try to start the jitsi-videobridge task (`systemctl start jitsi-videobridge`), systemctl returns me an error.
I have tried to inspect some logs (journalctl -xn, /var/logs/jitsi/jvb.log) and those are the errors I get :

[Result of journalctl -xn](https://github.com/jitsi/jitsi-videobridge/files/2663501/error.txt)
[Content of jvb.log](https://github.com/jitsi/jitsi-videobridge/files/2663500/jvb.log)

How can I get more information on what is going wrong ?

I haven't found anything on this except [this](https://community.jitsi.org/t/jitsi-dev-socket-listener-implementation-ice4j/3421/2), but that's 7 years old.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening an issue.

> java.lang.OutOfMemoryError: unable to create new native thread
What is the available memory on the machine? Are you running and jicofo on the same machine?
