### ISSUE TITLE
Question:building on Arch Linux

### ISSUE THREAD

**Issue by nobicycle** [jitsi/jitsi-videobridge#738]
Hello and thank you for jitsi-videobridge software.

I have a working Prosody server on Arch that I can connect to with Pidgin (see screenshot below)

> $ systemctl status prosody
> ● prosody.service - XMPP (Jabber) Server
>    Loaded: loaded (/usr/lib/systemd/system/prosody.service; disabled; vendor preset: disabled)
>    Active: active (running) since Mon 2019-01-07 11:22:50 WITA; 5min ago
>   Process: 14210 ExecStart=/usr/bin/prosodyctl start (code=exited, status=0/SUCCESS)
>  Main PID: 14213 (lua5.2)
>     Tasks: 1 (limit: 4915)
>    Memory: 10.9M
>    CGroup: /system.slice/prosody.service
>            └─14213 lua5.2 /usr/lib/prosody/../../bin/prosody
> 
> Jan 07 11:22:50 tower systemd[1]: Starting XMPP (Jabber) Server...
> Jan 07 11:22:50 tower prosody[14211]: mod_posix: Prosody is about to detach from the console, disabling further console output
> Jan 07 11:22:50 tower prosody[14213]: mod_posix: Successfully daemonized to PID 14213
> Jan 07 11:22:50 tower prosodyctl[14210]: Started
> Jan 07 11:22:50 tower systemd[1]: Started XMPP (Jabber) Server.
> Jan 07 11:22:50 tower prosody[14213]: modulemanager: pep is already loaded for prosody.localdomain, so not loading again
> 

Jitsi-videobriidge master is extracted here: /mnt/HD02-1T/archives/Office/Communications/Jitsi/jitsi-videobridge-master/"

From inside this directory I run the commands 

```
HOST="prosody.localdomain" 
DOMAIN="jitsibridge.prosody.localdomain" 
PORT="5437" SECRET="password" 
JVB_HOME="/mnt/HD02-1T/archives/Office/Communications/Jitsi/jitsi-videobridge-master/"
		
mvn compile exec:exec -Dexec.executable=java -Dexec.args="-cp %classpath org.jitsi.videobridge.Main --domain=\"${DOMAIN}\" --host=\"${HOST}\" --port=\"${PORT}\" --secret=\"${SECRET}\" -Djava.library.path=$JVB_HOME/lib/native/linux-64 -Djava.util.logging.config.file=$JVB_HOME/lib/logging.properties -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=.jitsi-videobridge "

```

But I get the error 

> SEVERE: java.net.ConnectException: Connection refused (Connection refused), host:prosody.localdomain, port:5437
> org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)
> 	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)
> 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
> 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
> 	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:315)
> 	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:300)
> 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:174)
> 	... 12 more
> 

> $ tail -7  /etc/prosody/prosody.cfg.lua 
> Component "jitsibridge.prosody.localdomain"
> 	component_secret = "password"
> 
> 

This is all running on localhost

> $ tail -2  /etc/hosts
> 192.168.1.100	prosody.localdomain
> 192.168.1.100	jitsibridge.prosody.localdomain
> 

Please advise.

![screenshot_2019-01-07_11-35-59](https://user-images.githubusercontent.com/1372447/50747713-5e586800-1270-11e9-80c9-71a488eee8b3.png)

**Comment by damencho** [comment]
Pidgin is using the client xmpp port 5222 which is different from what videobridge uses. Videobridge connects as a component and uses port 5347. 
>  Connection refused (Connection refused), host:prosody.localdomain, port:5437
By default, prosody listens on localhost on that port. 
Try changing `HOST="prosody.localdomain" ` to be localhost if you are running jvb on the same machine or make sure prosody listens interface with address `prosody.localdomain`.
You can control that using `component_interface `, more information: https://prosody.im/doc/components

Please use the community forum for problems or questions before opening issues.
