### ISSUE TITLE
Queries regarding the setup of videobridge

### ISSUE THREAD

**Issue by kshitij199319** [jitsi/jitsi-videobridge#744]
I have few queries regarding the jitsi meet and videobridge setup
1. Can we run jitsi meet  with Java 7 version?
2. I have a cantOS machine, so can I setup a videobridge server on centOs machine and is it recommended?
3. Is it possible to integrate jitsi videobridge with the signaling server setup that I already have or I have to setup independently jicofo and prosody and create a signalling setup to run a multiparty conference call?
4. Can I create a custom UI with the help of jitsi meet library?

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening issues.

> Can we run jitsi meet with Java 7 version?

Why would you do that? No, you cannot use java7. We switched most of the project to support as minimum java8. Even before switching, java8 was preferred cause we can use some optimizations on the ssl side.

> I have a cantOS machine, so can I setup a videobridge server on centOs machine and is it recommended?

Every OS that can run java will be able to run the bridge, but if it is not linux based you maybe will need to recompile native dependencies.
Anyway, I will suggest to you to install on Debian/Ubuntu system using the quick install method. So when you have a working solution then you can try installing it on your other OS, but mind that the process involves a lot of configuration and people are always missing some steps or not doing some stuff right, that's one of the reasons the manual setup doc to have a warning to not use it.

> Is it possible to integrate jitsi videobridge with the signaling server setup that I already have or I have to setup independently jicofo and prosody and create a signalling setup to run a multiparty conference call?

I doubt that your signaling has implemented all the stuff that jicofo is doing and the same protocols. I doubt jicofo is replacable. On the other hand, prosody can be replaced with another xmpp, with losing the option to reuse any of the modules we had provided for prosody that works with jitsi-meet. But my recommendation is to stick to the recommended way, so you will have a system that is easy to upgrade and separate from any other external services you have, so you can easily switch between versions...

> Can I create a custom UI with the help of jitsi meet library?

Here the recommended way of doing things is to use the iframe API and embed the video experience where you want. You can override some interface options on the server config or through the iframe API. In the current UI had been invested and we continue to invest a lot of work. If something is not configurable or not suiting your needs, you can always purpose it and create a PR to be added to the project. But if you go the path of building custom UI, you need to use the low-level lib-jitsi-meet, implement many things already existing in jitsi-meet and invest many people and hours of building that, while jitsi-meet will continue to evolve ...
