### ISSUE TITLE
Is it possible for users to have different channelLastN value when using Adaptive Last N?

### ISSUE THREAD

**Issue by brandonecraig** [jitsi/jitsi-videobridge#76]
I have tried giving each client a different channelLastN value in the config but it doesn't seem like it is working correctly. All users have adaptiveLastN set to true.

**Comment by bgrozev** [comment]
Currently the channelLastN value is global for the whole conference. Giving a different value to different clients will not have any affect.

AdaptiveLastN is also global. Once you enable it for a conference all users' lastN value will be managed by the bridge (and will not exceed channelLastN).

**Comment by emcho** [comment]
Possibly worth mentioning that it is actually possible to set different values in the bridge through colibri.

It should also be relatively straightforward to make clients request a specific N value through data channels. A patch would be welcome.
