### ISSUE TITLE
JVB is not forwarding video to\from channels where offerer is Browser.

### ISSUE THREAD

**Issue by sarumjanuch** [jitsi/jitsi-videobridge#783]
## Description
There is an issue, that when you want a browser to be an initiator, JVB will simply ignore video forwarding to\from such channel. Audio is working, but I am using mixing, so that might be a reason why audio part works, or be a reason why the video does not work. First, I was thinking that it is due to lack of RTX or simulcast, i have implemented signaling for RTX and simulcast on my clients and focus, using jitsi-meet as a reference, but that have not changed anything. Moreover, if I add participants only with initiator = true, everything seems to work fine. I believe I met all the requirements.
1) I munge SDP to create simulcast ssrc's.
2) All that SSRS's are signaled to JVB. 
3) The source ssrc of the bridge is signaled back to the client with mixed label (as in jitsi-meet), 
4) Other participants sources are signaled to each other (main source group from simulcast triplet from each party).
## Current behavior
I see that the browser is sending video and receiving a lot of PLI's and some NACK... But I don't see it receiving anything except audio stream. No one is able to send or receive video form such participant.
## Expected Behavior
Obviously, this either have to work, or initiator option has to be removed, and forced to true. It is a very good feature to dial in into conference and not only being dialed. Such feature provides and ability to transparently integrate with existing signalling protocols, like sip or Jingle.
## Possible Solution
I have no clue, the complexity of this project already does not let me look into the code to search for a solution.
## Steps to reproduce
Create a conference where one prat. will be initiator and the other will not. Basically, one dial in and the other is dialed.
# Environment details
Centos 6. 
Latest JVB: https://download.jitsi.org/jitsi-videobridge/linux/jitsi-videobridge-linux-x64-1109.zip from this archive.
Two latest chrome browsers on Windows 10.

There were a few times when the video suddenly started to being forwarded from such participant, but that was always like after 10-15 minutes, after call establishment, while I was digging in wbrtc-internals, without any actions from my side, and I have never seen it is forwarded to such participant.  Maybe I am missing some special option? Maybe this is because of mixed audio stream? I have not yet implemented an SCTP connection, but maybe this somehow can be a reason? I really have tried all and everything. I spent last week to make our signaling to be identical to the one in jitsi-meet, with two exceptions, I have cases when initiator=false, and we are using mixing for audio. RTX and Simulcast are on. Only VP8 is signaled by the bridge. Any advice would be amazing. I already have no options left, mimicking signalling as in jitsi-meet was my last resort. I can provide you with any information, traces, or even server access, just let me know what you need.

**Comment by bgrozev** [comment]
If I remember correctly the 'initiator' flag in colibri is only used to determine the ICE role that the bridge will use (controlled or controlling). It shouldn't prevent you from using different flows on a higher level. 

It is surprising that audio works, but video doesn't. If you are using bundle (you said you mimic the signaling in jitsi-meet so you should be), then ICE and DTLS must have completed successfully, so the 'initiator' flag is no longer relevant.

When you say that video is not forwarded does that mean that no packets arebeing sent to clients, or that clients don't render a video? It could very well be due to the missing data channel, especially if simulcast is enabled. I don't see how mixing audio could trigger this, but we haven't used it in a long time (and it's getting deprecated), so issues might have crept in.

**Comment by sarumjanuch** [comment]
Hi Boris, I was digging yesterday all over the places and can confirm that initiator is not used anywhere except for the ICE establishment process. Yes we use channel bundle, and yes ICE is fine, I always see iceconnectionstatechange= connected. It would be more correct to say now, that video is not forwarded when Browser is initial offerer. I see traffic from browsers towards JVB, but JVB does not forward what it receives. I am also very suspicious about data channels, but if JVB is initial offerer, everything works just perfectly fine without data channels and with mixed audio. Also good to know that audio mixing will be removed.

**Comment by sarumjanuch** [comment]
Also i see a lot of:

```
JVB 2019-03-20 12:06:23.585 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.585 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.586 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:2678388090
JVB 2019-03-20 12:06:23.586 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:2678388090
JVB 2019-03-20 12:06:23.590 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.590 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.595 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.595 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.602 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.603 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.609 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:3643726411
JVB 2019-03-20 12:06:23.609 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:2678388090
JVB 2019-03-20 12:06:23.612 WARNING: [3304] org.jitsi.videobridge.cc.AdaptiveTrackProjection.log() Dropping an RTP packet, because the SSRC has not been signaled:2678388090
```

Despite:

```
{
  "contents": [
    {
      "channels": [
        {
          "endpoint": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/100",
          "channel-bundle-id": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/100",
          "sources": [
            2426093545
          ],
          "rtp-level-relay-type": "mixer",
          "expire": 60,
          "initiator": false,
          "ssrcs": [
            926710724
          ],
          "id": "ac60dcade93fbfaf",
          "direction": "sendrecv"
        },
        {
          "endpoint": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/300",
          "channel-bundle-id": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/300",
          "sources": [
            4289556127
          ],
          "rtp-level-relay-type": "mixer",
          "expire": 60,
          "initiator": true,
          "ssrcs": [
            2759336355
          ],
          "id": "42373ccb9e7982ae",
          "direction": "sendrecv"
        }
      ],
      "name": "audio"
    },
    {
      "channels": [
        {
          "endpoint": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/300",
          "channel-bundle-id": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/300",
          "sources": [
            598724983
          ],
          "rtp-level-relay-type": "translator",
          "expire": 60,
          "initiator": true,
          "ssrcs": [
            70137055,
            1,
            625494907,
            3643726411,
            3303754339,
            446330386,
            3609129364
          ],
          "id": "8819bc31dd4e9e87",
          "receive-simulcast-layer": null,
          "direction": "sendrecv",
          "last-n": -1
        },
        {
          "endpoint": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/100",
          "channel-bundle-id": "432007cc-e2f0-4b46-8f39-b8186ccb4a05@muc.single.local/100",
          "sources": [
            598724983
          ],
          "rtp-level-relay-type": "translator",
          "expire": 60,
          "initiator": false,
          "ssrcs": [
            1,
            2702655748,
            1716910769,
            1717605785,
            2678388090,
            3472908047,
            4151315039
          ],
          "id": "9968e113350e0c4f",
          "receive-simulcast-layer": null,
          "direction": "sendrecv",
          "last-n": -1
        }
      ],
      "name": "video"
    }
  ],
  "id": "13a5a56f6a8eec"
}
```

**Comment by sarumjanuch** [comment]
Ok, the issue was in chrome offer. It has to be very clean, and payload ids must match ids, that will be in the answer from JVB, I didn't noticed that. Now works. Thank You!
