### ISSUE TITLE
How to make jvb run simultaneously on an 8-core CPU

### ISSUE THREAD

**Issue by zlwlogo** [jitsi/jitsi-videobridge#820]
I am running jitis-kit on ubuntu server 18.04. The desktop stream input by the client is relatively large and is CPU-intensive. I observed that jvb only runs in one core of the CPU. If you need to make an 6-core CPU run jvb, how to improve.

Now I use the i5-8400 CPU, which can support 30 client broadcasts when one core of the CPU is fully loaded. If large-scale broadcasts are required, it is necessary to use other cores to calculate and output desktop streams.

**Comment by damencho** [comment]
Please use the community forum for questions and problems before opening new issues.

I just checked one of the loaded bridges on meet.jit.is and it is definitely using all cores.
How are you running the bridge? How are you checking that it uses only one core?

**Comment by zlwlogo** [comment]
Thank you for your answer. I didn't find the answer in the previous issues.
I use jvb to install it according to the installation guide on the official website.
On how to determine that only one kernel is running, use the top command to view the CPU usage. The details are as follows.
![image](https://user-images.githubusercontent.com/30715115/56804069-15e0ac80-6857-11e9-9900-8bc86c7b1a35.png)

**Comment by damencho** [comment]
Click '1' in top and you will see that percentage distributed between the cores.
