### ISSUE TITLE
Unable to download server program

### ISSUE THREAD

**Issue by echooooooo** [jitsi/jitsi-videobridge#831]
Unable to download server program from  https://download.jitsi.org/stable/

## Description
---Not downloadable since yesterday

## Current behavior
---Not downloadable

## Expected Behavior
---downloadable

**Comment by damencho** [comment]
This is known and we are working on fixing it, will let you know as soon as it is resolved.

**Comment by damencho** [comment]
All issues had been fixed and download.jitsi.org is back.
