### ISSUE TITLE
videobridge seems to ignore "a=sendonly" in sdp

### ISSUE THREAD

**Issue by Paultok** [jitsi/jitsi-videobridge#84]
Is there any way to make the videobridge honor the standard sdp 'a=sendonly' direction? I am interested in sending video /audio only and don't want to receive any media stream from the videobridge.

**Comment by bgrozev** [comment]
Videobridge does not deal with SDP. The [COLIBRI](http://xmpp.org/extensions/xep-0340.html) "channel" elements have a "direction" attribute which AFAIK is handled by videobridge.
