### ISSUE TITLE
Does not record video and sound

### ISSUE THREAD

**Issue by sergioloyola** [jitsi/jitsi-videobridge#940]
W
[prosody.log](https://github.com/jitsi/jitsi-videobridge/files/3741282/prosody.log)
[jvb.log](https://github.com/jitsi/jitsi-videobridge/files/3741283/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-videobridge/files/3741284/jicofo.log)

hen I try to record a confederation, the recording of it becomes active, but when I finish recording. I see the generated video has only black screen with the jitsi logo

**Comment by bbaldino** [comment]
Do you mean audio and video are not forwarded? Or are you actually trying to do a recording of a meeting?  Is this a recording using Jibri?

**Comment by sergioloyola** [comment]
I am trying to record a meeting with jibri, but once the recording is finished, when I go to see the video I have the image attached
![Jitsi-screen](https://user-images.githubusercontent.com/25505920/67050712-93eb8500-f10f-11e9-876b-e207021c72dc.png)

**Comment by bbaldino** [comment]
I assume the other participants in the call are seeing and hearing eachother fine?  Can you attach Jibri logs

**Comment by sergioloyola** [comment]
Yes, the participants look and listen well.
[LOG.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744605/LOG.0.txt)
[FFMPEG.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744606/FFMPEG.0.txt)
[BROWSER.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744607/BROWSER.0.txt)

**Comment by bbaldino** [comment]
In those logs it looks like Jibri isn't in the call for very long.  It joins the call at about `18:07:42`, at `18:07:57` it checks the media it's receiving and it says that all clients in the call are muted (so it won't be receiving anything), at `18:08:12` it still looks like all other clients are still muted, and at `18:08:15` it gets told to stop.

**Comment by sergioloyola** [comment]
When you are in a conference between 2 and the moderator starts recording the other person does not get more video and sound. In this case the recording stopped alone.
[LOG.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744968/LOG.0.txt)
[FFMPEG.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744969/FFMPEG.0.txt)
[BROWSER.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3744971/BROWSER.0.txt)

**Comment by damencho** [comment]
Try opening 3 tabs, you will not get video. Recording may be fine, it is your deployment that is not fully configured. The recorder is like normal client, if you don't get video with 3 participants there will be no video and for the recorder.
Two people are in p2p mode, adding a third one you get to the bridge and the clients cannot send data to the bridge because of firewall or port forwarding or wrong private/public address.
https://jitsi.org/qi#advanced-configuration

**Comment by sergioloyola** [comment]
listo
