### ISSUE TITLE
Jibri Record Problem

### ISSUE THREAD

**Issue by sergioloyola** [jitsi/jitsi-videobridge#943]
Good afternoon, I have problems with the recording. It starts and after a while the recording stops by itself. What you record before it stops is saved. Then I put an extract of the log:
DETALLADO: [47] org.jitsi.jibri.util.ProcessStatePublisher.ffmpeg.invoke() Process ffmpeg hasn't written in 2 seconds, publishing periodic update
2019-10-21 14:05:18.622 DETALLADO: [47] org.jitsi.jibri.util.ProcessStatePublisher.ffmpeg.invoke() Process ffmpeg hasn't written in 2 seconds, publishing periodic update
2019-10-21 14:05:23.441 DETALLADO: [47] org.jitsi.jibri.util.ProcessStatePublisher.ffmpeg.invoke() Process ffmpeg hasn't written in 2 seconds, publishing periodic update
2019-10-21 14:06:17.912 GRAVE: [47] org.jitsi.jibri.selenium.JibriSelenium.invoke() Error while running call status checks: org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
(Session info: chrome=77.0.3865.120)
(Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Linux 4.4.0-165-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'grabador', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-165-generic', java.version: '1.8.0_222'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 77.0.3865.40 (f484704e052e0..., userDataDir: /tmp/.com.google.Chrome.N60ulY}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:34514}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 77.0.3865.120, webStorageEnabled: true}
Session ID: 40089b6a157ffd42822f53abb366329c with stack: 
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
org.jitsi.jibri.selenium.pageobjects.CallPage.getNumParticipants(CallPage.kt:71)
org.jitsi.jibri.selenium.status_checks.EmptyCallStatusCheck.run(EmptyCallStatusCheck.kt:14)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:194)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:105)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:294)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:105)
org.jitsi.jibri.util.extensions.SchedulerExecutorServiceExtsKt$sam$java_lang_Runnable$0.run(SchedulerExecutorServiceExts.kt)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2019-10-21 14:06:18.171 INFORMACIÓN: [55] org.jitsi.jibri.selenium.JibriSelenium.onSeleniumStateChange() Transitioning from state Running to Error: SESSION Chrome hung
2019-10-21 14:06:18.185 INFORMACIÓN: [55] org.jitsi.jibri.service.impl.FileRecordingJibriService.onServiceStateChange() File recording service transitioning from state Running to Error: SESSION Chrome hung
2019-10-21 14:06:18.189 GRAVE: [47] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55fa46956959 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap

**Comment by bbaldino** [comment]
Can you include the entire log?

**Comment by sergioloyola** [comment]
Ok, I attach the complete log.
[log.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752121/log.0.txt)

**Comment by bbaldino** [comment]
Can you include the browser and ffmpeg logs as well?

**Comment by sergioloyola** [comment]
ok, i attach the logs
[ffmpeg.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752161/ffmpeg.0.txt)
[browser.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752162/browser.0.txt)

**Comment by bbaldino** [comment]
Hm, are there no other browser logs?  Not much to go on there, looks like.  Maybe the crash interfered with our ability to grab the logs.  Is this a custom jitsi meet deployment?  We haven't seen this tab crash before.  Is this with Jibri in docker or a VM or  something?  Maybe it's a resource problem?  Can only speculate at this point.

**Comment by sergioloyola** [comment]
The jitsi is installed in a VM and the jibri is installed in another VM, both VMs have Ubuntu 16.04.4 LTS with 4 GB of RAM and 4 cores. I attached the other logs that I have
[log.3.txt](https://github.com/jitsi/jitsi-videobridge/files/3752305/log.3.txt)
[log.2.txt](https://github.com/jitsi/jitsi-videobridge/files/3752306/log.2.txt)
[log.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3752307/log.1.txt)
[log.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752308/log.0.txt)
[ffmpeg.3.txt](https://github.com/jitsi/jitsi-videobridge/files/3752309/ffmpeg.3.txt)
[ffmpeg.2.txt](https://github.com/jitsi/jitsi-videobridge/files/3752310/ffmpeg.2.txt)
[ffmpeg.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3752311/ffmpeg.1.txt)
[ffmpeg.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752312/ffmpeg.0.txt)
[browser.3.txt](https://github.com/jitsi/jitsi-videobridge/files/3752313/browser.3.txt)
[browser.2.txt](https://github.com/jitsi/jitsi-videobridge/files/3752314/browser.2.txt)
[browser.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3752315/browser.1.txt)
[browser.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3752316/browser.0.txt)

**Comment by bbaldino** [comment]
Have you tried testing Jibri on another machine (non VM) to see if it reproduces there?

**Comment by sergioloyola** [comment]
I try and let you know. Thank you

**Comment by sergioloyola** [comment]
@bbaldino install the jibri on a physical machine with buntu 16.04.4 LTS with 4 GB of RAM and 4 cores. Now I record video without problem, but the sound is not haunting me. I pass you the logs.
[log.7.txt](https://github.com/jitsi/jitsi-videobridge/files/3755149/log.7.txt)
[log.6.txt](https://github.com/jitsi/jitsi-videobridge/files/3755150/log.6.txt)
[log.5.txt](https://github.com/jitsi/jitsi-videobridge/files/3755151/log.5.txt)
[log.4.txt](https://github.com/jitsi/jitsi-videobridge/files/3755152/log.4.txt)
[log.3.txt](https://github.com/jitsi/jitsi-videobridge/files/3755153/log.3.txt)
[log.2.txt](https://github.com/jitsi/jitsi-videobridge/files/3755154/log.2.txt)
[log.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3755155/log.1.txt)
[log.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3755156/log.0.txt)
[ffmpeg.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3755157/ffmpeg.1.txt)
[ffmpeg.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3755158/ffmpeg.0.txt)
[browser.1.txt](https://github.com/jitsi/jitsi-videobridge/files/3755159/browser.1.txt)
[browser.0.txt](https://github.com/jitsi/jitsi-videobridge/files/3755160/browser.0.txt)

**Comment by bbaldino** [comment]
> Now I record video without problem, but the sound is not haunting me

What do you mean by this?

Otherwise Jibri logs seem ok, though you don't have a finalize script: `Failed to run finalize script: java.io.IOException: Cannot run program "/path/to/finalize_recording.sh": error=2, No such file or directory with stack: `
