### ISSUE TITLE
Full thread dump OpenJDK 64-Bit Server VM (25.222-b10 mixed mode)

### ISSUE THREAD

**Issue by lequocnam** [jitsi/jitsi-videobridge#969]
## Description
---
Hi all,
I got above issue today, in jitsi server. 
Did anyone get it before? And Why is this happening?
I want to know the cause, to prevent it later.
Thank you!

---
I've attached jicofo.log & jvb.log.
jvb & jicofo & prosody has been installed in the same server.

## Current behavior
---
Can not connect to jitsi room.

# Environment details
---
jvb: 1124
jicofo: 481

Attach log files
---
[jvb.log](https://github.com/jitsi/jitsi-videobridge/files/3812396/jvb.log)
[jicofo.log](https://github.com/jitsi/jitsi-videobridge/files/3812398/jicofo.log)

**Comment by damencho** [comment]
Please, when you have questions or problems first write to the community forum before opening new issues.

What is the problem you had? Did jvb process crash? You had sent thread stack of running jicofo and jvb, which does not mean anything without knowing the context.
What does jvb logs say? How do you run? Have you installed jitsi-meet on one machine, running jicofo and jvb there? What is the available ram on that machine?
