### ISSUE TITLE
Media over Https

### ISSUE THREAD

**Issue by HKApitech** [jitsi/jitsi-videobridge#97]
Hello guys,

I tried to use JVB as https server with one IP address (https://github.com/jitsi/jitsi-videobridge/blob/master/doc/http.md) but it doesn't work for me :( 

So now I'm trying to use the second method (https://github.com/jitsi/jitsi-videobridge/blob/master/doc/tcp.md) when I redirect 443 to 4443 I can't reach Jitsi-meet anymore. Something is wrong...

There are three sip-communicator.properties files :
./root/.sip-communicator/sip-communicator.properties
./etc/jitsi/jicofo/sip-communicator.properties
./etc/jitsi/videobridge/sip-communicator.properties

Which one shoud I actually use ?

Regards,

Hamza

**Comment by bgrozev** [comment]
Closing because it's a question. Please write again on the mailing list if you still need an answer.
